//go:build gogen_ir

// Code generated by lgbgen --target=go. DO NOT EDIT.
// gogen.nsHash:       ab5de6974d37b648545e1ea73ca50975ffcc6fc4b7b065bfd3054dc130c48460
// gogen.pipelineHash: f81a0be759146aabc0b9420eced6c006305bf04f7df82e999fb75a5c8206ea44

package io

import (
	"fmt"

	rt "github.com/nooga/let-go/pkg/rt"
	vm "github.com/nooga/let-go/pkg/vm"
)

func slurp_lines(path_0 vm.Value) (vm.Value, error) {
	var arg__15548_2 vm.Value
	var arg__15553_5 vm.Value
	var v6 vm.Value
	var callErr error
	_, _, _ = arg__15548_2, arg__15553_5, v6
	arg__15548_2, callErr = rt.InvokeValue(rt.LookupVar("io", "read-lines").Deref(), []vm.Value{path_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__15553_5, callErr = rt.InvokeValue(rt.LookupVar("io", "read-lines").Deref(), []vm.Value{path_0})
	if callErr != nil {
		return nil, callErr
	}
	v6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vec").Deref(), []vm.Value{arg__15553_5})
	if callErr != nil {
		return nil, callErr
	}
	return v6, nil
}
func __gogen_wrap(fn func(args []vm.Value) (vm.Value, error)) vm.Value {
	v, _ := vm.NativeFnType.Wrap(fn)
	return v
}
func init() {
	rt.RegisterGoOverrides("io", map[string]vm.Value{"slurp-lines": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("slurp-lines: wrong number of arguments %d (expected 1)", len(args))
		}
		return slurp_lines(args[0])
	}),
	})
}
