//go:build gogen_ir

// Code generated by lgbgen --target=go. DO NOT EDIT.
// gogen.nsHash:       25391108357568ef86c16d6f0a0cd2d16946a292003ec6855cf8eb54c618b945
// gogen.pipelineHash: f81a0be759146aabc0b9420eced6c006305bf04f7df82e999fb75a5c8206ea44

package zipper

import (
	"fmt"

	rt "github.com/nooga/let-go/pkg/rt"
	vm "github.com/nooga/let-go/pkg/vm"
)

func advance_empty(z_0 vm.Value) (vm.Value, error) {
	var z_2 vm.Value
	var z_3 vm.Value
	var v141 vm.Value
	var v148 vm.Value
	var v155 vm.Value
	var v162 vm.Value
	var v169 vm.Value
	var v176 vm.Value
	var v183 vm.Value
	var v190 vm.Value
	var v197 vm.Value
	var v204 int
	var arg__15675_10 vm.Value
	var arg__15681_14 vm.Value
	var arg__15688_19 vm.Value
	var arg__15689_20 vm.Value
	var v21 bool
	var z_5 vm.Value
	var v144 vm.Value
	var v151 vm.Value
	var v158 vm.Value
	var v165 vm.Value
	var v172 vm.Value
	var v179 vm.Value
	var v186 vm.Value
	var v193 vm.Value
	var v200 vm.Value
	var v207 int
	var v28 vm.Value
	var z_6 vm.Value
	var v142 vm.Value
	var v149 vm.Value
	var v156 vm.Value
	var v163 vm.Value
	var v170 vm.Value
	var v177 vm.Value
	var v184 vm.Value
	var v191 vm.Value
	var v198 vm.Value
	var v205 int
	var v106 vm.Value
	var z_107 vm.Value
	var z_30 vm.Value
	var v143 vm.Value
	var v150 vm.Value
	var v157 vm.Value
	var v164 vm.Value
	var v171 vm.Value
	var v178 vm.Value
	var v185 vm.Value
	var v192 vm.Value
	var v199 vm.Value
	var v206 int
	var arg__15702_37 vm.Value
	var arg__15708_41 vm.Value
	var arg__15715_46 vm.Value
	var arg__15721_50 vm.Value
	var block_51 vm.Value
	var arg__15728_55 vm.Value
	var arg__15736_60 vm.Value
	var insts_61 vm.Value
	var arg__15742_71 vm.Value
	var arg__15746_73 vm.Value
	var v74 bool
	var z_31 vm.Value
	var v145 vm.Value
	var v152 vm.Value
	var v159 vm.Value
	var v166 vm.Value
	var v173 vm.Value
	var v180 vm.Value
	var v187 vm.Value
	var v194 vm.Value
	var v201 vm.Value
	var v208 int
	var v103 vm.Value
	var z_104 vm.Value
	var z_62 vm.Value
	var block_63 vm.Value
	var insts_64 vm.Value
	var v140 vm.Value
	var v147 vm.Value
	var v154 vm.Value
	var v161 vm.Value
	var v168 vm.Value
	var v175 vm.Value
	var v182 vm.Value
	var v189 vm.Value
	var v196 vm.Value
	var v203 int
	var arg__15754_80 vm.Value
	var arg__15766_89 vm.Value
	var arg__15767_90 vm.Value
	var v93 vm.Value
	var z_65 vm.Value
	var block_66 vm.Value
	var insts_67 vm.Value
	var v146 vm.Value
	var v153 vm.Value
	var v160 vm.Value
	var v167 vm.Value
	var v174 vm.Value
	var v181 vm.Value
	var v188 vm.Value
	var v195 vm.Value
	var v202 vm.Value
	var v209 int
	var v96 vm.Value
	var z_97 vm.Value
	var block_98 vm.Value
	var insts_99 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = z_2, z_3, v141, v148, v155, v162, v169, v176, v183, v190, v197, v204, arg__15675_10, arg__15681_14, arg__15688_19, arg__15689_20, v21, z_5, v144, v151, v158, v165, v172, v179, v186, v193, v200, v207, v28, z_6, v142, v149, v156, v163, v170, v177, v184, v191, v198, v205, v106, z_107, z_30, v143, v150, v157, v164, v171, v178, v185, v192, v199, v206, arg__15702_37, arg__15708_41, arg__15715_46, arg__15721_50, block_51, arg__15728_55, arg__15736_60, insts_61, arg__15742_71, arg__15746_73, v74, z_31, v145, v152, v159, v166, v173, v180, v187, v194, v201, v208, v103, z_104, z_62, block_63, insts_64, v140, v147, v154, v161, v168, v175, v182, v189, v196, v203, arg__15754_80, arg__15766_89, arg__15767_90, v93, z_65, block_66, insts_67, v146, v153, v160, v167, v174, v181, v188, v195, v202, v209, v96, z_97, block_98, insts_99
	z_2 = z_0
	z_3 = z_0
	v141 = vm.Keyword("block-idx")
	v148 = vm.Keyword("blocks")
	v155 = vm.Keyword("else")
	v162 = vm.Keyword("blocks")
	v169 = vm.Keyword("block-idx")
	v176 = vm.Keyword("fn")
	v183 = vm.Keyword("inst-idx")
	v190 = vm.Keyword("block-idx")
	v197 = vm.Keyword("inst-idx")
	v204 = 0
	goto b1
b1:
	;
	arg__15675_10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_3, v141})
	if callErr != nil {
		return nil, callErr
	}
	arg__15681_14, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_3, v148})
	if callErr != nil {
		return nil, callErr
	}
	arg__15688_19, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_3, v148})
	if callErr != nil {
		return nil, callErr
	}
	arg__15689_20, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "count").Deref(), []vm.Value{arg__15688_19})
	if callErr != nil {
		return nil, callErr
	}
	v21 = rt.GeValue(arg__15675_10, arg__15689_20)
	if v21 {
		z_5 = z_3
		v144 = v141
		v151 = v148
		v158 = v155
		v165 = v162
		v172 = v169
		v179 = v176
		v186 = v183
		v193 = v190
		v200 = v197
		v207 = v204
		goto b2
	} else {
		z_6 = z_3
		v142 = v141
		v149 = v148
		v156 = v155
		v163 = v162
		v170 = v169
		v177 = v176
		v184 = v183
		v191 = v190
		v198 = v197
		v205 = v204
		goto b3
	}
b2:
	;
	v28, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "assoc").Deref(), []vm.Value{z_5, vm.Keyword("ended"), vm.Boolean(true)})
	if callErr != nil {
		return nil, callErr
	}
	v106 = v28
	z_107 = z_5
	goto b4
b3:
	;
	if vm.IsTruthy(v156) {
		z_30 = z_6
		v143 = v142
		v150 = v149
		v157 = v156
		v164 = v163
		v171 = v170
		v178 = v177
		v185 = v184
		v192 = v191
		v199 = v198
		v206 = v205
		goto b5
	} else {
		z_31 = z_6
		v145 = v142
		v152 = v149
		v159 = v156
		v166 = v163
		v173 = v170
		v180 = v177
		v187 = v184
		v194 = v191
		v201 = v198
		v208 = v205
		goto b6
	}
b4:
	;
	return v106, nil
b5:
	;
	arg__15702_37, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_30, v164})
	if callErr != nil {
		return nil, callErr
	}
	arg__15708_41, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_30, v171})
	if callErr != nil {
		return nil, callErr
	}
	arg__15715_46, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_30, v164})
	if callErr != nil {
		return nil, callErr
	}
	arg__15721_50, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_30, v171})
	if callErr != nil {
		return nil, callErr
	}
	block_51, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{arg__15715_46, arg__15721_50})
	if callErr != nil {
		return nil, callErr
	}
	arg__15728_55, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_30, v178})
	if callErr != nil {
		return nil, callErr
	}
	arg__15736_60, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_30, v178})
	if callErr != nil {
		return nil, callErr
	}
	insts_61, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-insts").Deref(), []vm.Value{block_51, arg__15736_60})
	if callErr != nil {
		return nil, callErr
	}
	arg__15742_71, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_30, v185})
	if callErr != nil {
		return nil, callErr
	}
	arg__15746_73, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "count").Deref(), []vm.Value{insts_61})
	if callErr != nil {
		return nil, callErr
	}
	v74 = rt.GeValue(arg__15742_71, arg__15746_73)
	if v74 {
		z_62 = z_30
		block_63 = block_51
		insts_64 = insts_61
		v140 = v143
		v147 = v150
		v154 = v157
		v161 = v164
		v168 = v171
		v175 = v178
		v182 = v185
		v189 = v192
		v196 = v199
		v203 = v206
		goto b8
	} else {
		z_65 = z_30
		block_66 = block_51
		insts_67 = insts_61
		v146 = v143
		v153 = v150
		v160 = v157
		v167 = v164
		v174 = v171
		v181 = v178
		v188 = v185
		v195 = v192
		v202 = v199
		v209 = v206
		goto b9
	}
b6:
	;
	v103 = vm.NIL
	z_104 = z_31
	goto b7
b7:
	;
	v106 = v103
	z_107 = z_104
	goto b4
b8:
	;
	arg__15754_80, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_62, v189})
	if callErr != nil {
		return nil, callErr
	}
	arg__15766_89, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_62, v189})
	if callErr != nil {
		return nil, callErr
	}
	arg__15767_90 = rt.AddValue(arg__15766_89, vm.Int(1))
	v93, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "assoc").Deref(), []vm.Value{z_62, v189, arg__15767_90, v196, vm.Int(v203)})
	if callErr != nil {
		return nil, callErr
	}
	z_2 = v93
	z_3 = z_62
	v141 = v140
	v148 = v147
	v155 = v154
	v162 = v161
	v169 = v168
	v176 = v175
	v183 = v182
	v190 = v189
	v197 = v196
	v204 = v203
	goto b1
b9:
	;
	v96 = z_65
	z_97 = z_65
	block_98 = block_66
	insts_99 = insts_67
	goto b10
b10:
	;
	v103 = v96
	z_104 = z_97
	goto b7
}
func end_QMARK_(z_0 vm.Value) (vm.Value, error) {
	var v4 vm.Value
	var callErr error
	_ = v4
	v4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_0, vm.Keyword("ended")})
	if callErr != nil {
		return nil, callErr
	}
	return v4, nil
}
func next(z_0 vm.Value) (vm.Value, error) {
	var v5 vm.Value
	var z_2 vm.Value
	var z_3 vm.Value
	var arg__15785_12 vm.Value
	var arg__15795_19 vm.Value
	var arg__15796_20 vm.Value
	var arg__15797_21 vm.Value
	var arg__15806_27 vm.Value
	var arg__15816_34 vm.Value
	var arg__15817_35 vm.Value
	var arg__15818_36 vm.Value
	var v37 vm.Value
	var v39 vm.Value
	var z_40 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _, _ = v5, z_2, z_3, arg__15785_12, arg__15795_19, arg__15796_20, arg__15797_21, arg__15806_27, arg__15816_34, arg__15817_35, arg__15818_36, v37, v39, z_40
	v5, callErr = rt.InvokeValue(rt.LookupVar("ir.zipper", "end?").Deref(), []vm.Value{z_0})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v5) {
		z_2 = z_0
		goto b1
	} else {
		z_3 = z_0
		goto b2
	}
b1:
	;
	v39 = z_2
	z_40 = z_2
	goto b3
b2:
	;
	arg__15785_12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_3, vm.Keyword("inst-idx")})
	if callErr != nil {
		return nil, callErr
	}
	arg__15795_19, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_3, vm.Keyword("inst-idx")})
	if callErr != nil {
		return nil, callErr
	}
	arg__15796_20 = rt.AddValue(arg__15795_19, vm.Int(1))
	arg__15797_21, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "assoc").Deref(), []vm.Value{z_3, vm.Keyword("inst-idx"), arg__15796_20})
	if callErr != nil {
		return nil, callErr
	}
	arg__15806_27, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_3, vm.Keyword("inst-idx")})
	if callErr != nil {
		return nil, callErr
	}
	arg__15816_34, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_3, vm.Keyword("inst-idx")})
	if callErr != nil {
		return nil, callErr
	}
	arg__15817_35 = rt.AddValue(arg__15816_34, vm.Int(1))
	arg__15818_36, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "assoc").Deref(), []vm.Value{z_3, vm.Keyword("inst-idx"), arg__15817_35})
	if callErr != nil {
		return nil, callErr
	}
	v37, callErr = rt.InvokeValue(rt.LookupVar("ir.zipper", "advance-empty").Deref(), []vm.Value{arg__15818_36})
	if callErr != nil {
		return nil, callErr
	}
	v39 = v37
	z_40 = z_3
	goto b3
b3:
	;
	return v39, nil
}
func current_block(z_0 vm.Value) (vm.Value, error) {
	var v4 vm.Value
	var z_1 vm.Value
	var z_2 vm.Value
	var arg__15827_11 vm.Value
	var arg__15833_15 vm.Value
	var arg__15840_20 vm.Value
	var arg__15846_24 vm.Value
	var v25 vm.Value
	var v27 vm.Value
	var z_28 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _ = v4, z_1, z_2, arg__15827_11, arg__15833_15, arg__15840_20, arg__15846_24, v25, v27, z_28
	v4, callErr = rt.InvokeValue(rt.LookupVar("ir.zipper", "end?").Deref(), []vm.Value{z_0})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v4) {
		z_1 = z_0
		goto b1
	} else {
		z_2 = z_0
		goto b2
	}
b1:
	;
	v27 = vm.NIL
	z_28 = z_1
	goto b3
b2:
	;
	arg__15827_11, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_2, vm.Keyword("blocks")})
	if callErr != nil {
		return nil, callErr
	}
	arg__15833_15, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_2, vm.Keyword("block-idx")})
	if callErr != nil {
		return nil, callErr
	}
	arg__15840_20, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_2, vm.Keyword("blocks")})
	if callErr != nil {
		return nil, callErr
	}
	arg__15846_24, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_2, vm.Keyword("block-idx")})
	if callErr != nil {
		return nil, callErr
	}
	v25, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{arg__15840_20, arg__15846_24})
	if callErr != nil {
		return nil, callErr
	}
	v27 = v25
	z_28 = z_2
	goto b3
b3:
	;
	return v27, nil
}
func node(z_0 vm.Value) (vm.Value, error) {
	var v5 vm.Value
	var z_2 vm.Value
	var z_3 vm.Value
	var arg__15853_10 vm.Value
	var arg__15859_14 vm.Value
	var arg__15864_17 vm.Value
	var arg__15870_21 vm.Value
	var insts_22 vm.Value
	var arg__15877_26 vm.Value
	var arg__15885_31 vm.Value
	var v32 vm.Value
	var v34 vm.Value
	var z_35 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _ = v5, z_2, z_3, arg__15853_10, arg__15859_14, arg__15864_17, arg__15870_21, insts_22, arg__15877_26, arg__15885_31, v32, v34, z_35
	v5, callErr = rt.InvokeValue(rt.LookupVar("ir.zipper", "end?").Deref(), []vm.Value{z_0})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v5) {
		z_2 = z_0
		goto b1
	} else {
		z_3 = z_0
		goto b2
	}
b1:
	;
	v34 = vm.NIL
	z_35 = z_2
	goto b3
b2:
	;
	arg__15853_10, callErr = rt.InvokeValue(rt.LookupVar("ir.zipper", "current-block").Deref(), []vm.Value{z_3})
	if callErr != nil {
		return nil, callErr
	}
	arg__15859_14, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_3, vm.Keyword("fn")})
	if callErr != nil {
		return nil, callErr
	}
	arg__15864_17, callErr = rt.InvokeValue(rt.LookupVar("ir.zipper", "current-block").Deref(), []vm.Value{z_3})
	if callErr != nil {
		return nil, callErr
	}
	arg__15870_21, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_3, vm.Keyword("fn")})
	if callErr != nil {
		return nil, callErr
	}
	insts_22, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-insts").Deref(), []vm.Value{arg__15864_17, arg__15870_21})
	if callErr != nil {
		return nil, callErr
	}
	arg__15877_26, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_3, vm.Keyword("inst-idx")})
	if callErr != nil {
		return nil, callErr
	}
	arg__15885_31, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_3, vm.Keyword("inst-idx")})
	if callErr != nil {
		return nil, callErr
	}
	v32, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{insts_22, arg__15885_31})
	if callErr != nil {
		return nil, callErr
	}
	v34 = v32
	z_35 = z_3
	goto b3
b3:
	;
	return v34, nil
}
func ir_zipper(f_0 vm.Value) (vm.Value, error) {
	var blocks_3 vm.Value
	var arg__15900_13 vm.Value
	var arg__15913_24 vm.Value
	var v25 vm.Value
	var callErr error
	_, _, _, _ = blocks_3, arg__15900_13, arg__15913_24, v25
	blocks_3, callErr = rt.InvokeValue(rt.LookupVar("ir", "blocks").Deref(), []vm.Value{f_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__15900_13, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "array-map").Deref(), []vm.Value{vm.Keyword("ended"), vm.Boolean(false), vm.Keyword("inst-idx"), vm.Int(0), vm.Keyword("fn"), f_0, vm.Keyword("block-idx"), vm.Int(0), vm.Keyword("blocks"), blocks_3})
	if callErr != nil {
		return nil, callErr
	}
	arg__15913_24, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "array-map").Deref(), []vm.Value{vm.Keyword("ended"), vm.Boolean(false), vm.Keyword("inst-idx"), vm.Int(0), vm.Keyword("fn"), f_0, vm.Keyword("block-idx"), vm.Int(0), vm.Keyword("blocks"), blocks_3})
	if callErr != nil {
		return nil, callErr
	}
	v25, callErr = rt.InvokeValue(rt.LookupVar("ir.zipper", "advance-empty").Deref(), []vm.Value{arg__15913_24})
	if callErr != nil {
		return nil, callErr
	}
	return v25, nil
}
func fn_of(z_0 vm.Value) (vm.Value, error) {
	var v4 vm.Value
	var callErr error
	_ = v4
	v4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{z_0, vm.Keyword("fn")})
	if callErr != nil {
		return nil, callErr
	}
	return v4, nil
}
func __gogen_wrap(fn func(args []vm.Value) (vm.Value, error)) vm.Value {
	v, _ := vm.NativeFnType.Wrap(fn)
	return v
}
func init() {
	rt.RegisterGoOverrides("ir.zipper", map[string]vm.Value{"advance-empty": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("advance-empty: wrong number of arguments %d (expected 1)", len(args))
		}
		return advance_empty(args[0])
	}), "end?": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("end?: wrong number of arguments %d (expected 1)", len(args))
		}
		return end_QMARK_(args[0])
	}), "next": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("next: wrong number of arguments %d (expected 1)", len(args))
		}
		return next(args[0])
	}), "current-block": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("current-block: wrong number of arguments %d (expected 1)", len(args))
		}
		return current_block(args[0])
	}), "node": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("node: wrong number of arguments %d (expected 1)", len(args))
		}
		return node(args[0])
	}), "ir-zipper": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("ir-zipper: wrong number of arguments %d (expected 1)", len(args))
		}
		return ir_zipper(args[0])
	}), "fn-of": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("fn-of: wrong number of arguments %d (expected 1)", len(args))
		}
		return fn_of(args[0])
	}),
	})
}
