//go:build gogen_ir

// Code generated by lgbgen --target=go. DO NOT EDIT.
// gogen.nsHash:       a2ca89aeaf20ba15c1eeb8a10a8b180ad3f5d4b6772dd1095a053c897d75f7b1
// gogen.pipelineHash: f81a0be759146aabc0b9420eced6c006305bf04f7df82e999fb75a5c8206ea44

package string

import (
	"fmt"

	rt "github.com/nooga/let-go/pkg/rt"
	vm "github.com/nooga/let-go/pkg/vm"
)

func lower_case(s_0 vm.Value) (vm.Value, error) {
	var v4 vm.Value
	var s_1 vm.Value
	var v9 vm.Value
	var s_2 vm.Value
	var v13 vm.Value
	var s_14 vm.Value
	var arg__14198_16 vm.Value
	var arg__14203_19 vm.Value
	var v20 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _ = v4, s_1, v9, s_2, v13, s_14, arg__14198_16, arg__14203_19, v20
	v4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nil?").Deref(), []vm.Value{s_0})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v4) {
		s_1 = s_0
		goto b1
	} else {
		s_2 = s_0
		goto b2
	}
b1:
	;
	v9, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "throw").Deref(), []vm.Value{vm.String("lower-case expected non-nil")})
	if callErr != nil {
		return nil, callErr
	}
	v13 = v9
	s_14 = s_1
	goto b3
b2:
	;
	v13 = vm.NIL
	s_14 = s_2
	goto b3
b3:
	;
	arg__14198_16, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "str").Deref(), []vm.Value{s_14})
	if callErr != nil {
		return nil, callErr
	}
	arg__14203_19, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "str").Deref(), []vm.Value{s_14})
	if callErr != nil {
		return nil, callErr
	}
	v20, callErr = lower_case(arg__14203_19)
	if callErr != nil {
		return nil, callErr
	}
	return v20, nil
}
func upper_case(s_0 vm.Value) (vm.Value, error) {
	var v4 vm.Value
	var s_1 vm.Value
	var v9 vm.Value
	var s_2 vm.Value
	var v13 vm.Value
	var s_14 vm.Value
	var arg__14213_16 vm.Value
	var arg__14218_19 vm.Value
	var v20 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _ = v4, s_1, v9, s_2, v13, s_14, arg__14213_16, arg__14218_19, v20
	v4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nil?").Deref(), []vm.Value{s_0})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v4) {
		s_1 = s_0
		goto b1
	} else {
		s_2 = s_0
		goto b2
	}
b1:
	;
	v9, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "throw").Deref(), []vm.Value{vm.String("upper-case expected non-nil")})
	if callErr != nil {
		return nil, callErr
	}
	v13 = v9
	s_14 = s_1
	goto b3
b2:
	;
	v13 = vm.NIL
	s_14 = s_2
	goto b3
b3:
	;
	arg__14213_16, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "str").Deref(), []vm.Value{s_14})
	if callErr != nil {
		return nil, callErr
	}
	arg__14218_19, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "str").Deref(), []vm.Value{s_14})
	if callErr != nil {
		return nil, callErr
	}
	v20, callErr = upper_case(arg__14218_19)
	if callErr != nil {
		return nil, callErr
	}
	return v20, nil
}
func replace(s_0 vm.Value, match_1 vm.Value, replacement_2 vm.Value) (vm.Value, error) {
	var v4 vm.Value
	var callErr error
	_ = v4
	v4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "str-replace").Deref(), []vm.Value{s_0, match_1, replacement_2})
	if callErr != nil {
		return nil, callErr
	}
	return v4, nil
}
func ends_with_QMARK_(s_0 vm.Value, substr_1 vm.Value) (vm.Value, error) {
	var v7 vm.Value
	var s_2 vm.Value
	var substr_3 vm.Value
	var v12 vm.Value
	var s_4 vm.Value
	var substr_5 vm.Value
	var v16 vm.Value
	var s_17 vm.Value
	var substr_18 vm.Value
	var arg__14235_24 vm.Value
	var arg__14240_27 vm.Value
	var v28 vm.Value
	var s_19 vm.Value
	var substr_20 vm.Value
	var v33 vm.Value
	var s_21 vm.Value
	var substr_22 vm.Value
	var v37 vm.Value
	var s_38 vm.Value
	var substr_39 vm.Value
	var arg__14247_41 vm.Value
	var arg__14253_44 vm.Value
	var v45 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = v7, s_2, substr_3, v12, s_4, substr_5, v16, s_17, substr_18, arg__14235_24, arg__14240_27, v28, s_19, substr_20, v33, s_21, substr_22, v37, s_38, substr_39, arg__14247_41, arg__14253_44, v45
	v7, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nil?").Deref(), []vm.Value{s_0})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v7) {
		s_2 = s_0
		substr_3 = substr_1
		goto b1
	} else {
		s_4 = s_0
		substr_5 = substr_1
		goto b2
	}
b1:
	;
	v12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "throw").Deref(), []vm.Value{vm.String("ends-with? expected non-nil string")})
	if callErr != nil {
		return nil, callErr
	}
	v16 = v12
	s_17 = s_2
	substr_18 = substr_3
	goto b3
b2:
	;
	v16 = vm.NIL
	s_17 = s_4
	substr_18 = substr_5
	goto b3
b3:
	;
	arg__14235_24, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "string?").Deref(), []vm.Value{substr_18})
	if callErr != nil {
		return nil, callErr
	}
	arg__14240_27, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "string?").Deref(), []vm.Value{substr_18})
	if callErr != nil {
		return nil, callErr
	}
	v28, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "not").Deref(), []vm.Value{arg__14240_27})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v28) {
		s_19 = s_17
		substr_20 = substr_18
		goto b4
	} else {
		s_21 = s_17
		substr_22 = substr_18
		goto b5
	}
b4:
	;
	v33, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "throw").Deref(), []vm.Value{vm.String("ends-with? expected String suffix")})
	if callErr != nil {
		return nil, callErr
	}
	v37 = v33
	s_38 = s_19
	substr_39 = substr_20
	goto b6
b5:
	;
	v37 = vm.NIL
	s_38 = s_21
	substr_39 = substr_22
	goto b6
b6:
	;
	arg__14247_41, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "str").Deref(), []vm.Value{s_38})
	if callErr != nil {
		return nil, callErr
	}
	arg__14253_44, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "str").Deref(), []vm.Value{s_38})
	if callErr != nil {
		return nil, callErr
	}
	v45, callErr = ends_with_QMARK_(arg__14253_44, substr_39)
	if callErr != nil {
		return nil, callErr
	}
	return v45, nil
}
func capitalize(s_0 vm.Value) (vm.Value, error) {
	var v4 vm.Value
	var s_1 vm.Value
	var v9 vm.Value
	var s_2 vm.Value
	var v13 vm.Value
	var s_14 vm.Value
	var s_16 vm.Value
	var v20 bool
	var s_17 vm.Value
	var s_18 vm.Value
	var arg__14273_28 vm.Value
	var arg__14282_35 vm.Value
	var arg__14283_36 vm.Value
	var arg__14289_40 vm.Value
	var arg__14296_45 vm.Value
	var arg__14297_46 vm.Value
	var arg__14306_53 vm.Value
	var arg__14315_60 vm.Value
	var arg__14316_61 vm.Value
	var arg__14322_65 vm.Value
	var arg__14329_70 vm.Value
	var arg__14330_71 vm.Value
	var v72 vm.Value
	var v74 vm.Value
	var s_75 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = v4, s_1, v9, s_2, v13, s_14, s_16, v20, s_17, s_18, arg__14273_28, arg__14282_35, arg__14283_36, arg__14289_40, arg__14296_45, arg__14297_46, arg__14306_53, arg__14315_60, arg__14316_61, arg__14322_65, arg__14329_70, arg__14330_71, v72, v74, s_75
	v4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nil?").Deref(), []vm.Value{s_0})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v4) {
		s_1 = s_0
		goto b1
	} else {
		s_2 = s_0
		goto b2
	}
b1:
	;
	v9, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "throw").Deref(), []vm.Value{vm.String("capitalize expected non-nil")})
	if callErr != nil {
		return nil, callErr
	}
	v13 = v9
	s_14 = s_1
	goto b3
b2:
	;
	v13 = vm.NIL
	s_14 = s_2
	goto b3
b3:
	;
	s_16, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "str").Deref(), []vm.Value{s_14})
	if callErr != nil {
		return nil, callErr
	}
	v20 = rt.EqValue(s_16, vm.String(""))
	if v20 {
		s_17 = s_16
		goto b4
	} else {
		s_18 = s_16
		goto b5
	}
b4:
	;
	v74 = s_17
	s_75 = s_17
	goto b6
b5:
	;
	arg__14273_28, callErr = rt.InvokeValue(rt.LookupVar("clojure.string", "subs").Deref(), []vm.Value{s_18, vm.Int(0), vm.Int(1)})
	if callErr != nil {
		return nil, callErr
	}
	arg__14282_35, callErr = rt.InvokeValue(rt.LookupVar("clojure.string", "subs").Deref(), []vm.Value{s_18, vm.Int(0), vm.Int(1)})
	if callErr != nil {
		return nil, callErr
	}
	arg__14283_36, callErr = rt.InvokeValue(rt.LookupVar("clojure.string", "upper-case").Deref(), []vm.Value{arg__14282_35})
	if callErr != nil {
		return nil, callErr
	}
	arg__14289_40, callErr = rt.InvokeValue(rt.LookupVar("clojure.string", "subs").Deref(), []vm.Value{s_18, vm.Int(1)})
	if callErr != nil {
		return nil, callErr
	}
	arg__14296_45, callErr = rt.InvokeValue(rt.LookupVar("clojure.string", "subs").Deref(), []vm.Value{s_18, vm.Int(1)})
	if callErr != nil {
		return nil, callErr
	}
	arg__14297_46, callErr = rt.InvokeValue(rt.LookupVar("clojure.string", "lower-case").Deref(), []vm.Value{arg__14296_45})
	if callErr != nil {
		return nil, callErr
	}
	arg__14306_53, callErr = rt.InvokeValue(rt.LookupVar("clojure.string", "subs").Deref(), []vm.Value{s_18, vm.Int(0), vm.Int(1)})
	if callErr != nil {
		return nil, callErr
	}
	arg__14315_60, callErr = rt.InvokeValue(rt.LookupVar("clojure.string", "subs").Deref(), []vm.Value{s_18, vm.Int(0), vm.Int(1)})
	if callErr != nil {
		return nil, callErr
	}
	arg__14316_61, callErr = rt.InvokeValue(rt.LookupVar("clojure.string", "upper-case").Deref(), []vm.Value{arg__14315_60})
	if callErr != nil {
		return nil, callErr
	}
	arg__14322_65, callErr = rt.InvokeValue(rt.LookupVar("clojure.string", "subs").Deref(), []vm.Value{s_18, vm.Int(1)})
	if callErr != nil {
		return nil, callErr
	}
	arg__14329_70, callErr = rt.InvokeValue(rt.LookupVar("clojure.string", "subs").Deref(), []vm.Value{s_18, vm.Int(1)})
	if callErr != nil {
		return nil, callErr
	}
	arg__14330_71, callErr = rt.InvokeValue(rt.LookupVar("clojure.string", "lower-case").Deref(), []vm.Value{arg__14329_70})
	if callErr != nil {
		return nil, callErr
	}
	v72, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "str").Deref(), []vm.Value{arg__14316_61, arg__14330_71})
	if callErr != nil {
		return nil, callErr
	}
	v74 = v72
	s_75 = s_18
	goto b6
b6:
	;
	return v74, nil
}
func starts_with_QMARK_(s_0 vm.Value, substr_1 vm.Value) (vm.Value, error) {
	var v7 vm.Value
	var s_2 vm.Value
	var substr_3 vm.Value
	var v12 vm.Value
	var s_4 vm.Value
	var substr_5 vm.Value
	var v16 vm.Value
	var s_17 vm.Value
	var substr_18 vm.Value
	var arg__14340_24 vm.Value
	var arg__14345_27 vm.Value
	var v28 vm.Value
	var s_19 vm.Value
	var substr_20 vm.Value
	var v33 vm.Value
	var s_21 vm.Value
	var substr_22 vm.Value
	var v37 vm.Value
	var s_38 vm.Value
	var substr_39 vm.Value
	var arg__14352_41 vm.Value
	var arg__14358_44 vm.Value
	var v45 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = v7, s_2, substr_3, v12, s_4, substr_5, v16, s_17, substr_18, arg__14340_24, arg__14345_27, v28, s_19, substr_20, v33, s_21, substr_22, v37, s_38, substr_39, arg__14352_41, arg__14358_44, v45
	v7, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nil?").Deref(), []vm.Value{s_0})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v7) {
		s_2 = s_0
		substr_3 = substr_1
		goto b1
	} else {
		s_4 = s_0
		substr_5 = substr_1
		goto b2
	}
b1:
	;
	v12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "throw").Deref(), []vm.Value{vm.String("starts-with? expected non-nil string")})
	if callErr != nil {
		return nil, callErr
	}
	v16 = v12
	s_17 = s_2
	substr_18 = substr_3
	goto b3
b2:
	;
	v16 = vm.NIL
	s_17 = s_4
	substr_18 = substr_5
	goto b3
b3:
	;
	arg__14340_24, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "string?").Deref(), []vm.Value{substr_18})
	if callErr != nil {
		return nil, callErr
	}
	arg__14345_27, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "string?").Deref(), []vm.Value{substr_18})
	if callErr != nil {
		return nil, callErr
	}
	v28, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "not").Deref(), []vm.Value{arg__14345_27})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v28) {
		s_19 = s_17
		substr_20 = substr_18
		goto b4
	} else {
		s_21 = s_17
		substr_22 = substr_18
		goto b5
	}
b4:
	;
	v33, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "throw").Deref(), []vm.Value{vm.String("starts-with? expected String prefix")})
	if callErr != nil {
		return nil, callErr
	}
	v37 = v33
	s_38 = s_19
	substr_39 = substr_20
	goto b6
b5:
	;
	v37 = vm.NIL
	s_38 = s_21
	substr_39 = substr_22
	goto b6
b6:
	;
	arg__14352_41, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "str").Deref(), []vm.Value{s_38})
	if callErr != nil {
		return nil, callErr
	}
	arg__14358_44, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "str").Deref(), []vm.Value{s_38})
	if callErr != nil {
		return nil, callErr
	}
	v45, callErr = starts_with_QMARK_(arg__14358_44, substr_39)
	if callErr != nil {
		return nil, callErr
	}
	return v45, nil
}
func reverse(s_0 vm.Value) (vm.Value, error) {
	var v4 vm.Value
	var s_1 vm.Value
	var v9 vm.Value
	var s_2 vm.Value
	var v13 vm.Value
	var s_14 vm.Value
	var arg__14370_17 vm.Value
	var arg__14375_20 vm.Value
	var arg__14376_21 vm.Value
	var arg__14382_25 vm.Value
	var arg__14387_28 vm.Value
	var arg__14388_29 vm.Value
	var v30 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _ = v4, s_1, v9, s_2, v13, s_14, arg__14370_17, arg__14375_20, arg__14376_21, arg__14382_25, arg__14387_28, arg__14388_29, v30
	v4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nil?").Deref(), []vm.Value{s_0})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v4) {
		s_1 = s_0
		goto b1
	} else {
		s_2 = s_0
		goto b2
	}
b1:
	;
	v9, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "throw").Deref(), []vm.Value{vm.String("reverse expected non-nil")})
	if callErr != nil {
		return nil, callErr
	}
	v13 = v9
	s_14 = s_1
	goto b3
b2:
	;
	v13 = vm.NIL
	s_14 = s_2
	goto b3
b3:
	;
	arg__14370_17, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vec").Deref(), []vm.Value{s_14})
	if callErr != nil {
		return nil, callErr
	}
	arg__14375_20, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vec").Deref(), []vm.Value{s_14})
	if callErr != nil {
		return nil, callErr
	}
	arg__14376_21, callErr = reverse(arg__14375_20)
	if callErr != nil {
		return nil, callErr
	}
	arg__14382_25, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vec").Deref(), []vm.Value{s_14})
	if callErr != nil {
		return nil, callErr
	}
	arg__14387_28, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vec").Deref(), []vm.Value{s_14})
	if callErr != nil {
		return nil, callErr
	}
	arg__14388_29, callErr = reverse(arg__14387_28)
	if callErr != nil {
		return nil, callErr
	}
	v30, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "apply").Deref(), []vm.Value{rt.LookupVar("clojure.core", "str").Deref(), arg__14388_29})
	if callErr != nil {
		return nil, callErr
	}
	return v30, nil
}
func escape(s_0 vm.Value, cmap_1 vm.Value) (vm.Value, error) {
	var arg__14392_7 vm.Value
	var arg__14397_10 vm.Value
	var v11 vm.Value
	var s_2 vm.Value
	var cmap_3 vm.Value
	var v16 vm.Value
	var s_4 vm.Value
	var cmap_5 vm.Value
	var v20 vm.Value
	var s_21 vm.Value
	var cmap_22 vm.Value
	var arg__14417_31 vm.Value
	var arg__14435_41 vm.Value
	var v42 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _, _ = arg__14392_7, arg__14397_10, v11, s_2, cmap_3, v16, s_4, cmap_5, v20, s_21, cmap_22, arg__14417_31, arg__14435_41, v42
	arg__14392_7, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "string?").Deref(), []vm.Value{s_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__14397_10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "string?").Deref(), []vm.Value{s_0})
	if callErr != nil {
		return nil, callErr
	}
	v11, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "not").Deref(), []vm.Value{arg__14397_10})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v11) {
		s_2 = s_0
		cmap_3 = cmap_1
		goto b1
	} else {
		s_4 = s_0
		cmap_5 = cmap_1
		goto b2
	}
b1:
	;
	v16, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "throw").Deref(), []vm.Value{vm.String("escape expected String")})
	if callErr != nil {
		return nil, callErr
	}
	v20 = v16
	s_21 = s_2
	cmap_22 = cmap_3
	goto b3
b2:
	;
	v20 = vm.NIL
	s_21 = s_4
	cmap_22 = cmap_5
	goto b3
b3:
	;
	arg__14417_31, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{rt.BoxNativeFn(func(c_0_c1 vm.Value) (vm.Value, error) {
		var or__x_3_c1 vm.Value
		var c_4_c1 vm.Value
		var cmap_5_c1 vm.Value
		var or__x_6_c1 vm.Value
		var c_7_c1 vm.Value
		var cmap_8_c1 vm.Value
		var or__x_9_c1 vm.Value
		var v13_c1 vm.Value
		var c_14_c1 vm.Value
		var cmap_15_c1 vm.Value
		var or__x_16_c1 vm.Value
		var callErr error
		_, _, _, _, _, _, _, _, _, _, _ = or__x_3_c1, c_4_c1, cmap_5_c1, or__x_6_c1, c_7_c1, cmap_8_c1, or__x_9_c1, v13_c1, c_14_c1, cmap_15_c1, or__x_16_c1
		or__x_3_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{cmap_22, c_0_c1})
		if callErr != nil {
			return nil, callErr
		}
		if vm.IsTruthy(or__x_3_c1) {
			c_4_c1 = c_0_c1
			cmap_5_c1 = cmap_22
			or__x_6_c1 = or__x_3_c1
			goto b1
		} else {
			c_7_c1 = c_0_c1
			cmap_8_c1 = cmap_22
			or__x_9_c1 = or__x_3_c1
			goto b2
		}
	b1:
		;
		v13_c1 = or__x_6_c1
		c_14_c1 = c_4_c1
		cmap_15_c1 = cmap_5_c1
		or__x_16_c1 = or__x_6_c1
		goto b3
	b2:
		;
		v13_c1 = c_7_c1
		c_14_c1 = c_7_c1
		cmap_15_c1 = cmap_8_c1
		or__x_16_c1 = or__x_9_c1
		goto b3
	b3:
		;
		return v13_c1, nil
	}), s_21})
	if callErr != nil {
		return nil, callErr
	}
	arg__14435_41, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{rt.BoxNativeFn(func(c_0_c2 vm.Value) (vm.Value, error) {
		var or__x_3_c2 vm.Value
		var c_4_c2 vm.Value
		var cmap_5_c2 vm.Value
		var or__x_6_c2 vm.Value
		var c_7_c2 vm.Value
		var cmap_8_c2 vm.Value
		var or__x_9_c2 vm.Value
		var v13_c2 vm.Value
		var c_14_c2 vm.Value
		var cmap_15_c2 vm.Value
		var or__x_16_c2 vm.Value
		var callErr error
		_, _, _, _, _, _, _, _, _, _, _ = or__x_3_c2, c_4_c2, cmap_5_c2, or__x_6_c2, c_7_c2, cmap_8_c2, or__x_9_c2, v13_c2, c_14_c2, cmap_15_c2, or__x_16_c2
		or__x_3_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{cmap_22, c_0_c2})
		if callErr != nil {
			return nil, callErr
		}
		if vm.IsTruthy(or__x_3_c2) {
			c_4_c2 = c_0_c2
			cmap_5_c2 = cmap_22
			or__x_6_c2 = or__x_3_c2
			goto b1
		} else {
			c_7_c2 = c_0_c2
			cmap_8_c2 = cmap_22
			or__x_9_c2 = or__x_3_c2
			goto b2
		}
	b1:
		;
		v13_c2 = or__x_6_c2
		c_14_c2 = c_4_c2
		cmap_15_c2 = cmap_5_c2
		or__x_16_c2 = or__x_6_c2
		goto b3
	b2:
		;
		v13_c2 = c_7_c2
		c_14_c2 = c_7_c2
		cmap_15_c2 = cmap_8_c2
		or__x_16_c2 = or__x_9_c2
		goto b3
	b3:
		;
		return v13_c2, nil
	}), s_21})
	if callErr != nil {
		return nil, callErr
	}
	v42, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "apply").Deref(), []vm.Value{rt.LookupVar("clojure.core", "str").Deref(), arg__14435_41})
	if callErr != nil {
		return nil, callErr
	}
	return v42, nil
}
func re_quote_replacement(replacement_0 vm.Value) vm.Value {
	return replacement_0
}
func last_index_of__a0(s_0 vm.Value, value_1 vm.Value) (vm.Value, error) {
	var v3 vm.Value
	var callErr error
	_ = v3
	v3, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "last-index-of").Deref(), []vm.Value{s_0, value_1})
	if callErr != nil {
		return nil, callErr
	}
	return v3, nil
}
func last_index_of__a1(s_0 vm.Value, value_1 vm.Value, from_index_2 vm.Value) (vm.Value, error) {
	var v4 vm.Value
	var callErr error
	_ = v4
	v4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "last-index-of").Deref(), []vm.Value{s_0, value_1, from_index_2})
	if callErr != nil {
		return nil, callErr
	}
	return v4, nil
}
func index_of__a0(s_0 vm.Value, value_1 vm.Value) (vm.Value, error) {
	var v3 vm.Value
	var callErr error
	_ = v3
	v3, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "index-of").Deref(), []vm.Value{s_0, value_1})
	if callErr != nil {
		return nil, callErr
	}
	return v3, nil
}
func index_of__a1(s_0 vm.Value, value_1 vm.Value, from_index_2 vm.Value) (vm.Value, error) {
	var v4 vm.Value
	var callErr error
	_ = v4
	v4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "index-of").Deref(), []vm.Value{s_0, value_1, from_index_2})
	if callErr != nil {
		return nil, callErr
	}
	return v4, nil
}
func join__a0(coll_0 vm.Value) (vm.Value, error) {
	var v4 vm.Value
	var callErr error
	_ = v4
	v4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "apply").Deref(), []vm.Value{rt.LookupVar("clojure.core", "str").Deref(), coll_0})
	if callErr != nil {
		return nil, callErr
	}
	return v4, nil
}
func join__a1(sep_0 vm.Value, coll_1 vm.Value) (vm.Value, error) {
	var arg__14472_4 vm.Value
	var arg__14480_8 vm.Value
	var v9 vm.Value
	var callErr error
	_, _, _ = arg__14472_4, arg__14480_8, v9
	arg__14472_4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "interpose").Deref(), []vm.Value{sep_0, coll_1})
	if callErr != nil {
		return nil, callErr
	}
	arg__14480_8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "interpose").Deref(), []vm.Value{sep_0, coll_1})
	if callErr != nil {
		return nil, callErr
	}
	v9, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "apply").Deref(), []vm.Value{rt.LookupVar("clojure.core", "str").Deref(), arg__14480_8})
	if callErr != nil {
		return nil, callErr
	}
	return v9, nil
}
func blank_QMARK_(s_0 vm.Value) (vm.Value, error) {
	var v4 vm.Value
	var s_1 vm.Value
	var s_2 vm.Value
	var arg__14487_11 vm.Value
	var arg__14492_14 vm.Value
	var v15 vm.Value
	var v43 vm.Value
	var s_44 vm.Value
	var s_8 vm.Value
	var v20 vm.Value
	var s_9 vm.Value
	var v40 vm.Value
	var s_41 vm.Value
	var s_22 vm.Value
	var arg__14500_28 vm.Value
	var arg__14506_32 vm.Value
	var v33 vm.Value
	var s_23 vm.Value
	var v37 vm.Value
	var s_38 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = v4, s_1, s_2, arg__14487_11, arg__14492_14, v15, v43, s_44, s_8, v20, s_9, v40, s_41, s_22, arg__14500_28, arg__14506_32, v33, s_23, v37, s_38
	v4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nil?").Deref(), []vm.Value{s_0})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v4) {
		s_1 = s_0
		goto b1
	} else {
		s_2 = s_0
		goto b2
	}
b1:
	;
	v43 = vm.Boolean(true)
	s_44 = s_1
	goto b3
b2:
	;
	arg__14487_11, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "string?").Deref(), []vm.Value{s_2})
	if callErr != nil {
		return nil, callErr
	}
	arg__14492_14, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "string?").Deref(), []vm.Value{s_2})
	if callErr != nil {
		return nil, callErr
	}
	v15, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "not").Deref(), []vm.Value{arg__14492_14})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v15) {
		s_8 = s_2
		goto b4
	} else {
		s_9 = s_2
		goto b5
	}
b3:
	;
	return v43, nil
b4:
	;
	v20, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "throw").Deref(), []vm.Value{vm.String("blank? expected String")})
	if callErr != nil {
		return nil, callErr
	}
	v40 = v20
	s_41 = s_8
	goto b6
b5:
	;
	if vm.IsTruthy(vm.Keyword("else")) {
		s_22 = s_9
		goto b7
	} else {
		s_23 = s_9
		goto b8
	}
b6:
	;
	v43 = v40
	s_44 = s_41
	goto b3
b7:
	;
	arg__14500_28, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{s_22})
	if callErr != nil {
		return nil, callErr
	}
	arg__14506_32, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{s_22})
	if callErr != nil {
		return nil, callErr
	}
	v33, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "every?").Deref(), []vm.Value{rt.LookupVar("clojure.string", "whitespace-char?").Deref(), arg__14506_32})
	if callErr != nil {
		return nil, callErr
	}
	v37 = v33
	s_38 = s_22
	goto b9
b8:
	;
	v37 = vm.NIL
	s_38 = s_23
	goto b9
b9:
	;
	v40 = v37
	s_41 = s_38
	goto b6
}
func __gogen_wrap(fn func(args []vm.Value) (vm.Value, error)) vm.Value {
	v, _ := vm.NativeFnType.Wrap(fn)
	return v
}
func init() {
	rt.RegisterGoOverrides("string", map[string]vm.Value{"lower-case": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("lower-case: wrong number of arguments %d (expected 1)", len(args))
		}
		return lower_case(args[0])
	}), "upper-case": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("upper-case: wrong number of arguments %d (expected 1)", len(args))
		}
		return upper_case(args[0])
	}), "replace": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 3 {
			return nil, fmt.Errorf("replace: wrong number of arguments %d (expected 3)", len(args))
		}
		return replace(args[0], args[1], args[2])
	}), "ends-with?": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 2 {
			return nil, fmt.Errorf("ends-with?: wrong number of arguments %d (expected 2)", len(args))
		}
		return ends_with_QMARK_(args[0], args[1])
	}), "capitalize": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("capitalize: wrong number of arguments %d (expected 1)", len(args))
		}
		return capitalize(args[0])
	}), "starts-with?": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 2 {
			return nil, fmt.Errorf("starts-with?: wrong number of arguments %d (expected 2)", len(args))
		}
		return starts_with_QMARK_(args[0], args[1])
	}), "reverse": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("reverse: wrong number of arguments %d (expected 1)", len(args))
		}
		return reverse(args[0])
	}), "escape": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 2 {
			return nil, fmt.Errorf("escape: wrong number of arguments %d (expected 2)", len(args))
		}
		return escape(args[0], args[1])
	}), "re-quote-replacement": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("re-quote-replacement: wrong number of arguments %d (expected 1)", len(args))
		}
		return re_quote_replacement(args[0]), nil
	}), "blank?": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("blank?: wrong number of arguments %d (expected 1)", len(args))
		}
		return blank_QMARK_(args[0])
	}),
	})
}
