//go:build gogen_ir

// Code generated by lgbgen --target=go. DO NOT EDIT.
// gogen.nsHash:       9121e2ab4ab3ba6458a33074fad32b2b65b6c942f7d93d3f98e0dad7d8d357c6
// gogen.pipelineHash: f81a0be759146aabc0b9420eced6c006305bf04f7df82e999fb75a5c8206ea44

package set

import (
	"fmt"

	rt "github.com/nooga/let-go/pkg/rt"
	vm "github.com/nooga/let-go/pkg/vm"
)

func difference__a0(s1_0 vm.Value) vm.Value {
	return s1_0
}
func difference__a1(s1_0 vm.Value, s2_1 vm.Value) (vm.Value, error) {
	var arg__14510_7 vm.Value
	var arg__14514_9 vm.Value
	var v10 bool
	var s1_2 vm.Value
	var s2_3 vm.Value
	var v19 vm.Value
	var s1_4 vm.Value
	var s2_5 vm.Value
	var v24 vm.Value
	var v26 vm.Value
	var s1_27 vm.Value
	var s2_28 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _ = arg__14510_7, arg__14514_9, v10, s1_2, s2_3, v19, s1_4, s2_5, v24, v26, s1_27, s2_28
	arg__14510_7, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "count").Deref(), []vm.Value{s1_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__14514_9, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "count").Deref(), []vm.Value{s2_1})
	if callErr != nil {
		return nil, callErr
	}
	v10 = rt.LtValue(arg__14510_7, arg__14514_9)
	if v10 {
		s1_2 = s1_0
		s2_3 = s2_1
		goto b1
	} else {
		s1_4 = s1_0
		s2_5 = s2_1
		goto b2
	}
b1:
	;
	v19, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reduce").Deref(), []vm.Value{rt.BoxNativeFn(func(result_0_c1 vm.Value, item_1_c1 vm.Value) (vm.Value, error) {
		var v10_c1 vm.Value
		var result_3_c1 vm.Value
		var item_4_c1 vm.Value
		var s2_5_c1 vm.Value
		var v13_c1 vm.Value
		var result_6_c1 vm.Value
		var item_7_c1 vm.Value
		var s2_8_c1 vm.Value
		var v16_c1 vm.Value
		var result_17_c1 vm.Value
		var item_18_c1 vm.Value
		var s2_19_c1 vm.Value
		var callErr error
		_, _, _, _, _, _, _, _, _, _, _, _ = v10_c1, result_3_c1, item_4_c1, s2_5_c1, v13_c1, result_6_c1, item_7_c1, s2_8_c1, v16_c1, result_17_c1, item_18_c1, s2_19_c1
		v10_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "contains?").Deref(), []vm.Value{s2_3, item_1_c1})
		if callErr != nil {
			return nil, callErr
		}
		if vm.IsTruthy(v10_c1) {
			result_3_c1 = result_0_c1
			item_4_c1 = item_1_c1
			s2_5_c1 = s2_3
			goto b1
		} else {
			result_6_c1 = result_0_c1
			item_7_c1 = item_1_c1
			s2_8_c1 = s2_3
			goto b2
		}
	b1:
		;
		v13_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "disj").Deref(), []vm.Value{result_3_c1, item_4_c1})
		if callErr != nil {
			return nil, callErr
		}
		v16_c1 = v13_c1
		result_17_c1 = result_3_c1
		item_18_c1 = item_4_c1
		s2_19_c1 = s2_5_c1
		goto b3
	b2:
		;
		v16_c1 = result_6_c1
		result_17_c1 = result_6_c1
		item_18_c1 = item_7_c1
		s2_19_c1 = s2_8_c1
		goto b3
	b3:
		;
		return v16_c1, nil
	}), s1_2, s1_2})
	if callErr != nil {
		return nil, callErr
	}
	v26 = v19
	s1_27 = s1_2
	s2_28 = s2_3
	goto b3
b2:
	;
	v24, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reduce").Deref(), []vm.Value{rt.LookupVar("clojure.core", "disj").Deref(), s1_4, s2_5})
	if callErr != nil {
		return nil, callErr
	}
	v26 = v24
	s1_27 = s1_4
	s2_28 = s2_5
	goto b3
b3:
	;
	return v26, nil
}
func difference__a2(s1_0 vm.Value, s2_1 vm.Value, args ...vm.Value) (vm.Value, error) {
	var arg__14556_5 vm.Value
	var arg__14565_9 vm.Value
	var v10 vm.Value
	var callErr error
	_, _, _ = arg__14556_5, arg__14565_9, v10
	arg__14556_5, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "conj").Deref(), []vm.Value{rt.BoxRestArgs(args), s2_1})
	if callErr != nil {
		return nil, callErr
	}
	arg__14565_9, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "conj").Deref(), []vm.Value{rt.BoxRestArgs(args), s2_1})
	if callErr != nil {
		return nil, callErr
	}
	v10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reduce").Deref(), []vm.Value{rt.LookupVar("clojure.set", "difference").Deref(), s1_0, arg__14565_9})
	if callErr != nil {
		return nil, callErr
	}
	return v10, nil
}
func rename_keys(m_0 vm.Value, kmap_1 vm.Value) (vm.Value, error) {
	var v5 vm.Value
	var callErr error
	_ = v5
	v5, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reduce").Deref(), []vm.Value{rt.BoxNativeFn(func(m_0_c1 vm.Value, vec__14589_1_c1 vm.Value) (vm.Value, error) {
		var old_7_c1 vm.Value
		var new_13_c1 vm.Value
		var v23_c1 vm.Value
		var m_14_c1 vm.Value
		var vec__14589_15_c1 vm.Value
		var old_16_c1 vm.Value
		var new_17_c1 vm.Value
		var arg__14664_26_c1 vm.Value
		var arg__14671_28_c1 vm.Value
		var arg__14678_31_c1 vm.Value
		var arg__14685_33_c1 vm.Value
		var v34_c1 vm.Value
		var m_18_c1 vm.Value
		var vec__14589_19_c1 vm.Value
		var old_20_c1 vm.Value
		var new_21_c1 vm.Value
		var v37_c1 vm.Value
		var m_38_c1 vm.Value
		var vec__14589_39_c1 vm.Value
		var old_40_c1 vm.Value
		var new_41_c1 vm.Value
		var callErr error
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = old_7_c1, new_13_c1, v23_c1, m_14_c1, vec__14589_15_c1, old_16_c1, new_17_c1, arg__14664_26_c1, arg__14671_28_c1, arg__14678_31_c1, arg__14685_33_c1, v34_c1, m_18_c1, vec__14589_19_c1, old_20_c1, new_21_c1, v37_c1, m_38_c1, vec__14589_39_c1, old_40_c1, new_41_c1
		old_7_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{vec__14589_1_c1, vm.Int(0), vm.NIL})
		if callErr != nil {
			return nil, callErr
		}
		new_13_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{vec__14589_1_c1, vm.Int(1), vm.NIL})
		if callErr != nil {
			return nil, callErr
		}
		v23_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "contains?").Deref(), []vm.Value{m_0_c1, old_7_c1})
		if callErr != nil {
			return nil, callErr
		}
		if vm.IsTruthy(v23_c1) {
			m_14_c1 = m_0_c1
			vec__14589_15_c1 = vec__14589_1_c1
			old_16_c1 = old_7_c1
			new_17_c1 = new_13_c1
			goto b1
		} else {
			m_18_c1 = m_0_c1
			vec__14589_19_c1 = vec__14589_1_c1
			old_20_c1 = old_7_c1
			new_21_c1 = new_13_c1
			goto b2
		}
	b1:
		;
		arg__14664_26_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "dissoc").Deref(), []vm.Value{m_14_c1, old_16_c1})
		if callErr != nil {
			return nil, callErr
		}
		arg__14671_28_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{m_14_c1, old_16_c1})
		if callErr != nil {
			return nil, callErr
		}
		arg__14678_31_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "dissoc").Deref(), []vm.Value{m_14_c1, old_16_c1})
		if callErr != nil {
			return nil, callErr
		}
		arg__14685_33_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "get").Deref(), []vm.Value{m_14_c1, old_16_c1})
		if callErr != nil {
			return nil, callErr
		}
		v34_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "assoc").Deref(), []vm.Value{arg__14678_31_c1, new_17_c1, arg__14685_33_c1})
		if callErr != nil {
			return nil, callErr
		}
		v37_c1 = v34_c1
		m_38_c1 = m_14_c1
		vec__14589_39_c1 = vec__14589_15_c1
		old_40_c1 = old_16_c1
		new_41_c1 = new_17_c1
		goto b3
	b2:
		;
		v37_c1 = m_18_c1
		m_38_c1 = m_18_c1
		vec__14589_39_c1 = vec__14589_19_c1
		old_40_c1 = old_20_c1
		new_41_c1 = new_21_c1
		goto b3
	b3:
		;
		return v37_c1, nil
	}), m_0, kmap_1})
	if callErr != nil {
		return nil, callErr
	}
	return v5, nil
}
func intersection__a0(s1_0 vm.Value) vm.Value {
	return s1_0
}
func intersection__a1(s1_0 vm.Value, s2_1 vm.Value) (vm.Value, error) {
	var arg__14692_7 vm.Value
	var arg__14696_9 vm.Value
	var v10 bool
	var s1_2 vm.Value
	var s2_3 vm.Value
	var s1_4 vm.Value
	var s2_5 vm.Value
	var arg__14712_17 vm.Value
	var arg__14729_23 vm.Value
	var v24 vm.Value
	var v26 vm.Value
	var s1_27 vm.Value
	var s2_28 vm.Value
	var callErr error
	var a0 vm.Value
	var a1 vm.Value
	_, _, _, _, _, _, _, _, _, _, _, _, _ = arg__14692_7, arg__14696_9, v10, s1_2, s2_3, s1_4, s2_5, arg__14712_17, arg__14729_23, v24, v26, s1_27, s2_28
	a0 = s1_0
	a1 = s2_1
func_entry:
	;
	arg__14692_7, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "count").Deref(), []vm.Value{a1})
	if callErr != nil {
		return nil, callErr
	}
	arg__14696_9, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "count").Deref(), []vm.Value{a0})
	if callErr != nil {
		return nil, callErr
	}
	v10 = rt.LtValue(arg__14692_7, arg__14696_9)
	if v10 {
		s1_2 = a0
		s2_3 = a1
		goto b1
	} else {
		s1_4 = a0
		s2_5 = a1
		goto b2
	}
b1:
	;
	a0 = s2_3
	a1 = s1_2
	goto func_entry
b2:
	;
	arg__14712_17, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{s1_4})
	if callErr != nil {
		return nil, callErr
	}
	arg__14729_23, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{s1_4})
	if callErr != nil {
		return nil, callErr
	}
	v24, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reduce").Deref(), []vm.Value{rt.BoxNativeFn(func(result_0_c1 vm.Value, item_1_c1 vm.Value) (vm.Value, error) {
		var v10_c1 vm.Value
		var result_3_c1 vm.Value
		var item_4_c1 vm.Value
		var s2_5_c1 vm.Value
		var result_6_c1 vm.Value
		var item_7_c1 vm.Value
		var s2_8_c1 vm.Value
		var v14_c1 vm.Value
		var v16_c1 vm.Value
		var result_17_c1 vm.Value
		var item_18_c1 vm.Value
		var s2_19_c1 vm.Value
		var callErr error
		_, _, _, _, _, _, _, _, _, _, _, _ = v10_c1, result_3_c1, item_4_c1, s2_5_c1, result_6_c1, item_7_c1, s2_8_c1, v14_c1, v16_c1, result_17_c1, item_18_c1, s2_19_c1
		v10_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "contains?").Deref(), []vm.Value{s2_5, item_1_c1})
		if callErr != nil {
			return nil, callErr
		}
		if vm.IsTruthy(v10_c1) {
			result_3_c1 = result_0_c1
			item_4_c1 = item_1_c1
			s2_5_c1 = s2_5
			goto b1
		} else {
			result_6_c1 = result_0_c1
			item_7_c1 = item_1_c1
			s2_8_c1 = s2_5
			goto b2
		}
	b1:
		;
		v16_c1 = result_3_c1
		result_17_c1 = result_3_c1
		item_18_c1 = item_4_c1
		s2_19_c1 = s2_5_c1
		goto b3
	b2:
		;
		v14_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "disj").Deref(), []vm.Value{result_6_c1, item_7_c1})
		if callErr != nil {
			return nil, callErr
		}
		v16_c1 = v14_c1
		result_17_c1 = result_6_c1
		item_18_c1 = item_7_c1
		s2_19_c1 = s2_8_c1
		goto b3
	b3:
		;
		return v16_c1, nil
	}), s1_4, arg__14729_23})
	if callErr != nil {
		return nil, callErr
	}
	v26 = v24
	s1_27 = s1_4
	s2_28 = s2_5
	goto b3
b3:
	;
	return v26, nil
}
func select_(pred_0 vm.Value, s_1 vm.Value) (vm.Value, error) {
	var v9 vm.Value
	var callErr error
	_ = v9
	v9, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reduce").Deref(), []vm.Value{rt.BoxNativeFn(func(result_0_c1 vm.Value, item_1_c1 vm.Value) (vm.Value, error) {
		var v9_c1 vm.Value
		var result_3_c1 vm.Value
		var item_4_c1 vm.Value
		var pred_5_c1 vm.Value
		var result_6_c1 vm.Value
		var item_7_c1 vm.Value
		var pred_8_c1 vm.Value
		var v13_c1 vm.Value
		var v15_c1 vm.Value
		var result_16_c1 vm.Value
		var item_17_c1 vm.Value
		var pred_18_c1 vm.Value
		var callErr error
		_, _, _, _, _, _, _, _, _, _, _, _ = v9_c1, result_3_c1, item_4_c1, pred_5_c1, result_6_c1, item_7_c1, pred_8_c1, v13_c1, v15_c1, result_16_c1, item_17_c1, pred_18_c1
		v9_c1, callErr = rt.InvokeValue(pred_0, []vm.Value{item_1_c1})
		if callErr != nil {
			return nil, callErr
		}
		if vm.IsTruthy(v9_c1) {
			result_3_c1 = result_0_c1
			item_4_c1 = item_1_c1
			pred_5_c1 = pred_0
			goto b1
		} else {
			result_6_c1 = result_0_c1
			item_7_c1 = item_1_c1
			pred_8_c1 = pred_0
			goto b2
		}
	b1:
		;
		v15_c1 = result_3_c1
		result_16_c1 = result_3_c1
		item_17_c1 = item_4_c1
		pred_18_c1 = pred_5_c1
		goto b3
	b2:
		;
		v13_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "disj").Deref(), []vm.Value{result_6_c1, item_7_c1})
		if callErr != nil {
			return nil, callErr
		}
		v15_c1 = v13_c1
		result_16_c1 = result_6_c1
		item_17_c1 = item_7_c1
		pred_18_c1 = pred_8_c1
		goto b3
	b3:
		;
		return v15_c1, nil
	}), s_1, s_1})
	if callErr != nil {
		return nil, callErr
	}
	return v9, nil
}
func union__a0() (vm.Value, error) {
	var v1 vm.Value
	var callErr error
	_ = v1
	v1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "hash-set").Deref(), []vm.Value{})
	if callErr != nil {
		return nil, callErr
	}
	return v1, nil
}
func union__a1(s1_0 vm.Value) vm.Value {
	return s1_0
}
func union__a2(s1_0 vm.Value, s2_1 vm.Value) (vm.Value, error) {
	var v5 vm.Value
	var callErr error
	_ = v5
	v5, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reduce").Deref(), []vm.Value{rt.LookupVar("clojure.core", "conj").Deref(), s1_0, s2_1})
	if callErr != nil {
		return nil, callErr
	}
	return v5, nil
}
func union__a3(s1_0 vm.Value, s2_1 vm.Value, args ...vm.Value) (vm.Value, error) {
	var arg__14767_5 vm.Value
	var arg__14776_9 vm.Value
	var v10 vm.Value
	var callErr error
	_, _, _ = arg__14767_5, arg__14776_9, v10
	arg__14767_5, callErr = rt.InvokeValue(rt.LookupVar("clojure.set", "union").Deref(), []vm.Value{s1_0, s2_1})
	if callErr != nil {
		return nil, callErr
	}
	arg__14776_9, callErr = rt.InvokeValue(rt.LookupVar("clojure.set", "union").Deref(), []vm.Value{s1_0, s2_1})
	if callErr != nil {
		return nil, callErr
	}
	v10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reduce").Deref(), []vm.Value{rt.LookupVar("clojure.set", "union").Deref(), arg__14776_9, rt.BoxRestArgs(args)})
	if callErr != nil {
		return nil, callErr
	}
	return v10, nil
}
func map_invert(m_0 vm.Value) (vm.Value, error) {
	var v6 vm.Value
	var callErr error
	_ = v6
	v6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reduce").Deref(), []vm.Value{rt.BoxNativeFn(func(acc_0_c1 vm.Value, vec__14778_1_c1 vm.Value) (vm.Value, error) {
		var k_7_c1 vm.Value
		var v_13_c1 vm.Value
		var v15_c1 vm.Value
		var callErr error
		_, _, _ = k_7_c1, v_13_c1, v15_c1
		k_7_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{vec__14778_1_c1, vm.Int(0), vm.NIL})
		if callErr != nil {
			return nil, callErr
		}
		v_13_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{vec__14778_1_c1, vm.Int(1), vm.NIL})
		if callErr != nil {
			return nil, callErr
		}
		v15_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "assoc").Deref(), []vm.Value{acc_0_c1, v_13_c1, k_7_c1})
		if callErr != nil {
			return nil, callErr
		}
		return v15_c1, nil
	}), vm.EmptyPersistentMap, m_0})
	if callErr != nil {
		return nil, callErr
	}
	return v6, nil
}
func superset_QMARK_(s1_0 vm.Value, s2_1 vm.Value) (vm.Value, error) {
	var v3 vm.Value
	var callErr error
	_ = v3
	v3, callErr = rt.InvokeValue(rt.LookupVar("clojure.set", "subset?").Deref(), []vm.Value{s2_1, s1_0})
	if callErr != nil {
		return nil, callErr
	}
	return v3, nil
}
func __gogen_wrap(fn func(args []vm.Value) (vm.Value, error)) vm.Value {
	v, _ := vm.NativeFnType.Wrap(fn)
	return v
}
func init() {
	rt.RegisterGoOverrides("set", map[string]vm.Value{"rename-keys": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 2 {
			return nil, fmt.Errorf("rename-keys: wrong number of arguments %d (expected 2)", len(args))
		}
		return rename_keys(args[0], args[1])
	}), "select": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 2 {
			return nil, fmt.Errorf("select: wrong number of arguments %d (expected 2)", len(args))
		}
		return select_(args[0], args[1])
	}), "map-invert": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("map-invert: wrong number of arguments %d (expected 1)", len(args))
		}
		return map_invert(args[0])
	}), "superset?": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 2 {
			return nil, fmt.Errorf("superset?: wrong number of arguments %d (expected 2)", len(args))
		}
		return superset_QMARK_(args[0], args[1])
	}),
	})
}
