//go:build gogen_ir

// Code generated by lgbgen --target=go. DO NOT EDIT.
// gogen.nsHash:       f1dd3de572eaf37199113cb3cf121e5997ce75b911d546bd9f6dff502735092d
// gogen.pipelineHash: f81a0be759146aabc0b9420eced6c006305bf04f7df82e999fb75a5c8206ea44

package licm

import (
	"fmt"

	rt "github.com/nooga/let-go/pkg/rt"
	vm "github.com/nooga/let-go/pkg/vm"
)

func hoist_one_BANG_(f_0 vm.Value, nid_1 vm.Value, pre_header_2 vm.Value) (vm.Value, error) {
	var op_5 vm.Value
	var refs_7 vm.Value
	var aux_9 vm.Value
	var clone_11 vm.Value
	var from_block_13 vm.Value
	var v15 vm.Value
	var v17 vm.Value
	var callErr error
	_, _, _, _, _, _, _ = op_5, refs_7, aux_9, clone_11, from_block_13, v15, v17
	op_5, callErr = rt.InvokeValue(rt.LookupVar("ir", "op").Deref(), []vm.Value{nid_1, f_0})
	if callErr != nil {
		return nil, callErr
	}
	refs_7, callErr = rt.InvokeValue(rt.LookupVar("ir", "refs").Deref(), []vm.Value{nid_1, f_0})
	if callErr != nil {
		return nil, callErr
	}
	aux_9, callErr = rt.InvokeValue(rt.LookupVar("ir", "aux").Deref(), []vm.Value{nid_1, f_0})
	if callErr != nil {
		return nil, callErr
	}
	clone_11, callErr = rt.InvokeValue(rt.LookupVar("ir", "add-inst").Deref(), []vm.Value{f_0, pre_header_2, op_5, refs_7, aux_9})
	if callErr != nil {
		return nil, callErr
	}
	from_block_13, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-of").Deref(), []vm.Value{nid_1, f_0})
	if callErr != nil {
		return nil, callErr
	}
	v15, callErr = rt.InvokeValue(rt.LookupVar("ir", "replace-all-uses!").Deref(), []vm.Value{f_0, nid_1, clone_11})
	if callErr != nil {
		return nil, callErr
	}
	v17, callErr = rt.InvokeValue(rt.LookupVar("ir", "remove-inst!").Deref(), []vm.Value{f_0, from_block_13, nid_1})
	if callErr != nil {
		return nil, callErr
	}
	return clone_11, nil
}
func back_edges(f_0 vm.Value) (vm.Value, error) {
	var for__a28152_5 vm.Value
	var __15 vm.Value
	var for__iter28151_17 vm.Value
	var arg__30697_19 vm.Value
	var arg__30702_21 vm.Value
	var arg__30703_22 vm.Value
	var for__a28152_27 vm.Value
	var __37 vm.Value
	var for__iter28151_39 vm.Value
	var arg__33249_41 vm.Value
	var arg__33254_43 vm.Value
	var arg__33255_44 vm.Value
	var v45 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _ = for__a28152_5, __15, for__iter28151_17, arg__30697_19, arg__30702_21, arg__30703_22, for__a28152_27, __37, for__iter28151_39, arg__33249_41, arg__33254_43, arg__33255_44, v45
	for__a28152_5, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "atom").Deref(), []vm.Value{vm.NIL})
	if callErr != nil {
		return nil, callErr
	}
	__15, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reset!").Deref(), []vm.Value{for__a28152_5, rt.BoxNativeFn(func(for__s_0_c1 vm.Value) (vm.Value, error) {
		var v14_c1 vm.Value
		var callErr error
		_ = v14_c1
		v14_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "lazy-seq*").Deref(), []vm.Value{rt.BoxNativeFn(func() (vm.Value, error) {
			var tem__G__0_4_c2 vm.Value
			var f_5_c2 vm.Value
			var for__a28152_6_c2 vm.Value
			var for__s_7_c2 vm.Value
			var tem__G__0_8_c2 vm.Value
			var header_15_c2 vm.Value
			var for__a28150_19_c2 vm.Value
			var __33_c2 vm.Value
			var for__iter28149_35_c2 vm.Value
			var arg__30354_37_c2 vm.Value
			var arg__30361_39_c2 vm.Value
			var arg__30362_40_c2 vm.Value
			var arg__30366_42_c2 vm.Value
			var head__30370_44_c2 vm.Value
			var arg__30374_46_c2 vm.Value
			var arg__30375_47_c2 vm.Value
			var for__a28150_52_c2 vm.Value
			var __66_c2 vm.Value
			var for__iter28149_68_c2 vm.Value
			var arg__30667_70_c2 vm.Value
			var arg__30674_72_c2 vm.Value
			var arg__30675_73_c2 vm.Value
			var arg__30679_75_c2 vm.Value
			var head__30683_77_c2 vm.Value
			var arg__30687_79_c2 vm.Value
			var arg__30688_80_c2 vm.Value
			var v81_c2 vm.Value
			var f_9_c2 vm.Value
			var for__a28152_10_c2 vm.Value
			var for__s_11_c2 vm.Value
			var tem__G__0_12_c2 vm.Value
			var v85_c2 vm.Value
			var f_86_c2 vm.Value
			var for__a28152_87_c2 vm.Value
			var for__s_88_c2 vm.Value
			var tem__G__0_89_c2 vm.Value
			var callErr error
			_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = tem__G__0_4_c2, f_5_c2, for__a28152_6_c2, for__s_7_c2, tem__G__0_8_c2, header_15_c2, for__a28150_19_c2, __33_c2, for__iter28149_35_c2, arg__30354_37_c2, arg__30361_39_c2, arg__30362_40_c2, arg__30366_42_c2, head__30370_44_c2, arg__30374_46_c2, arg__30375_47_c2, for__a28150_52_c2, __66_c2, for__iter28149_68_c2, arg__30667_70_c2, arg__30674_72_c2, arg__30675_73_c2, arg__30679_75_c2, head__30683_77_c2, arg__30687_79_c2, arg__30688_80_c2, v81_c2, f_9_c2, for__a28152_10_c2, for__s_11_c2, tem__G__0_12_c2, v85_c2, f_86_c2, for__a28152_87_c2, for__s_88_c2, tem__G__0_89_c2
			tem__G__0_4_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{for__s_0_c1})
			if callErr != nil {
				return nil, callErr
			}
			if vm.IsTruthy(tem__G__0_4_c2) {
				f_5_c2 = f_0
				for__a28152_6_c2 = for__a28152_5
				for__s_7_c2 = for__s_0_c1
				tem__G__0_8_c2 = tem__G__0_4_c2
				goto b1
			} else {
				f_9_c2 = f_0
				for__a28152_10_c2 = for__a28152_5
				for__s_11_c2 = for__s_0_c1
				tem__G__0_12_c2 = tem__G__0_4_c2
				goto b2
			}
		b1:
			;
			header_15_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "first").Deref(), []vm.Value{tem__G__0_8_c2})
			if callErr != nil {
				return nil, callErr
			}
			for__a28150_19_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "atom").Deref(), []vm.Value{vm.NIL})
			if callErr != nil {
				return nil, callErr
			}
			__33_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reset!").Deref(), []vm.Value{for__a28150_19_c2, rt.BoxNativeFn(func(for__s_0_c3 vm.Value) (vm.Value, error) {
				var v18_c3 vm.Value
				var callErr error
				_ = v18_c3
				v18_c3, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "lazy-seq*").Deref(), []vm.Value{rt.BoxNativeFn(func() (vm.Value, error) {
					var tem__G__0_5_c4 vm.Value
					var f_6_c4 vm.Value
					var for__a28150_7_c4 vm.Value
					var for__s_8_c4 vm.Value
					var header_9_c4 vm.Value
					var tem__G__0_10_c4 vm.Value
					var pred_18_c4 vm.Value
					var v34_c4 vm.Value
					var f_11_c4 vm.Value
					var for__a28150_12_c4 vm.Value
					var for__s_13_c4 vm.Value
					var header_14_c4 vm.Value
					var tem__G__0_15_c4 vm.Value
					var v109_c4 vm.Value
					var f_110_c4 vm.Value
					var for__a28150_111_c4 vm.Value
					var for__s_112_c4 vm.Value
					var header_113_c4 vm.Value
					var tem__G__0_114_c4 vm.Value
					var f_19_c4 vm.Value
					var for__a28150_20_c4 vm.Value
					var for__s_21_c4 vm.Value
					var header_22_c4 vm.Value
					var tem__G__0_23_c4 vm.Value
					var for__xs_24_c4 vm.Value
					var pred_25_c4 vm.Value
					var arg__30293_37_c4 vm.Value
					var arg__30298_40_c4 vm.Value
					var v41_c4 vm.Value
					var f_26_c4 vm.Value
					var for__a28150_27_c4 vm.Value
					var for__s_28_c4 vm.Value
					var header_29_c4 vm.Value
					var tem__G__0_30_c4 vm.Value
					var for__xs_31_c4 vm.Value
					var pred_32_c4 vm.Value
					var arg__30299_45_c4 vm.Value
					var f_46_c4 vm.Value
					var for__a28150_47_c4 vm.Value
					var for__s_48_c4 vm.Value
					var header_49_c4 vm.Value
					var tem__G__0_50_c4 vm.Value
					var for__xs_51_c4 vm.Value
					var pred_52_c4 vm.Value
					var arg__30303_54_c4 vm.Value
					var head__30307_56_c4 vm.Value
					var arg__30311_58_c4 vm.Value
					var arg__30312_59_c4 vm.Value
					var v78_c4 vm.Value
					var f_61_c4 vm.Value
					var for__a28150_62_c4 vm.Value
					var for__s_63_c4 vm.Value
					var header_64_c4 vm.Value
					var tem__G__0_65_c4 vm.Value
					var for__xs_66_c4 vm.Value
					var pred_67_c4 vm.Value
					var head__30313_68_c4 vm.Value
					var arg__30324_81_c4 vm.Value
					var arg__30329_84_c4 vm.Value
					var v85_c4 vm.Value
					var f_69_c4 vm.Value
					var for__a28150_70_c4 vm.Value
					var for__s_71_c4 vm.Value
					var header_72_c4 vm.Value
					var tem__G__0_73_c4 vm.Value
					var for__xs_74_c4 vm.Value
					var pred_75_c4 vm.Value
					var head__30313_76_c4 vm.Value
					var arg__30330_89_c4 vm.Value
					var f_90_c4 vm.Value
					var for__a28150_91_c4 vm.Value
					var for__s_92_c4 vm.Value
					var header_93_c4 vm.Value
					var tem__G__0_94_c4 vm.Value
					var for__xs_95_c4 vm.Value
					var pred_96_c4 vm.Value
					var head__30313_97_c4 vm.Value
					var arg__30334_99_c4 vm.Value
					var head__30338_101_c4 vm.Value
					var arg__30342_103_c4 vm.Value
					var arg__30343_104_c4 vm.Value
					var v105_c4 vm.Value
					var callErr error
					_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = tem__G__0_5_c4, f_6_c4, for__a28150_7_c4, for__s_8_c4, header_9_c4, tem__G__0_10_c4, pred_18_c4, v34_c4, f_11_c4, for__a28150_12_c4, for__s_13_c4, header_14_c4, tem__G__0_15_c4, v109_c4, f_110_c4, for__a28150_111_c4, for__s_112_c4, header_113_c4, tem__G__0_114_c4, f_19_c4, for__a28150_20_c4, for__s_21_c4, header_22_c4, tem__G__0_23_c4, for__xs_24_c4, pred_25_c4, arg__30293_37_c4, arg__30298_40_c4, v41_c4, f_26_c4, for__a28150_27_c4, for__s_28_c4, header_29_c4, tem__G__0_30_c4, for__xs_31_c4, pred_32_c4, arg__30299_45_c4, f_46_c4, for__a28150_47_c4, for__s_48_c4, header_49_c4, tem__G__0_50_c4, for__xs_51_c4, pred_52_c4, arg__30303_54_c4, head__30307_56_c4, arg__30311_58_c4, arg__30312_59_c4, v78_c4, f_61_c4, for__a28150_62_c4, for__s_63_c4, header_64_c4, tem__G__0_65_c4, for__xs_66_c4, pred_67_c4, head__30313_68_c4, arg__30324_81_c4, arg__30329_84_c4, v85_c4, f_69_c4, for__a28150_70_c4, for__s_71_c4, header_72_c4, tem__G__0_73_c4, for__xs_74_c4, pred_75_c4, head__30313_76_c4, arg__30330_89_c4, f_90_c4, for__a28150_91_c4, for__s_92_c4, header_93_c4, tem__G__0_94_c4, for__xs_95_c4, pred_96_c4, head__30313_97_c4, arg__30334_99_c4, head__30338_101_c4, arg__30342_103_c4, arg__30343_104_c4, v105_c4
					tem__G__0_5_c4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{for__s_7_c2})
					if callErr != nil {
						return nil, callErr
					}
					if vm.IsTruthy(tem__G__0_5_c4) {
						f_6_c4 = f_5_c2
						for__a28150_7_c4 = for__a28150_19_c2
						for__s_8_c4 = for__s_7_c2
						header_9_c4 = header_15_c2
						tem__G__0_10_c4 = tem__G__0_5_c4
						goto b1
					} else {
						f_11_c4 = f_5_c2
						for__a28150_12_c4 = for__a28150_19_c2
						for__s_13_c4 = for__s_7_c2
						header_14_c4 = header_15_c2
						tem__G__0_15_c4 = tem__G__0_5_c4
						goto b2
					}
				b1:
					;
					pred_18_c4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "first").Deref(), []vm.Value{tem__G__0_10_c4})
					if callErr != nil {
						return nil, callErr
					}
					v34_c4, callErr = rt.InvokeValue(rt.LookupVar("ir.dominance", "dominates?").Deref(), []vm.Value{f_6_c4, header_9_c4, pred_18_c4})
					if callErr != nil {
						return nil, callErr
					}
					if vm.IsTruthy(v34_c4) {
						f_19_c4 = f_6_c4
						for__a28150_20_c4 = for__a28150_7_c4
						for__s_21_c4 = for__s_8_c4
						header_22_c4 = header_9_c4
						tem__G__0_23_c4 = tem__G__0_10_c4
						for__xs_24_c4 = tem__G__0_10_c4
						pred_25_c4 = pred_18_c4
						goto b4
					} else {
						f_26_c4 = f_6_c4
						for__a28150_27_c4 = for__a28150_7_c4
						for__s_28_c4 = for__s_8_c4
						header_29_c4 = header_9_c4
						tem__G__0_30_c4 = tem__G__0_10_c4
						for__xs_31_c4 = tem__G__0_10_c4
						pred_32_c4 = pred_18_c4
						goto b5
					}
				b2:
					;
					v109_c4 = vm.NIL
					f_110_c4 = f_11_c4
					for__a28150_111_c4 = for__a28150_12_c4
					for__s_112_c4 = for__s_13_c4
					header_113_c4 = header_14_c4
					tem__G__0_114_c4 = tem__G__0_15_c4
					goto b3
				b3:
					;
					return v109_c4, nil
				b4:
					;
					arg__30293_37_c4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_25_c4, header_22_c4})
					if callErr != nil {
						return nil, callErr
					}
					arg__30298_40_c4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_25_c4, header_22_c4})
					if callErr != nil {
						return nil, callErr
					}
					v41_c4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "list").Deref(), []vm.Value{arg__30298_40_c4})
					if callErr != nil {
						return nil, callErr
					}
					arg__30299_45_c4 = v41_c4
					f_46_c4 = f_19_c4
					for__a28150_47_c4 = for__a28150_20_c4
					for__s_48_c4 = for__s_21_c4
					header_49_c4 = header_22_c4
					tem__G__0_50_c4 = tem__G__0_23_c4
					for__xs_51_c4 = for__xs_24_c4
					pred_52_c4 = pred_25_c4
					goto b6
				b5:
					;
					arg__30299_45_c4 = vm.NIL
					f_46_c4 = f_26_c4
					for__a28150_47_c4 = for__a28150_27_c4
					for__s_48_c4 = for__s_28_c4
					header_49_c4 = header_29_c4
					tem__G__0_50_c4 = tem__G__0_30_c4
					for__xs_51_c4 = for__xs_31_c4
					pred_52_c4 = pred_32_c4
					goto b6
				b6:
					;
					arg__30303_54_c4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_51_c4})
					if callErr != nil {
						return nil, callErr
					}
					head__30307_56_c4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28150_47_c4})
					if callErr != nil {
						return nil, callErr
					}
					arg__30311_58_c4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_51_c4})
					if callErr != nil {
						return nil, callErr
					}
					arg__30312_59_c4, callErr = rt.InvokeValue(head__30307_56_c4, []vm.Value{arg__30311_58_c4})
					if callErr != nil {
						return nil, callErr
					}
					v78_c4, callErr = rt.InvokeValue(rt.LookupVar("ir.dominance", "dominates?").Deref(), []vm.Value{f_46_c4, header_49_c4, pred_52_c4})
					if callErr != nil {
						return nil, callErr
					}
					if vm.IsTruthy(v78_c4) {
						f_61_c4 = f_46_c4
						for__a28150_62_c4 = for__a28150_47_c4
						for__s_63_c4 = for__s_48_c4
						header_64_c4 = header_49_c4
						tem__G__0_65_c4 = tem__G__0_50_c4
						for__xs_66_c4 = for__xs_51_c4
						pred_67_c4 = pred_52_c4
						head__30313_68_c4 = rt.LookupVar("clojure.core", "concat-list").Deref()
						goto b7
					} else {
						f_69_c4 = f_46_c4
						for__a28150_70_c4 = for__a28150_47_c4
						for__s_71_c4 = for__s_48_c4
						header_72_c4 = header_49_c4
						tem__G__0_73_c4 = tem__G__0_50_c4
						for__xs_74_c4 = for__xs_51_c4
						pred_75_c4 = pred_52_c4
						head__30313_76_c4 = rt.LookupVar("clojure.core", "concat-list").Deref()
						goto b8
					}
				b7:
					;
					arg__30324_81_c4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_67_c4, header_64_c4})
					if callErr != nil {
						return nil, callErr
					}
					arg__30329_84_c4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_67_c4, header_64_c4})
					if callErr != nil {
						return nil, callErr
					}
					v85_c4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "list").Deref(), []vm.Value{arg__30329_84_c4})
					if callErr != nil {
						return nil, callErr
					}
					arg__30330_89_c4 = v85_c4
					f_90_c4 = f_61_c4
					for__a28150_91_c4 = for__a28150_62_c4
					for__s_92_c4 = for__s_63_c4
					header_93_c4 = header_64_c4
					tem__G__0_94_c4 = tem__G__0_65_c4
					for__xs_95_c4 = for__xs_66_c4
					pred_96_c4 = pred_67_c4
					head__30313_97_c4 = head__30313_68_c4
					goto b9
				b8:
					;
					arg__30330_89_c4 = vm.NIL
					f_90_c4 = f_69_c4
					for__a28150_91_c4 = for__a28150_70_c4
					for__s_92_c4 = for__s_71_c4
					header_93_c4 = header_72_c4
					tem__G__0_94_c4 = tem__G__0_73_c4
					for__xs_95_c4 = for__xs_74_c4
					pred_96_c4 = pred_75_c4
					head__30313_97_c4 = head__30313_76_c4
					goto b9
				b9:
					;
					arg__30334_99_c4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_95_c4})
					if callErr != nil {
						return nil, callErr
					}
					head__30338_101_c4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28150_91_c4})
					if callErr != nil {
						return nil, callErr
					}
					arg__30342_103_c4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_95_c4})
					if callErr != nil {
						return nil, callErr
					}
					arg__30343_104_c4, callErr = rt.InvokeValue(head__30338_101_c4, []vm.Value{arg__30342_103_c4})
					if callErr != nil {
						return nil, callErr
					}
					v105_c4, callErr = rt.InvokeValue(head__30313_97_c4, []vm.Value{arg__30330_89_c4, arg__30343_104_c4})
					if callErr != nil {
						return nil, callErr
					}
					v109_c4 = v105_c4
					f_110_c4 = f_90_c4
					for__a28150_111_c4 = for__a28150_91_c4
					for__s_112_c4 = for__s_92_c4
					header_113_c4 = header_93_c4
					tem__G__0_114_c4 = tem__G__0_94_c4
					goto b3
				})})
				if callErr != nil {
					return nil, callErr
				}
				return v18_c3, nil
			})})
			if callErr != nil {
				return nil, callErr
			}
			for__iter28149_35_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28150_19_c2})
			if callErr != nil {
				return nil, callErr
			}
			arg__30354_37_c2, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-preds").Deref(), []vm.Value{header_15_c2, f_5_c2})
			if callErr != nil {
				return nil, callErr
			}
			arg__30361_39_c2, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-preds").Deref(), []vm.Value{header_15_c2, f_5_c2})
			if callErr != nil {
				return nil, callErr
			}
			arg__30362_40_c2, callErr = rt.InvokeValue(for__iter28149_35_c2, []vm.Value{arg__30361_39_c2})
			if callErr != nil {
				return nil, callErr
			}
			arg__30366_42_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{tem__G__0_8_c2})
			if callErr != nil {
				return nil, callErr
			}
			head__30370_44_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28152_6_c2})
			if callErr != nil {
				return nil, callErr
			}
			arg__30374_46_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{tem__G__0_8_c2})
			if callErr != nil {
				return nil, callErr
			}
			arg__30375_47_c2, callErr = rt.InvokeValue(head__30370_44_c2, []vm.Value{arg__30374_46_c2})
			if callErr != nil {
				return nil, callErr
			}
			for__a28150_52_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "atom").Deref(), []vm.Value{vm.NIL})
			if callErr != nil {
				return nil, callErr
			}
			__66_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reset!").Deref(), []vm.Value{for__a28150_52_c2, rt.BoxNativeFn(func(for__s_0_c5 vm.Value) (vm.Value, error) {
				var v18_c5 vm.Value
				var callErr error
				_ = v18_c5
				v18_c5, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "lazy-seq*").Deref(), []vm.Value{rt.BoxNativeFn(func() (vm.Value, error) {
					var tem__G__0_5_c6 vm.Value
					var f_6_c6 vm.Value
					var for__a28150_7_c6 vm.Value
					var for__s_8_c6 vm.Value
					var header_9_c6 vm.Value
					var tem__G__0_10_c6 vm.Value
					var pred_18_c6 vm.Value
					var v34_c6 vm.Value
					var f_11_c6 vm.Value
					var for__a28150_12_c6 vm.Value
					var for__s_13_c6 vm.Value
					var header_14_c6 vm.Value
					var tem__G__0_15_c6 vm.Value
					var v109_c6 vm.Value
					var f_110_c6 vm.Value
					var for__a28150_111_c6 vm.Value
					var for__s_112_c6 vm.Value
					var header_113_c6 vm.Value
					var tem__G__0_114_c6 vm.Value
					var f_19_c6 vm.Value
					var for__a28150_20_c6 vm.Value
					var for__s_21_c6 vm.Value
					var header_22_c6 vm.Value
					var tem__G__0_23_c6 vm.Value
					var for__xs_24_c6 vm.Value
					var pred_25_c6 vm.Value
					var arg__30606_37_c6 vm.Value
					var arg__30611_40_c6 vm.Value
					var v41_c6 vm.Value
					var f_26_c6 vm.Value
					var for__a28150_27_c6 vm.Value
					var for__s_28_c6 vm.Value
					var header_29_c6 vm.Value
					var tem__G__0_30_c6 vm.Value
					var for__xs_31_c6 vm.Value
					var pred_32_c6 vm.Value
					var arg__30612_45_c6 vm.Value
					var f_46_c6 vm.Value
					var for__a28150_47_c6 vm.Value
					var for__s_48_c6 vm.Value
					var header_49_c6 vm.Value
					var tem__G__0_50_c6 vm.Value
					var for__xs_51_c6 vm.Value
					var pred_52_c6 vm.Value
					var arg__30616_54_c6 vm.Value
					var head__30620_56_c6 vm.Value
					var arg__30624_58_c6 vm.Value
					var arg__30625_59_c6 vm.Value
					var v78_c6 vm.Value
					var f_61_c6 vm.Value
					var for__a28150_62_c6 vm.Value
					var for__s_63_c6 vm.Value
					var header_64_c6 vm.Value
					var tem__G__0_65_c6 vm.Value
					var for__xs_66_c6 vm.Value
					var pred_67_c6 vm.Value
					var head__30626_68_c6 vm.Value
					var arg__30637_81_c6 vm.Value
					var arg__30642_84_c6 vm.Value
					var v85_c6 vm.Value
					var f_69_c6 vm.Value
					var for__a28150_70_c6 vm.Value
					var for__s_71_c6 vm.Value
					var header_72_c6 vm.Value
					var tem__G__0_73_c6 vm.Value
					var for__xs_74_c6 vm.Value
					var pred_75_c6 vm.Value
					var head__30626_76_c6 vm.Value
					var arg__30643_89_c6 vm.Value
					var f_90_c6 vm.Value
					var for__a28150_91_c6 vm.Value
					var for__s_92_c6 vm.Value
					var header_93_c6 vm.Value
					var tem__G__0_94_c6 vm.Value
					var for__xs_95_c6 vm.Value
					var pred_96_c6 vm.Value
					var head__30626_97_c6 vm.Value
					var arg__30647_99_c6 vm.Value
					var head__30651_101_c6 vm.Value
					var arg__30655_103_c6 vm.Value
					var arg__30656_104_c6 vm.Value
					var v105_c6 vm.Value
					var callErr error
					_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = tem__G__0_5_c6, f_6_c6, for__a28150_7_c6, for__s_8_c6, header_9_c6, tem__G__0_10_c6, pred_18_c6, v34_c6, f_11_c6, for__a28150_12_c6, for__s_13_c6, header_14_c6, tem__G__0_15_c6, v109_c6, f_110_c6, for__a28150_111_c6, for__s_112_c6, header_113_c6, tem__G__0_114_c6, f_19_c6, for__a28150_20_c6, for__s_21_c6, header_22_c6, tem__G__0_23_c6, for__xs_24_c6, pred_25_c6, arg__30606_37_c6, arg__30611_40_c6, v41_c6, f_26_c6, for__a28150_27_c6, for__s_28_c6, header_29_c6, tem__G__0_30_c6, for__xs_31_c6, pred_32_c6, arg__30612_45_c6, f_46_c6, for__a28150_47_c6, for__s_48_c6, header_49_c6, tem__G__0_50_c6, for__xs_51_c6, pred_52_c6, arg__30616_54_c6, head__30620_56_c6, arg__30624_58_c6, arg__30625_59_c6, v78_c6, f_61_c6, for__a28150_62_c6, for__s_63_c6, header_64_c6, tem__G__0_65_c6, for__xs_66_c6, pred_67_c6, head__30626_68_c6, arg__30637_81_c6, arg__30642_84_c6, v85_c6, f_69_c6, for__a28150_70_c6, for__s_71_c6, header_72_c6, tem__G__0_73_c6, for__xs_74_c6, pred_75_c6, head__30626_76_c6, arg__30643_89_c6, f_90_c6, for__a28150_91_c6, for__s_92_c6, header_93_c6, tem__G__0_94_c6, for__xs_95_c6, pred_96_c6, head__30626_97_c6, arg__30647_99_c6, head__30651_101_c6, arg__30655_103_c6, arg__30656_104_c6, v105_c6
					tem__G__0_5_c6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{for__s_7_c2})
					if callErr != nil {
						return nil, callErr
					}
					if vm.IsTruthy(tem__G__0_5_c6) {
						f_6_c6 = f_5_c2
						for__a28150_7_c6 = for__a28150_52_c2
						for__s_8_c6 = for__s_7_c2
						header_9_c6 = header_15_c2
						tem__G__0_10_c6 = tem__G__0_5_c6
						goto b1
					} else {
						f_11_c6 = f_5_c2
						for__a28150_12_c6 = for__a28150_52_c2
						for__s_13_c6 = for__s_7_c2
						header_14_c6 = header_15_c2
						tem__G__0_15_c6 = tem__G__0_5_c6
						goto b2
					}
				b1:
					;
					pred_18_c6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "first").Deref(), []vm.Value{tem__G__0_10_c6})
					if callErr != nil {
						return nil, callErr
					}
					v34_c6, callErr = rt.InvokeValue(rt.LookupVar("ir.dominance", "dominates?").Deref(), []vm.Value{f_6_c6, header_9_c6, pred_18_c6})
					if callErr != nil {
						return nil, callErr
					}
					if vm.IsTruthy(v34_c6) {
						f_19_c6 = f_6_c6
						for__a28150_20_c6 = for__a28150_7_c6
						for__s_21_c6 = for__s_8_c6
						header_22_c6 = header_9_c6
						tem__G__0_23_c6 = tem__G__0_10_c6
						for__xs_24_c6 = tem__G__0_10_c6
						pred_25_c6 = pred_18_c6
						goto b4
					} else {
						f_26_c6 = f_6_c6
						for__a28150_27_c6 = for__a28150_7_c6
						for__s_28_c6 = for__s_8_c6
						header_29_c6 = header_9_c6
						tem__G__0_30_c6 = tem__G__0_10_c6
						for__xs_31_c6 = tem__G__0_10_c6
						pred_32_c6 = pred_18_c6
						goto b5
					}
				b2:
					;
					v109_c6 = vm.NIL
					f_110_c6 = f_11_c6
					for__a28150_111_c6 = for__a28150_12_c6
					for__s_112_c6 = for__s_13_c6
					header_113_c6 = header_14_c6
					tem__G__0_114_c6 = tem__G__0_15_c6
					goto b3
				b3:
					;
					return v109_c6, nil
				b4:
					;
					arg__30606_37_c6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_25_c6, header_22_c6})
					if callErr != nil {
						return nil, callErr
					}
					arg__30611_40_c6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_25_c6, header_22_c6})
					if callErr != nil {
						return nil, callErr
					}
					v41_c6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "list").Deref(), []vm.Value{arg__30611_40_c6})
					if callErr != nil {
						return nil, callErr
					}
					arg__30612_45_c6 = v41_c6
					f_46_c6 = f_19_c6
					for__a28150_47_c6 = for__a28150_20_c6
					for__s_48_c6 = for__s_21_c6
					header_49_c6 = header_22_c6
					tem__G__0_50_c6 = tem__G__0_23_c6
					for__xs_51_c6 = for__xs_24_c6
					pred_52_c6 = pred_25_c6
					goto b6
				b5:
					;
					arg__30612_45_c6 = vm.NIL
					f_46_c6 = f_26_c6
					for__a28150_47_c6 = for__a28150_27_c6
					for__s_48_c6 = for__s_28_c6
					header_49_c6 = header_29_c6
					tem__G__0_50_c6 = tem__G__0_30_c6
					for__xs_51_c6 = for__xs_31_c6
					pred_52_c6 = pred_32_c6
					goto b6
				b6:
					;
					arg__30616_54_c6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_51_c6})
					if callErr != nil {
						return nil, callErr
					}
					head__30620_56_c6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28150_47_c6})
					if callErr != nil {
						return nil, callErr
					}
					arg__30624_58_c6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_51_c6})
					if callErr != nil {
						return nil, callErr
					}
					arg__30625_59_c6, callErr = rt.InvokeValue(head__30620_56_c6, []vm.Value{arg__30624_58_c6})
					if callErr != nil {
						return nil, callErr
					}
					v78_c6, callErr = rt.InvokeValue(rt.LookupVar("ir.dominance", "dominates?").Deref(), []vm.Value{f_46_c6, header_49_c6, pred_52_c6})
					if callErr != nil {
						return nil, callErr
					}
					if vm.IsTruthy(v78_c6) {
						f_61_c6 = f_46_c6
						for__a28150_62_c6 = for__a28150_47_c6
						for__s_63_c6 = for__s_48_c6
						header_64_c6 = header_49_c6
						tem__G__0_65_c6 = tem__G__0_50_c6
						for__xs_66_c6 = for__xs_51_c6
						pred_67_c6 = pred_52_c6
						head__30626_68_c6 = rt.LookupVar("clojure.core", "concat-list").Deref()
						goto b7
					} else {
						f_69_c6 = f_46_c6
						for__a28150_70_c6 = for__a28150_47_c6
						for__s_71_c6 = for__s_48_c6
						header_72_c6 = header_49_c6
						tem__G__0_73_c6 = tem__G__0_50_c6
						for__xs_74_c6 = for__xs_51_c6
						pred_75_c6 = pred_52_c6
						head__30626_76_c6 = rt.LookupVar("clojure.core", "concat-list").Deref()
						goto b8
					}
				b7:
					;
					arg__30637_81_c6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_67_c6, header_64_c6})
					if callErr != nil {
						return nil, callErr
					}
					arg__30642_84_c6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_67_c6, header_64_c6})
					if callErr != nil {
						return nil, callErr
					}
					v85_c6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "list").Deref(), []vm.Value{arg__30642_84_c6})
					if callErr != nil {
						return nil, callErr
					}
					arg__30643_89_c6 = v85_c6
					f_90_c6 = f_61_c6
					for__a28150_91_c6 = for__a28150_62_c6
					for__s_92_c6 = for__s_63_c6
					header_93_c6 = header_64_c6
					tem__G__0_94_c6 = tem__G__0_65_c6
					for__xs_95_c6 = for__xs_66_c6
					pred_96_c6 = pred_67_c6
					head__30626_97_c6 = head__30626_68_c6
					goto b9
				b8:
					;
					arg__30643_89_c6 = vm.NIL
					f_90_c6 = f_69_c6
					for__a28150_91_c6 = for__a28150_70_c6
					for__s_92_c6 = for__s_71_c6
					header_93_c6 = header_72_c6
					tem__G__0_94_c6 = tem__G__0_73_c6
					for__xs_95_c6 = for__xs_74_c6
					pred_96_c6 = pred_75_c6
					head__30626_97_c6 = head__30626_76_c6
					goto b9
				b9:
					;
					arg__30647_99_c6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_95_c6})
					if callErr != nil {
						return nil, callErr
					}
					head__30651_101_c6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28150_91_c6})
					if callErr != nil {
						return nil, callErr
					}
					arg__30655_103_c6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_95_c6})
					if callErr != nil {
						return nil, callErr
					}
					arg__30656_104_c6, callErr = rt.InvokeValue(head__30651_101_c6, []vm.Value{arg__30655_103_c6})
					if callErr != nil {
						return nil, callErr
					}
					v105_c6, callErr = rt.InvokeValue(head__30626_97_c6, []vm.Value{arg__30643_89_c6, arg__30656_104_c6})
					if callErr != nil {
						return nil, callErr
					}
					v109_c6 = v105_c6
					f_110_c6 = f_90_c6
					for__a28150_111_c6 = for__a28150_91_c6
					for__s_112_c6 = for__s_92_c6
					header_113_c6 = header_93_c6
					tem__G__0_114_c6 = tem__G__0_94_c6
					goto b3
				})})
				if callErr != nil {
					return nil, callErr
				}
				return v18_c5, nil
			})})
			if callErr != nil {
				return nil, callErr
			}
			for__iter28149_68_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28150_52_c2})
			if callErr != nil {
				return nil, callErr
			}
			arg__30667_70_c2, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-preds").Deref(), []vm.Value{header_15_c2, f_5_c2})
			if callErr != nil {
				return nil, callErr
			}
			arg__30674_72_c2, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-preds").Deref(), []vm.Value{header_15_c2, f_5_c2})
			if callErr != nil {
				return nil, callErr
			}
			arg__30675_73_c2, callErr = rt.InvokeValue(for__iter28149_68_c2, []vm.Value{arg__30674_72_c2})
			if callErr != nil {
				return nil, callErr
			}
			arg__30679_75_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{tem__G__0_8_c2})
			if callErr != nil {
				return nil, callErr
			}
			head__30683_77_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28152_6_c2})
			if callErr != nil {
				return nil, callErr
			}
			arg__30687_79_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{tem__G__0_8_c2})
			if callErr != nil {
				return nil, callErr
			}
			arg__30688_80_c2, callErr = rt.InvokeValue(head__30683_77_c2, []vm.Value{arg__30687_79_c2})
			if callErr != nil {
				return nil, callErr
			}
			v81_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "concat-list").Deref(), []vm.Value{arg__30675_73_c2, arg__30688_80_c2})
			if callErr != nil {
				return nil, callErr
			}
			v85_c2 = v81_c2
			f_86_c2 = f_5_c2
			for__a28152_87_c2 = for__a28152_6_c2
			for__s_88_c2 = for__s_7_c2
			tem__G__0_89_c2 = tem__G__0_8_c2
			goto b3
		b2:
			;
			v85_c2 = vm.NIL
			f_86_c2 = f_9_c2
			for__a28152_87_c2 = for__a28152_10_c2
			for__s_88_c2 = for__s_11_c2
			tem__G__0_89_c2 = tem__G__0_12_c2
			goto b3
		b3:
			;
			return v85_c2, nil
		})})
		if callErr != nil {
			return nil, callErr
		}
		return v14_c1, nil
	})})
	if callErr != nil {
		return nil, callErr
	}
	for__iter28151_17, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28152_5})
	if callErr != nil {
		return nil, callErr
	}
	arg__30697_19, callErr = rt.InvokeValue(rt.LookupVar("ir", "blocks").Deref(), []vm.Value{f_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__30702_21, callErr = rt.InvokeValue(rt.LookupVar("ir", "blocks").Deref(), []vm.Value{f_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__30703_22, callErr = rt.InvokeValue(for__iter28151_17, []vm.Value{arg__30702_21})
	if callErr != nil {
		return nil, callErr
	}
	for__a28152_27, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "atom").Deref(), []vm.Value{vm.NIL})
	if callErr != nil {
		return nil, callErr
	}
	__37, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reset!").Deref(), []vm.Value{for__a28152_27, rt.BoxNativeFn(func(for__s_0_c7 vm.Value) (vm.Value, error) {
		var v14_c7 vm.Value
		var callErr error
		_ = v14_c7
		v14_c7, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "lazy-seq*").Deref(), []vm.Value{rt.BoxNativeFn(func() (vm.Value, error) {
			var tem__G__0_4_c8 vm.Value
			var f_5_c8 vm.Value
			var for__a28152_6_c8 vm.Value
			var for__s_7_c8 vm.Value
			var tem__G__0_8_c8 vm.Value
			var header_15_c8 vm.Value
			var for__a28150_19_c8 vm.Value
			var __33_c8 vm.Value
			var for__iter28149_35_c8 vm.Value
			var arg__32906_37_c8 vm.Value
			var arg__32913_39_c8 vm.Value
			var arg__32914_40_c8 vm.Value
			var arg__32918_42_c8 vm.Value
			var head__32922_44_c8 vm.Value
			var arg__32926_46_c8 vm.Value
			var arg__32927_47_c8 vm.Value
			var for__a28150_52_c8 vm.Value
			var __66_c8 vm.Value
			var for__iter28149_68_c8 vm.Value
			var arg__33219_70_c8 vm.Value
			var arg__33226_72_c8 vm.Value
			var arg__33227_73_c8 vm.Value
			var arg__33231_75_c8 vm.Value
			var head__33235_77_c8 vm.Value
			var arg__33239_79_c8 vm.Value
			var arg__33240_80_c8 vm.Value
			var v81_c8 vm.Value
			var f_9_c8 vm.Value
			var for__a28152_10_c8 vm.Value
			var for__s_11_c8 vm.Value
			var tem__G__0_12_c8 vm.Value
			var v85_c8 vm.Value
			var f_86_c8 vm.Value
			var for__a28152_87_c8 vm.Value
			var for__s_88_c8 vm.Value
			var tem__G__0_89_c8 vm.Value
			var callErr error
			_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = tem__G__0_4_c8, f_5_c8, for__a28152_6_c8, for__s_7_c8, tem__G__0_8_c8, header_15_c8, for__a28150_19_c8, __33_c8, for__iter28149_35_c8, arg__32906_37_c8, arg__32913_39_c8, arg__32914_40_c8, arg__32918_42_c8, head__32922_44_c8, arg__32926_46_c8, arg__32927_47_c8, for__a28150_52_c8, __66_c8, for__iter28149_68_c8, arg__33219_70_c8, arg__33226_72_c8, arg__33227_73_c8, arg__33231_75_c8, head__33235_77_c8, arg__33239_79_c8, arg__33240_80_c8, v81_c8, f_9_c8, for__a28152_10_c8, for__s_11_c8, tem__G__0_12_c8, v85_c8, f_86_c8, for__a28152_87_c8, for__s_88_c8, tem__G__0_89_c8
			tem__G__0_4_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{for__s_0_c7})
			if callErr != nil {
				return nil, callErr
			}
			if vm.IsTruthy(tem__G__0_4_c8) {
				f_5_c8 = f_0
				for__a28152_6_c8 = for__a28152_27
				for__s_7_c8 = for__s_0_c7
				tem__G__0_8_c8 = tem__G__0_4_c8
				goto b1
			} else {
				f_9_c8 = f_0
				for__a28152_10_c8 = for__a28152_27
				for__s_11_c8 = for__s_0_c7
				tem__G__0_12_c8 = tem__G__0_4_c8
				goto b2
			}
		b1:
			;
			header_15_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "first").Deref(), []vm.Value{tem__G__0_8_c8})
			if callErr != nil {
				return nil, callErr
			}
			for__a28150_19_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "atom").Deref(), []vm.Value{vm.NIL})
			if callErr != nil {
				return nil, callErr
			}
			__33_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reset!").Deref(), []vm.Value{for__a28150_19_c8, rt.BoxNativeFn(func(for__s_0_c9 vm.Value) (vm.Value, error) {
				var v18_c9 vm.Value
				var callErr error
				_ = v18_c9
				v18_c9, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "lazy-seq*").Deref(), []vm.Value{rt.BoxNativeFn(func() (vm.Value, error) {
					var tem__G__0_5_c10 vm.Value
					var f_6_c10 vm.Value
					var for__a28150_7_c10 vm.Value
					var for__s_8_c10 vm.Value
					var header_9_c10 vm.Value
					var tem__G__0_10_c10 vm.Value
					var pred_18_c10 vm.Value
					var v34_c10 vm.Value
					var f_11_c10 vm.Value
					var for__a28150_12_c10 vm.Value
					var for__s_13_c10 vm.Value
					var header_14_c10 vm.Value
					var tem__G__0_15_c10 vm.Value
					var v109_c10 vm.Value
					var f_110_c10 vm.Value
					var for__a28150_111_c10 vm.Value
					var for__s_112_c10 vm.Value
					var header_113_c10 vm.Value
					var tem__G__0_114_c10 vm.Value
					var f_19_c10 vm.Value
					var for__a28150_20_c10 vm.Value
					var for__s_21_c10 vm.Value
					var header_22_c10 vm.Value
					var tem__G__0_23_c10 vm.Value
					var for__xs_24_c10 vm.Value
					var pred_25_c10 vm.Value
					var arg__32845_37_c10 vm.Value
					var arg__32850_40_c10 vm.Value
					var v41_c10 vm.Value
					var f_26_c10 vm.Value
					var for__a28150_27_c10 vm.Value
					var for__s_28_c10 vm.Value
					var header_29_c10 vm.Value
					var tem__G__0_30_c10 vm.Value
					var for__xs_31_c10 vm.Value
					var pred_32_c10 vm.Value
					var arg__32851_45_c10 vm.Value
					var f_46_c10 vm.Value
					var for__a28150_47_c10 vm.Value
					var for__s_48_c10 vm.Value
					var header_49_c10 vm.Value
					var tem__G__0_50_c10 vm.Value
					var for__xs_51_c10 vm.Value
					var pred_52_c10 vm.Value
					var arg__32855_54_c10 vm.Value
					var head__32859_56_c10 vm.Value
					var arg__32863_58_c10 vm.Value
					var arg__32864_59_c10 vm.Value
					var v78_c10 vm.Value
					var f_61_c10 vm.Value
					var for__a28150_62_c10 vm.Value
					var for__s_63_c10 vm.Value
					var header_64_c10 vm.Value
					var tem__G__0_65_c10 vm.Value
					var for__xs_66_c10 vm.Value
					var pred_67_c10 vm.Value
					var head__32865_68_c10 vm.Value
					var arg__32876_81_c10 vm.Value
					var arg__32881_84_c10 vm.Value
					var v85_c10 vm.Value
					var f_69_c10 vm.Value
					var for__a28150_70_c10 vm.Value
					var for__s_71_c10 vm.Value
					var header_72_c10 vm.Value
					var tem__G__0_73_c10 vm.Value
					var for__xs_74_c10 vm.Value
					var pred_75_c10 vm.Value
					var head__32865_76_c10 vm.Value
					var arg__32882_89_c10 vm.Value
					var f_90_c10 vm.Value
					var for__a28150_91_c10 vm.Value
					var for__s_92_c10 vm.Value
					var header_93_c10 vm.Value
					var tem__G__0_94_c10 vm.Value
					var for__xs_95_c10 vm.Value
					var pred_96_c10 vm.Value
					var head__32865_97_c10 vm.Value
					var arg__32886_99_c10 vm.Value
					var head__32890_101_c10 vm.Value
					var arg__32894_103_c10 vm.Value
					var arg__32895_104_c10 vm.Value
					var v105_c10 vm.Value
					var callErr error
					_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = tem__G__0_5_c10, f_6_c10, for__a28150_7_c10, for__s_8_c10, header_9_c10, tem__G__0_10_c10, pred_18_c10, v34_c10, f_11_c10, for__a28150_12_c10, for__s_13_c10, header_14_c10, tem__G__0_15_c10, v109_c10, f_110_c10, for__a28150_111_c10, for__s_112_c10, header_113_c10, tem__G__0_114_c10, f_19_c10, for__a28150_20_c10, for__s_21_c10, header_22_c10, tem__G__0_23_c10, for__xs_24_c10, pred_25_c10, arg__32845_37_c10, arg__32850_40_c10, v41_c10, f_26_c10, for__a28150_27_c10, for__s_28_c10, header_29_c10, tem__G__0_30_c10, for__xs_31_c10, pred_32_c10, arg__32851_45_c10, f_46_c10, for__a28150_47_c10, for__s_48_c10, header_49_c10, tem__G__0_50_c10, for__xs_51_c10, pred_52_c10, arg__32855_54_c10, head__32859_56_c10, arg__32863_58_c10, arg__32864_59_c10, v78_c10, f_61_c10, for__a28150_62_c10, for__s_63_c10, header_64_c10, tem__G__0_65_c10, for__xs_66_c10, pred_67_c10, head__32865_68_c10, arg__32876_81_c10, arg__32881_84_c10, v85_c10, f_69_c10, for__a28150_70_c10, for__s_71_c10, header_72_c10, tem__G__0_73_c10, for__xs_74_c10, pred_75_c10, head__32865_76_c10, arg__32882_89_c10, f_90_c10, for__a28150_91_c10, for__s_92_c10, header_93_c10, tem__G__0_94_c10, for__xs_95_c10, pred_96_c10, head__32865_97_c10, arg__32886_99_c10, head__32890_101_c10, arg__32894_103_c10, arg__32895_104_c10, v105_c10
					tem__G__0_5_c10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{for__s_7_c8})
					if callErr != nil {
						return nil, callErr
					}
					if vm.IsTruthy(tem__G__0_5_c10) {
						f_6_c10 = f_5_c8
						for__a28150_7_c10 = for__a28150_19_c8
						for__s_8_c10 = for__s_7_c8
						header_9_c10 = header_15_c8
						tem__G__0_10_c10 = tem__G__0_5_c10
						goto b1
					} else {
						f_11_c10 = f_5_c8
						for__a28150_12_c10 = for__a28150_19_c8
						for__s_13_c10 = for__s_7_c8
						header_14_c10 = header_15_c8
						tem__G__0_15_c10 = tem__G__0_5_c10
						goto b2
					}
				b1:
					;
					pred_18_c10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "first").Deref(), []vm.Value{tem__G__0_10_c10})
					if callErr != nil {
						return nil, callErr
					}
					v34_c10, callErr = rt.InvokeValue(rt.LookupVar("ir.dominance", "dominates?").Deref(), []vm.Value{f_6_c10, header_9_c10, pred_18_c10})
					if callErr != nil {
						return nil, callErr
					}
					if vm.IsTruthy(v34_c10) {
						f_19_c10 = f_6_c10
						for__a28150_20_c10 = for__a28150_7_c10
						for__s_21_c10 = for__s_8_c10
						header_22_c10 = header_9_c10
						tem__G__0_23_c10 = tem__G__0_10_c10
						for__xs_24_c10 = tem__G__0_10_c10
						pred_25_c10 = pred_18_c10
						goto b4
					} else {
						f_26_c10 = f_6_c10
						for__a28150_27_c10 = for__a28150_7_c10
						for__s_28_c10 = for__s_8_c10
						header_29_c10 = header_9_c10
						tem__G__0_30_c10 = tem__G__0_10_c10
						for__xs_31_c10 = tem__G__0_10_c10
						pred_32_c10 = pred_18_c10
						goto b5
					}
				b2:
					;
					v109_c10 = vm.NIL
					f_110_c10 = f_11_c10
					for__a28150_111_c10 = for__a28150_12_c10
					for__s_112_c10 = for__s_13_c10
					header_113_c10 = header_14_c10
					tem__G__0_114_c10 = tem__G__0_15_c10
					goto b3
				b3:
					;
					return v109_c10, nil
				b4:
					;
					arg__32845_37_c10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_25_c10, header_22_c10})
					if callErr != nil {
						return nil, callErr
					}
					arg__32850_40_c10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_25_c10, header_22_c10})
					if callErr != nil {
						return nil, callErr
					}
					v41_c10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "list").Deref(), []vm.Value{arg__32850_40_c10})
					if callErr != nil {
						return nil, callErr
					}
					arg__32851_45_c10 = v41_c10
					f_46_c10 = f_19_c10
					for__a28150_47_c10 = for__a28150_20_c10
					for__s_48_c10 = for__s_21_c10
					header_49_c10 = header_22_c10
					tem__G__0_50_c10 = tem__G__0_23_c10
					for__xs_51_c10 = for__xs_24_c10
					pred_52_c10 = pred_25_c10
					goto b6
				b5:
					;
					arg__32851_45_c10 = vm.NIL
					f_46_c10 = f_26_c10
					for__a28150_47_c10 = for__a28150_27_c10
					for__s_48_c10 = for__s_28_c10
					header_49_c10 = header_29_c10
					tem__G__0_50_c10 = tem__G__0_30_c10
					for__xs_51_c10 = for__xs_31_c10
					pred_52_c10 = pred_32_c10
					goto b6
				b6:
					;
					arg__32855_54_c10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_51_c10})
					if callErr != nil {
						return nil, callErr
					}
					head__32859_56_c10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28150_47_c10})
					if callErr != nil {
						return nil, callErr
					}
					arg__32863_58_c10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_51_c10})
					if callErr != nil {
						return nil, callErr
					}
					arg__32864_59_c10, callErr = rt.InvokeValue(head__32859_56_c10, []vm.Value{arg__32863_58_c10})
					if callErr != nil {
						return nil, callErr
					}
					v78_c10, callErr = rt.InvokeValue(rt.LookupVar("ir.dominance", "dominates?").Deref(), []vm.Value{f_46_c10, header_49_c10, pred_52_c10})
					if callErr != nil {
						return nil, callErr
					}
					if vm.IsTruthy(v78_c10) {
						f_61_c10 = f_46_c10
						for__a28150_62_c10 = for__a28150_47_c10
						for__s_63_c10 = for__s_48_c10
						header_64_c10 = header_49_c10
						tem__G__0_65_c10 = tem__G__0_50_c10
						for__xs_66_c10 = for__xs_51_c10
						pred_67_c10 = pred_52_c10
						head__32865_68_c10 = rt.LookupVar("clojure.core", "concat-list").Deref()
						goto b7
					} else {
						f_69_c10 = f_46_c10
						for__a28150_70_c10 = for__a28150_47_c10
						for__s_71_c10 = for__s_48_c10
						header_72_c10 = header_49_c10
						tem__G__0_73_c10 = tem__G__0_50_c10
						for__xs_74_c10 = for__xs_51_c10
						pred_75_c10 = pred_52_c10
						head__32865_76_c10 = rt.LookupVar("clojure.core", "concat-list").Deref()
						goto b8
					}
				b7:
					;
					arg__32876_81_c10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_67_c10, header_64_c10})
					if callErr != nil {
						return nil, callErr
					}
					arg__32881_84_c10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_67_c10, header_64_c10})
					if callErr != nil {
						return nil, callErr
					}
					v85_c10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "list").Deref(), []vm.Value{arg__32881_84_c10})
					if callErr != nil {
						return nil, callErr
					}
					arg__32882_89_c10 = v85_c10
					f_90_c10 = f_61_c10
					for__a28150_91_c10 = for__a28150_62_c10
					for__s_92_c10 = for__s_63_c10
					header_93_c10 = header_64_c10
					tem__G__0_94_c10 = tem__G__0_65_c10
					for__xs_95_c10 = for__xs_66_c10
					pred_96_c10 = pred_67_c10
					head__32865_97_c10 = head__32865_68_c10
					goto b9
				b8:
					;
					arg__32882_89_c10 = vm.NIL
					f_90_c10 = f_69_c10
					for__a28150_91_c10 = for__a28150_70_c10
					for__s_92_c10 = for__s_71_c10
					header_93_c10 = header_72_c10
					tem__G__0_94_c10 = tem__G__0_73_c10
					for__xs_95_c10 = for__xs_74_c10
					pred_96_c10 = pred_75_c10
					head__32865_97_c10 = head__32865_76_c10
					goto b9
				b9:
					;
					arg__32886_99_c10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_95_c10})
					if callErr != nil {
						return nil, callErr
					}
					head__32890_101_c10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28150_91_c10})
					if callErr != nil {
						return nil, callErr
					}
					arg__32894_103_c10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_95_c10})
					if callErr != nil {
						return nil, callErr
					}
					arg__32895_104_c10, callErr = rt.InvokeValue(head__32890_101_c10, []vm.Value{arg__32894_103_c10})
					if callErr != nil {
						return nil, callErr
					}
					v105_c10, callErr = rt.InvokeValue(head__32865_97_c10, []vm.Value{arg__32882_89_c10, arg__32895_104_c10})
					if callErr != nil {
						return nil, callErr
					}
					v109_c10 = v105_c10
					f_110_c10 = f_90_c10
					for__a28150_111_c10 = for__a28150_91_c10
					for__s_112_c10 = for__s_92_c10
					header_113_c10 = header_93_c10
					tem__G__0_114_c10 = tem__G__0_94_c10
					goto b3
				})})
				if callErr != nil {
					return nil, callErr
				}
				return v18_c9, nil
			})})
			if callErr != nil {
				return nil, callErr
			}
			for__iter28149_35_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28150_19_c8})
			if callErr != nil {
				return nil, callErr
			}
			arg__32906_37_c8, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-preds").Deref(), []vm.Value{header_15_c8, f_5_c8})
			if callErr != nil {
				return nil, callErr
			}
			arg__32913_39_c8, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-preds").Deref(), []vm.Value{header_15_c8, f_5_c8})
			if callErr != nil {
				return nil, callErr
			}
			arg__32914_40_c8, callErr = rt.InvokeValue(for__iter28149_35_c8, []vm.Value{arg__32913_39_c8})
			if callErr != nil {
				return nil, callErr
			}
			arg__32918_42_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{tem__G__0_8_c8})
			if callErr != nil {
				return nil, callErr
			}
			head__32922_44_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28152_6_c8})
			if callErr != nil {
				return nil, callErr
			}
			arg__32926_46_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{tem__G__0_8_c8})
			if callErr != nil {
				return nil, callErr
			}
			arg__32927_47_c8, callErr = rt.InvokeValue(head__32922_44_c8, []vm.Value{arg__32926_46_c8})
			if callErr != nil {
				return nil, callErr
			}
			for__a28150_52_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "atom").Deref(), []vm.Value{vm.NIL})
			if callErr != nil {
				return nil, callErr
			}
			__66_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reset!").Deref(), []vm.Value{for__a28150_52_c8, rt.BoxNativeFn(func(for__s_0_c11 vm.Value) (vm.Value, error) {
				var v18_c11 vm.Value
				var callErr error
				_ = v18_c11
				v18_c11, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "lazy-seq*").Deref(), []vm.Value{rt.BoxNativeFn(func() (vm.Value, error) {
					var tem__G__0_5_c12 vm.Value
					var f_6_c12 vm.Value
					var for__a28150_7_c12 vm.Value
					var for__s_8_c12 vm.Value
					var header_9_c12 vm.Value
					var tem__G__0_10_c12 vm.Value
					var pred_18_c12 vm.Value
					var v34_c12 vm.Value
					var f_11_c12 vm.Value
					var for__a28150_12_c12 vm.Value
					var for__s_13_c12 vm.Value
					var header_14_c12 vm.Value
					var tem__G__0_15_c12 vm.Value
					var v109_c12 vm.Value
					var f_110_c12 vm.Value
					var for__a28150_111_c12 vm.Value
					var for__s_112_c12 vm.Value
					var header_113_c12 vm.Value
					var tem__G__0_114_c12 vm.Value
					var f_19_c12 vm.Value
					var for__a28150_20_c12 vm.Value
					var for__s_21_c12 vm.Value
					var header_22_c12 vm.Value
					var tem__G__0_23_c12 vm.Value
					var for__xs_24_c12 vm.Value
					var pred_25_c12 vm.Value
					var arg__33158_37_c12 vm.Value
					var arg__33163_40_c12 vm.Value
					var v41_c12 vm.Value
					var f_26_c12 vm.Value
					var for__a28150_27_c12 vm.Value
					var for__s_28_c12 vm.Value
					var header_29_c12 vm.Value
					var tem__G__0_30_c12 vm.Value
					var for__xs_31_c12 vm.Value
					var pred_32_c12 vm.Value
					var arg__33164_45_c12 vm.Value
					var f_46_c12 vm.Value
					var for__a28150_47_c12 vm.Value
					var for__s_48_c12 vm.Value
					var header_49_c12 vm.Value
					var tem__G__0_50_c12 vm.Value
					var for__xs_51_c12 vm.Value
					var pred_52_c12 vm.Value
					var arg__33168_54_c12 vm.Value
					var head__33172_56_c12 vm.Value
					var arg__33176_58_c12 vm.Value
					var arg__33177_59_c12 vm.Value
					var v78_c12 vm.Value
					var f_61_c12 vm.Value
					var for__a28150_62_c12 vm.Value
					var for__s_63_c12 vm.Value
					var header_64_c12 vm.Value
					var tem__G__0_65_c12 vm.Value
					var for__xs_66_c12 vm.Value
					var pred_67_c12 vm.Value
					var head__33178_68_c12 vm.Value
					var arg__33189_81_c12 vm.Value
					var arg__33194_84_c12 vm.Value
					var v85_c12 vm.Value
					var f_69_c12 vm.Value
					var for__a28150_70_c12 vm.Value
					var for__s_71_c12 vm.Value
					var header_72_c12 vm.Value
					var tem__G__0_73_c12 vm.Value
					var for__xs_74_c12 vm.Value
					var pred_75_c12 vm.Value
					var head__33178_76_c12 vm.Value
					var arg__33195_89_c12 vm.Value
					var f_90_c12 vm.Value
					var for__a28150_91_c12 vm.Value
					var for__s_92_c12 vm.Value
					var header_93_c12 vm.Value
					var tem__G__0_94_c12 vm.Value
					var for__xs_95_c12 vm.Value
					var pred_96_c12 vm.Value
					var head__33178_97_c12 vm.Value
					var arg__33199_99_c12 vm.Value
					var head__33203_101_c12 vm.Value
					var arg__33207_103_c12 vm.Value
					var arg__33208_104_c12 vm.Value
					var v105_c12 vm.Value
					var callErr error
					_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = tem__G__0_5_c12, f_6_c12, for__a28150_7_c12, for__s_8_c12, header_9_c12, tem__G__0_10_c12, pred_18_c12, v34_c12, f_11_c12, for__a28150_12_c12, for__s_13_c12, header_14_c12, tem__G__0_15_c12, v109_c12, f_110_c12, for__a28150_111_c12, for__s_112_c12, header_113_c12, tem__G__0_114_c12, f_19_c12, for__a28150_20_c12, for__s_21_c12, header_22_c12, tem__G__0_23_c12, for__xs_24_c12, pred_25_c12, arg__33158_37_c12, arg__33163_40_c12, v41_c12, f_26_c12, for__a28150_27_c12, for__s_28_c12, header_29_c12, tem__G__0_30_c12, for__xs_31_c12, pred_32_c12, arg__33164_45_c12, f_46_c12, for__a28150_47_c12, for__s_48_c12, header_49_c12, tem__G__0_50_c12, for__xs_51_c12, pred_52_c12, arg__33168_54_c12, head__33172_56_c12, arg__33176_58_c12, arg__33177_59_c12, v78_c12, f_61_c12, for__a28150_62_c12, for__s_63_c12, header_64_c12, tem__G__0_65_c12, for__xs_66_c12, pred_67_c12, head__33178_68_c12, arg__33189_81_c12, arg__33194_84_c12, v85_c12, f_69_c12, for__a28150_70_c12, for__s_71_c12, header_72_c12, tem__G__0_73_c12, for__xs_74_c12, pred_75_c12, head__33178_76_c12, arg__33195_89_c12, f_90_c12, for__a28150_91_c12, for__s_92_c12, header_93_c12, tem__G__0_94_c12, for__xs_95_c12, pred_96_c12, head__33178_97_c12, arg__33199_99_c12, head__33203_101_c12, arg__33207_103_c12, arg__33208_104_c12, v105_c12
					tem__G__0_5_c12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{for__s_7_c8})
					if callErr != nil {
						return nil, callErr
					}
					if vm.IsTruthy(tem__G__0_5_c12) {
						f_6_c12 = f_5_c8
						for__a28150_7_c12 = for__a28150_52_c8
						for__s_8_c12 = for__s_7_c8
						header_9_c12 = header_15_c8
						tem__G__0_10_c12 = tem__G__0_5_c12
						goto b1
					} else {
						f_11_c12 = f_5_c8
						for__a28150_12_c12 = for__a28150_52_c8
						for__s_13_c12 = for__s_7_c8
						header_14_c12 = header_15_c8
						tem__G__0_15_c12 = tem__G__0_5_c12
						goto b2
					}
				b1:
					;
					pred_18_c12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "first").Deref(), []vm.Value{tem__G__0_10_c12})
					if callErr != nil {
						return nil, callErr
					}
					v34_c12, callErr = rt.InvokeValue(rt.LookupVar("ir.dominance", "dominates?").Deref(), []vm.Value{f_6_c12, header_9_c12, pred_18_c12})
					if callErr != nil {
						return nil, callErr
					}
					if vm.IsTruthy(v34_c12) {
						f_19_c12 = f_6_c12
						for__a28150_20_c12 = for__a28150_7_c12
						for__s_21_c12 = for__s_8_c12
						header_22_c12 = header_9_c12
						tem__G__0_23_c12 = tem__G__0_10_c12
						for__xs_24_c12 = tem__G__0_10_c12
						pred_25_c12 = pred_18_c12
						goto b4
					} else {
						f_26_c12 = f_6_c12
						for__a28150_27_c12 = for__a28150_7_c12
						for__s_28_c12 = for__s_8_c12
						header_29_c12 = header_9_c12
						tem__G__0_30_c12 = tem__G__0_10_c12
						for__xs_31_c12 = tem__G__0_10_c12
						pred_32_c12 = pred_18_c12
						goto b5
					}
				b2:
					;
					v109_c12 = vm.NIL
					f_110_c12 = f_11_c12
					for__a28150_111_c12 = for__a28150_12_c12
					for__s_112_c12 = for__s_13_c12
					header_113_c12 = header_14_c12
					tem__G__0_114_c12 = tem__G__0_15_c12
					goto b3
				b3:
					;
					return v109_c12, nil
				b4:
					;
					arg__33158_37_c12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_25_c12, header_22_c12})
					if callErr != nil {
						return nil, callErr
					}
					arg__33163_40_c12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_25_c12, header_22_c12})
					if callErr != nil {
						return nil, callErr
					}
					v41_c12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "list").Deref(), []vm.Value{arg__33163_40_c12})
					if callErr != nil {
						return nil, callErr
					}
					arg__33164_45_c12 = v41_c12
					f_46_c12 = f_19_c12
					for__a28150_47_c12 = for__a28150_20_c12
					for__s_48_c12 = for__s_21_c12
					header_49_c12 = header_22_c12
					tem__G__0_50_c12 = tem__G__0_23_c12
					for__xs_51_c12 = for__xs_24_c12
					pred_52_c12 = pred_25_c12
					goto b6
				b5:
					;
					arg__33164_45_c12 = vm.NIL
					f_46_c12 = f_26_c12
					for__a28150_47_c12 = for__a28150_27_c12
					for__s_48_c12 = for__s_28_c12
					header_49_c12 = header_29_c12
					tem__G__0_50_c12 = tem__G__0_30_c12
					for__xs_51_c12 = for__xs_31_c12
					pred_52_c12 = pred_32_c12
					goto b6
				b6:
					;
					arg__33168_54_c12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_51_c12})
					if callErr != nil {
						return nil, callErr
					}
					head__33172_56_c12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28150_47_c12})
					if callErr != nil {
						return nil, callErr
					}
					arg__33176_58_c12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_51_c12})
					if callErr != nil {
						return nil, callErr
					}
					arg__33177_59_c12, callErr = rt.InvokeValue(head__33172_56_c12, []vm.Value{arg__33176_58_c12})
					if callErr != nil {
						return nil, callErr
					}
					v78_c12, callErr = rt.InvokeValue(rt.LookupVar("ir.dominance", "dominates?").Deref(), []vm.Value{f_46_c12, header_49_c12, pred_52_c12})
					if callErr != nil {
						return nil, callErr
					}
					if vm.IsTruthy(v78_c12) {
						f_61_c12 = f_46_c12
						for__a28150_62_c12 = for__a28150_47_c12
						for__s_63_c12 = for__s_48_c12
						header_64_c12 = header_49_c12
						tem__G__0_65_c12 = tem__G__0_50_c12
						for__xs_66_c12 = for__xs_51_c12
						pred_67_c12 = pred_52_c12
						head__33178_68_c12 = rt.LookupVar("clojure.core", "concat-list").Deref()
						goto b7
					} else {
						f_69_c12 = f_46_c12
						for__a28150_70_c12 = for__a28150_47_c12
						for__s_71_c12 = for__s_48_c12
						header_72_c12 = header_49_c12
						tem__G__0_73_c12 = tem__G__0_50_c12
						for__xs_74_c12 = for__xs_51_c12
						pred_75_c12 = pred_52_c12
						head__33178_76_c12 = rt.LookupVar("clojure.core", "concat-list").Deref()
						goto b8
					}
				b7:
					;
					arg__33189_81_c12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_67_c12, header_64_c12})
					if callErr != nil {
						return nil, callErr
					}
					arg__33194_84_c12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{pred_67_c12, header_64_c12})
					if callErr != nil {
						return nil, callErr
					}
					v85_c12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "list").Deref(), []vm.Value{arg__33194_84_c12})
					if callErr != nil {
						return nil, callErr
					}
					arg__33195_89_c12 = v85_c12
					f_90_c12 = f_61_c12
					for__a28150_91_c12 = for__a28150_62_c12
					for__s_92_c12 = for__s_63_c12
					header_93_c12 = header_64_c12
					tem__G__0_94_c12 = tem__G__0_65_c12
					for__xs_95_c12 = for__xs_66_c12
					pred_96_c12 = pred_67_c12
					head__33178_97_c12 = head__33178_68_c12
					goto b9
				b8:
					;
					arg__33195_89_c12 = vm.NIL
					f_90_c12 = f_69_c12
					for__a28150_91_c12 = for__a28150_70_c12
					for__s_92_c12 = for__s_71_c12
					header_93_c12 = header_72_c12
					tem__G__0_94_c12 = tem__G__0_73_c12
					for__xs_95_c12 = for__xs_74_c12
					pred_96_c12 = pred_75_c12
					head__33178_97_c12 = head__33178_76_c12
					goto b9
				b9:
					;
					arg__33199_99_c12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_95_c12})
					if callErr != nil {
						return nil, callErr
					}
					head__33203_101_c12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28150_91_c12})
					if callErr != nil {
						return nil, callErr
					}
					arg__33207_103_c12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{for__xs_95_c12})
					if callErr != nil {
						return nil, callErr
					}
					arg__33208_104_c12, callErr = rt.InvokeValue(head__33203_101_c12, []vm.Value{arg__33207_103_c12})
					if callErr != nil {
						return nil, callErr
					}
					v105_c12, callErr = rt.InvokeValue(head__33178_97_c12, []vm.Value{arg__33195_89_c12, arg__33208_104_c12})
					if callErr != nil {
						return nil, callErr
					}
					v109_c12 = v105_c12
					f_110_c12 = f_90_c12
					for__a28150_111_c12 = for__a28150_91_c12
					for__s_112_c12 = for__s_92_c12
					header_113_c12 = header_93_c12
					tem__G__0_114_c12 = tem__G__0_94_c12
					goto b3
				})})
				if callErr != nil {
					return nil, callErr
				}
				return v18_c11, nil
			})})
			if callErr != nil {
				return nil, callErr
			}
			for__iter28149_68_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28150_52_c8})
			if callErr != nil {
				return nil, callErr
			}
			arg__33219_70_c8, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-preds").Deref(), []vm.Value{header_15_c8, f_5_c8})
			if callErr != nil {
				return nil, callErr
			}
			arg__33226_72_c8, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-preds").Deref(), []vm.Value{header_15_c8, f_5_c8})
			if callErr != nil {
				return nil, callErr
			}
			arg__33227_73_c8, callErr = rt.InvokeValue(for__iter28149_68_c8, []vm.Value{arg__33226_72_c8})
			if callErr != nil {
				return nil, callErr
			}
			arg__33231_75_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{tem__G__0_8_c8})
			if callErr != nil {
				return nil, callErr
			}
			head__33235_77_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28152_6_c8})
			if callErr != nil {
				return nil, callErr
			}
			arg__33239_79_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "rest").Deref(), []vm.Value{tem__G__0_8_c8})
			if callErr != nil {
				return nil, callErr
			}
			arg__33240_80_c8, callErr = rt.InvokeValue(head__33235_77_c8, []vm.Value{arg__33239_79_c8})
			if callErr != nil {
				return nil, callErr
			}
			v81_c8, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "concat-list").Deref(), []vm.Value{arg__33227_73_c8, arg__33240_80_c8})
			if callErr != nil {
				return nil, callErr
			}
			v85_c8 = v81_c8
			f_86_c8 = f_5_c8
			for__a28152_87_c8 = for__a28152_6_c8
			for__s_88_c8 = for__s_7_c8
			tem__G__0_89_c8 = tem__G__0_8_c8
			goto b3
		b2:
			;
			v85_c8 = vm.NIL
			f_86_c8 = f_9_c8
			for__a28152_87_c8 = for__a28152_10_c8
			for__s_88_c8 = for__s_11_c8
			tem__G__0_89_c8 = tem__G__0_12_c8
			goto b3
		b3:
			;
			return v85_c8, nil
		})})
		if callErr != nil {
			return nil, callErr
		}
		return v14_c7, nil
	})})
	if callErr != nil {
		return nil, callErr
	}
	for__iter28151_39, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{for__a28152_27})
	if callErr != nil {
		return nil, callErr
	}
	arg__33249_41, callErr = rt.InvokeValue(rt.LookupVar("ir", "blocks").Deref(), []vm.Value{f_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__33254_43, callErr = rt.InvokeValue(rt.LookupVar("ir", "blocks").Deref(), []vm.Value{f_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__33255_44, callErr = rt.InvokeValue(for__iter28151_39, []vm.Value{arg__33254_43})
	if callErr != nil {
		return nil, callErr
	}
	v45, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vec").Deref(), []vm.Value{arg__33255_44})
	if callErr != nil {
		return nil, callErr
	}
	return v45, nil
}
func pure_op_QMARK_(op_0 vm.Value) (vm.Value, error) {
	var v4 vm.Value
	var callErr error
	_ = v4
	v4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "contains?").Deref(), []vm.Value{rt.LookupVar("ir.passes.licm", "pure-ops").Deref(), op_0})
	if callErr != nil {
		return nil, callErr
	}
	return v4, nil
}
func unique_pre_header(f_0 vm.Value, header_1 vm.Value, loop_set_2 vm.Value) (vm.Value, error) {
	var arg__33267_5 vm.Value
	var arg__33275_8 vm.Value
	var outs_9 vm.Value
	var arg__33280_20 vm.Value
	var v21 bool
	var f_10 vm.Value
	var header_11 vm.Value
	var loop_set_12 vm.Value
	var outs_13 vm.Value
	var v24 vm.Value
	var f_14 vm.Value
	var header_15 vm.Value
	var loop_set_16 vm.Value
	var outs_17 vm.Value
	var v28 vm.Value
	var f_29 vm.Value
	var header_30 vm.Value
	var loop_set_31 vm.Value
	var outs_32 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = arg__33267_5, arg__33275_8, outs_9, arg__33280_20, v21, f_10, header_11, loop_set_12, outs_13, v24, f_14, header_15, loop_set_16, outs_17, v28, f_29, header_30, loop_set_31, outs_32
	arg__33267_5, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-preds").Deref(), []vm.Value{header_1, f_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__33275_8, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-preds").Deref(), []vm.Value{header_1, f_0})
	if callErr != nil {
		return nil, callErr
	}
	outs_9, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "remove").Deref(), []vm.Value{loop_set_2, arg__33275_8})
	if callErr != nil {
		return nil, callErr
	}
	arg__33280_20, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "count").Deref(), []vm.Value{outs_9})
	if callErr != nil {
		return nil, callErr
	}
	v21 = rt.EqValue(arg__33280_20, vm.Int(1))
	if v21 {
		f_10 = f_0
		header_11 = header_1
		loop_set_12 = loop_set_2
		outs_13 = outs_9
		goto b1
	} else {
		f_14 = f_0
		header_15 = header_1
		loop_set_16 = loop_set_2
		outs_17 = outs_9
		goto b2
	}
b1:
	;
	v24, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "first").Deref(), []vm.Value{outs_13})
	if callErr != nil {
		return nil, callErr
	}
	v28 = v24
	f_29 = f_10
	header_30 = header_11
	loop_set_31 = loop_set_12
	outs_32 = outs_13
	goto b3
b2:
	;
	v28 = vm.NIL
	f_29 = f_14
	header_30 = header_15
	loop_set_31 = loop_set_16
	outs_32 = outs_17
	goto b3
b3:
	;
	return v28, nil
}
func loop_blocks(f_0 vm.Value, p__33994_1 vm.Value) (vm.Value, error) {
	var pred_7 vm.Value
	var header_13 vm.Value
	var arg__34016_16 vm.Value
	var arg__34026_19 vm.Value
	var v20 vm.Value
	var callErr error
	_, _, _, _, _ = pred_7, header_13, arg__34016_16, arg__34026_19, v20
	pred_7, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{p__33994_1, vm.Int(0), vm.NIL})
	if callErr != nil {
		return nil, callErr
	}
	header_13, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{p__33994_1, vm.Int(1), vm.NIL})
	if callErr != nil {
		return nil, callErr
	}
	arg__34016_16, callErr = rt.InvokeValue(rt.LookupVar("ir.passes.licm", "reachable-without").Deref(), []vm.Value{f_0, pred_7, header_13})
	if callErr != nil {
		return nil, callErr
	}
	arg__34026_19, callErr = rt.InvokeValue(rt.LookupVar("ir.passes.licm", "reachable-without").Deref(), []vm.Value{f_0, pred_7, header_13})
	if callErr != nil {
		return nil, callErr
	}
	v20, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "conj").Deref(), []vm.Value{arg__34026_19, header_13})
	if callErr != nil {
		return nil, callErr
	}
	return v20, nil
}
func licm_one_loop(f_0 vm.Value, back_edge_1 vm.Value) (vm.Value, error) {
	var header_6 vm.Value
	var loop_set_8 vm.Value
	var pre_header_10 vm.Value
	var f_11 vm.Value
	var back_edge_12 vm.Value
	var header_13 vm.Value
	var loop_set_14 vm.Value
	var pre_header_15 vm.Value
	var hoistable_23 vm.Value
	var arg__34807_29 vm.Value
	var arg__34823_36 vm.Value
	var hoisted_pairs_37 vm.Value
	var v53 vm.Value
	var f_16 vm.Value
	var back_edge_17 vm.Value
	var header_18 vm.Value
	var loop_set_19 vm.Value
	var pre_header_20 vm.Value
	var v81 vm.Value
	var f_82 vm.Value
	var back_edge_83 vm.Value
	var header_84 vm.Value
	var loop_set_85 vm.Value
	var pre_header_86 vm.Value
	var f_38 vm.Value
	var back_edge_39 vm.Value
	var header_40 vm.Value
	var loop_set_41 vm.Value
	var pre_header_42 vm.Value
	var hoistable_43 vm.Value
	var hoisted_pairs_44 vm.Value
	var arg__34835_59 vm.Value
	var arg__34846_65 vm.Value
	var v66 vm.Value
	var f_45 vm.Value
	var back_edge_46 vm.Value
	var header_47 vm.Value
	var loop_set_48 vm.Value
	var pre_header_49 vm.Value
	var hoistable_50 vm.Value
	var hoisted_pairs_51 vm.Value
	var v70 vm.Value
	var f_71 vm.Value
	var back_edge_72 vm.Value
	var header_73 vm.Value
	var loop_set_74 vm.Value
	var pre_header_75 vm.Value
	var hoistable_76 vm.Value
	var hoisted_pairs_77 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = header_6, loop_set_8, pre_header_10, f_11, back_edge_12, header_13, loop_set_14, pre_header_15, hoistable_23, arg__34807_29, arg__34823_36, hoisted_pairs_37, v53, f_16, back_edge_17, header_18, loop_set_19, pre_header_20, v81, f_82, back_edge_83, header_84, loop_set_85, pre_header_86, f_38, back_edge_39, header_40, loop_set_41, pre_header_42, hoistable_43, hoisted_pairs_44, arg__34835_59, arg__34846_65, v66, f_45, back_edge_46, header_47, loop_set_48, pre_header_49, hoistable_50, hoisted_pairs_51, v70, f_71, back_edge_72, header_73, loop_set_74, pre_header_75, hoistable_76, hoisted_pairs_77
	header_6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{back_edge_1, vm.Int(1)})
	if callErr != nil {
		return nil, callErr
	}
	loop_set_8, callErr = rt.InvokeValue(rt.LookupVar("ir.passes.licm", "loop-blocks").Deref(), []vm.Value{f_0, back_edge_1})
	if callErr != nil {
		return nil, callErr
	}
	pre_header_10, callErr = rt.InvokeValue(rt.LookupVar("ir.passes.licm", "unique-pre-header").Deref(), []vm.Value{f_0, header_6, loop_set_8})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(pre_header_10) {
		f_11 = f_0
		back_edge_12 = back_edge_1
		header_13 = header_6
		loop_set_14 = loop_set_8
		pre_header_15 = pre_header_10
		goto b1
	} else {
		f_16 = f_0
		back_edge_17 = back_edge_1
		header_18 = header_6
		loop_set_19 = loop_set_8
		pre_header_20 = pre_header_10
		goto b2
	}
b1:
	;
	hoistable_23, callErr = rt.InvokeValue(rt.LookupVar("ir.passes.licm", "collect-hoistable").Deref(), []vm.Value{f_11, loop_set_14})
	if callErr != nil {
		return nil, callErr
	}
	arg__34807_29, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "sort").Deref(), []vm.Value{hoistable_23})
	if callErr != nil {
		return nil, callErr
	}
	arg__34823_36, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "sort").Deref(), []vm.Value{hoistable_23})
	if callErr != nil {
		return nil, callErr
	}
	hoisted_pairs_37, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "mapv").Deref(), []vm.Value{rt.BoxNativeFn(func(orig_0_c1 vm.Value) (vm.Value, error) {
		var arg__34818_5_c1 vm.Value
		var v6_c1 vm.Value
		var callErr error
		_, _ = arg__34818_5_c1, v6_c1
		arg__34818_5_c1, callErr = rt.InvokeValue(rt.LookupVar("ir.passes.licm", "hoist-one!").Deref(), []vm.Value{f_11, orig_0_c1, pre_header_15})
		if callErr != nil {
			return nil, callErr
		}
		v6_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{orig_0_c1, arg__34818_5_c1})
		if callErr != nil {
			return nil, callErr
		}
		return v6_c1, nil
	}), arg__34823_36})
	if callErr != nil {
		return nil, callErr
	}
	v53, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{hoisted_pairs_37})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v53) {
		f_38 = f_11
		back_edge_39 = back_edge_12
		header_40 = header_13
		loop_set_41 = loop_set_14
		pre_header_42 = pre_header_15
		hoistable_43 = hoistable_23
		hoisted_pairs_44 = hoisted_pairs_37
		goto b4
	} else {
		f_45 = f_11
		back_edge_46 = back_edge_12
		header_47 = header_13
		loop_set_48 = loop_set_14
		pre_header_49 = pre_header_15
		hoistable_50 = hoistable_23
		hoisted_pairs_51 = hoisted_pairs_37
		goto b5
	}
b2:
	;
	v81 = vm.NIL
	f_82 = f_16
	back_edge_83 = back_edge_17
	header_84 = header_18
	loop_set_85 = loop_set_19
	pre_header_86 = pre_header_20
	goto b3
b3:
	;
	return v81, nil
b4:
	;
	arg__34835_59, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "array-map").Deref(), []vm.Value{vm.Keyword("body"), loop_set_41, vm.Keyword("preheader"), pre_header_42, vm.Keyword("header"), header_40})
	if callErr != nil {
		return nil, callErr
	}
	arg__34846_65, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "array-map").Deref(), []vm.Value{vm.Keyword("body"), loop_set_41, vm.Keyword("preheader"), pre_header_42, vm.Keyword("header"), header_40})
	if callErr != nil {
		return nil, callErr
	}
	v66, callErr = rt.InvokeValue(rt.LookupVar("ir.passes.licm", "thread-hoisted-through-header!").Deref(), []vm.Value{f_38, arg__34846_65, hoisted_pairs_44})
	if callErr != nil {
		return nil, callErr
	}
	v70 = v66
	f_71 = f_38
	back_edge_72 = back_edge_39
	header_73 = header_40
	loop_set_74 = loop_set_41
	pre_header_75 = pre_header_42
	hoistable_76 = hoistable_43
	hoisted_pairs_77 = hoisted_pairs_44
	goto b6
b5:
	;
	v70 = vm.NIL
	f_71 = f_45
	back_edge_72 = back_edge_46
	header_73 = header_47
	loop_set_74 = loop_set_48
	pre_header_75 = pre_header_49
	hoistable_76 = hoistable_50
	hoisted_pairs_77 = hoisted_pairs_51
	goto b6
b6:
	;
	v81 = v70
	f_82 = f_71
	back_edge_83 = back_edge_72
	header_84 = header_73
	loop_set_85 = loop_set_74
	pre_header_86 = pre_header_75
	goto b3
}
func operand_defined_outside_QMARK_(f_0 vm.Value, inst_1 vm.Value, loop_set_2 vm.Value) (vm.Value, error) {
	var refs_5 vm.Value
	var v15 vm.Value
	var callErr error
	_, _ = refs_5, v15
	refs_5, callErr = rt.InvokeValue(rt.LookupVar("ir", "refs").Deref(), []vm.Value{inst_1, f_0})
	if callErr != nil {
		return nil, callErr
	}
	v15, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "every?").Deref(), []vm.Value{rt.BoxNativeFn(func(r_0_c1 vm.Value) (vm.Value, error) {
		var arg__34895_4_c1 vm.Value
		var arg__34903_7_c1 vm.Value
		var arg__34904_8_c1 vm.Value
		var arg__34912_11_c1 vm.Value
		var arg__34920_14_c1 vm.Value
		var arg__34921_15_c1 vm.Value
		var v16_c1 vm.Value
		var callErr error
		_, _, _, _, _, _, _ = arg__34895_4_c1, arg__34903_7_c1, arg__34904_8_c1, arg__34912_11_c1, arg__34920_14_c1, arg__34921_15_c1, v16_c1
		arg__34895_4_c1, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-of").Deref(), []vm.Value{r_0_c1, f_0})
		if callErr != nil {
			return nil, callErr
		}
		arg__34903_7_c1, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-of").Deref(), []vm.Value{r_0_c1, f_0})
		if callErr != nil {
			return nil, callErr
		}
		arg__34904_8_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "contains?").Deref(), []vm.Value{loop_set_2, arg__34903_7_c1})
		if callErr != nil {
			return nil, callErr
		}
		arg__34912_11_c1, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-of").Deref(), []vm.Value{r_0_c1, f_0})
		if callErr != nil {
			return nil, callErr
		}
		arg__34920_14_c1, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-of").Deref(), []vm.Value{r_0_c1, f_0})
		if callErr != nil {
			return nil, callErr
		}
		arg__34921_15_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "contains?").Deref(), []vm.Value{loop_set_2, arg__34920_14_c1})
		if callErr != nil {
			return nil, callErr
		}
		v16_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "not").Deref(), []vm.Value{arg__34921_15_c1})
		if callErr != nil {
			return nil, callErr
		}
		return v16_c1, nil
	}), refs_5})
	if callErr != nil {
		return nil, callErr
	}
	return v15, nil
}
func licm(f_0 vm.Value) (vm.Value, error) {
	var arg__34929_3 vm.Value
	var arg__34934_6 vm.Value
	var doseq_seq__34924_7 vm.Value
	var doseq_loop__34925_8 vm.Value
	var f_9 vm.Value
	var doseq_seq__34924_11 vm.Value
	var doseq_loop__34925_12 vm.Value
	var f_13 vm.Value
	var be_19 vm.Value
	var v21 vm.Value
	var v23 vm.Value
	var doseq_seq__34924_14 vm.Value
	var doseq_loop__34925_15 vm.Value
	var f_16 vm.Value
	var v27 vm.Value
	var doseq_seq__34924_28 vm.Value
	var doseq_loop__34925_29 vm.Value
	var f_30 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = arg__34929_3, arg__34934_6, doseq_seq__34924_7, doseq_loop__34925_8, f_9, doseq_seq__34924_11, doseq_loop__34925_12, f_13, be_19, v21, v23, doseq_seq__34924_14, doseq_loop__34925_15, f_16, v27, doseq_seq__34924_28, doseq_loop__34925_29, f_30
	arg__34929_3, callErr = rt.InvokeValue(rt.LookupVar("ir.passes.licm", "back-edges").Deref(), []vm.Value{f_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__34934_6, callErr = rt.InvokeValue(rt.LookupVar("ir.passes.licm", "back-edges").Deref(), []vm.Value{f_0})
	if callErr != nil {
		return nil, callErr
	}
	doseq_seq__34924_7, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{arg__34934_6})
	if callErr != nil {
		return nil, callErr
	}
	doseq_loop__34925_8 = doseq_seq__34924_7
	f_9 = f_0
	goto b1
b1:
	;
	if vm.IsTruthy(doseq_loop__34925_8) {
		doseq_seq__34924_11 = doseq_seq__34924_7
		doseq_loop__34925_12 = doseq_loop__34925_8
		f_13 = f_9
		goto b2
	} else {
		doseq_seq__34924_14 = doseq_seq__34924_7
		doseq_loop__34925_15 = doseq_loop__34925_8
		f_16 = f_9
		goto b3
	}
b2:
	;
	be_19, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "first").Deref(), []vm.Value{doseq_loop__34925_12})
	if callErr != nil {
		return nil, callErr
	}
	v21, callErr = rt.InvokeValue(rt.LookupVar("ir.passes.licm", "licm-one-loop").Deref(), []vm.Value{f_13, be_19})
	if callErr != nil {
		return nil, callErr
	}
	v23, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "next").Deref(), []vm.Value{doseq_loop__34925_12})
	if callErr != nil {
		return nil, callErr
	}
	doseq_loop__34925_8 = v23
	f_9 = f_13
	goto b1
b3:
	;
	v27 = vm.NIL
	doseq_seq__34924_28 = doseq_seq__34924_14
	doseq_loop__34925_29 = doseq_loop__34925_15
	f_30 = f_16
	goto b4
b4:
	;
	return f_30, nil
}
func __gogen_wrap(fn func(args []vm.Value) (vm.Value, error)) vm.Value {
	v, _ := vm.NativeFnType.Wrap(fn)
	return v
}
func init() {
	rt.RegisterGoOverrides("ir.passes.licm", map[string]vm.Value{"hoist-one!": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 3 {
			return nil, fmt.Errorf("hoist-one!: wrong number of arguments %d (expected 3)", len(args))
		}
		return hoist_one_BANG_(args[0], args[1], args[2])
	}), "back-edges": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("back-edges: wrong number of arguments %d (expected 1)", len(args))
		}
		return back_edges(args[0])
	}), "pure-op?": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("pure-op?: wrong number of arguments %d (expected 1)", len(args))
		}
		return pure_op_QMARK_(args[0])
	}), "unique-pre-header": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 3 {
			return nil, fmt.Errorf("unique-pre-header: wrong number of arguments %d (expected 3)", len(args))
		}
		return unique_pre_header(args[0], args[1], args[2])
	}), "loop-blocks": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 2 {
			return nil, fmt.Errorf("loop-blocks: wrong number of arguments %d (expected 2)", len(args))
		}
		return loop_blocks(args[0], args[1])
	}), "licm-one-loop": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 2 {
			return nil, fmt.Errorf("licm-one-loop: wrong number of arguments %d (expected 2)", len(args))
		}
		return licm_one_loop(args[0], args[1])
	}), "operand-defined-outside?": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 3 {
			return nil, fmt.Errorf("operand-defined-outside?: wrong number of arguments %d (expected 3)", len(args))
		}
		return operand_defined_outside_QMARK_(args[0], args[1], args[2])
	}), "licm": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("licm: wrong number of arguments %d (expected 1)", len(args))
		}
		return licm(args[0])
	}),
	})
}
