//go:build gogen_ir

// Code generated by lgbgen --target=go. DO NOT EDIT.
// gogen.nsHash:       8c2dfe02bb763c95a3c7980be434ad04b77ea3533dc91e740f33f66f7158064a
// gogen.pipelineHash: f81a0be759146aabc0b9420eced6c006305bf04f7df82e999fb75a5c8206ea44

package edn

import (
	"fmt"

	rt "github.com/nooga/let-go/pkg/rt"
	vm "github.com/nooga/let-go/pkg/vm"
)

func read_string__a0(s_0 vm.Value) (vm.Value, error) {
	var v2 vm.Value
	var callErr error
	_ = v2
	v2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "read-string").Deref(), []vm.Value{s_0})
	if callErr != nil {
		return nil, callErr
	}
	return v2, nil
}
func write_string(form_0 vm.Value) (vm.Value, error) {
	var v2 vm.Value
	var callErr error
	_ = v2
	v2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "pr-str").Deref(), []vm.Value{form_0})
	if callErr != nil {
		return nil, callErr
	}
	return v2, nil
}
func __gogen_wrap(fn func(args []vm.Value) (vm.Value, error)) vm.Value {
	v, _ := vm.NativeFnType.Wrap(fn)
	return v
}
func init() {
	rt.RegisterGoOverrides("edn", map[string]vm.Value{"write-string": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("write-string: wrong number of arguments %d (expected 1)", len(args))
		}
		return write_string(args[0])
	}),
	})
}
