//go:build gogen_ir

// Code generated by lgbgen --target=go. DO NOT EDIT.
// gogen.nsHash:       9866ba54606595988cc2efa4de13936ab6c6f3e2d0ac925bbcb451f69f685b67
// gogen.pipelineHash: f81a0be759146aabc0b9420eced6c006305bf04f7df82e999fb75a5c8206ea44

package walk

import (
	"fmt"

	rt "github.com/nooga/let-go/pkg/rt"
	vm "github.com/nooga/let-go/pkg/vm"
)

func walk(inner_0 vm.Value, outer_1 vm.Value, form_2 vm.Value) (vm.Value, error) {
	var v10 vm.Value
	var inner_3 vm.Value
	var outer_4 vm.Value
	var form_5 vm.Value
	var arg__13789_14 vm.Value
	var arg__13797_18 vm.Value
	var arg__13798_19 vm.Value
	var arg__13806_22 vm.Value
	var arg__13814_26 vm.Value
	var arg__13815_27 vm.Value
	var v28 vm.Value
	var inner_6 vm.Value
	var outer_7 vm.Value
	var form_8 vm.Value
	var v37 vm.Value
	var v163 vm.Value
	var inner_164 vm.Value
	var outer_165 vm.Value
	var form_166 vm.Value
	var inner_30 vm.Value
	var outer_31 vm.Value
	var form_32 vm.Value
	var arg__13822_40 vm.Value
	var arg__13827_42 vm.Value
	var arg__13828_43 vm.Value
	var arg__13832_45 vm.Value
	var arg__13837_47 vm.Value
	var arg__13838_48 vm.Value
	var arg__13843_51 vm.Value
	var arg__13848_53 vm.Value
	var arg__13849_54 vm.Value
	var arg__13853_56 vm.Value
	var arg__13858_58 vm.Value
	var arg__13859_59 vm.Value
	var arg__13860_60 vm.Value
	var arg__13865_62 vm.Value
	var arg__13870_64 vm.Value
	var arg__13871_65 vm.Value
	var arg__13875_67 vm.Value
	var arg__13880_69 vm.Value
	var arg__13881_70 vm.Value
	var arg__13886_73 vm.Value
	var arg__13891_75 vm.Value
	var arg__13892_76 vm.Value
	var arg__13896_78 vm.Value
	var arg__13901_80 vm.Value
	var arg__13902_81 vm.Value
	var arg__13903_82 vm.Value
	var v83 vm.Value
	var inner_33 vm.Value
	var outer_34 vm.Value
	var form_35 vm.Value
	var v92 vm.Value
	var v158 vm.Value
	var inner_159 vm.Value
	var outer_160 vm.Value
	var form_161 vm.Value
	var inner_85 vm.Value
	var outer_86 vm.Value
	var form_87 vm.Value
	var arg__13912_95 vm.Value
	var arg__13919_97 vm.Value
	var v98 vm.Value
	var inner_88 vm.Value
	var outer_89 vm.Value
	var form_90 vm.Value
	var v107 vm.Value
	var v153 vm.Value
	var inner_154 vm.Value
	var outer_155 vm.Value
	var form_156 vm.Value
	var inner_100 vm.Value
	var outer_101 vm.Value
	var form_102 vm.Value
	var arg__13926_110 vm.Value
	var arg__13932_112 vm.Value
	var arg__13937_115 vm.Value
	var arg__13943_117 vm.Value
	var arg__13944_118 vm.Value
	var arg__13949_120 vm.Value
	var arg__13955_122 vm.Value
	var arg__13960_125 vm.Value
	var arg__13966_127 vm.Value
	var arg__13967_128 vm.Value
	var v129 vm.Value
	var inner_103 vm.Value
	var outer_104 vm.Value
	var form_105 vm.Value
	var v148 vm.Value
	var inner_149 vm.Value
	var outer_150 vm.Value
	var form_151 vm.Value
	var inner_131 vm.Value
	var outer_132 vm.Value
	var form_133 vm.Value
	var v139 vm.Value
	var inner_134 vm.Value
	var outer_135 vm.Value
	var form_136 vm.Value
	var v143 vm.Value
	var inner_144 vm.Value
	var outer_145 vm.Value
	var form_146 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = v10, inner_3, outer_4, form_5, arg__13789_14, arg__13797_18, arg__13798_19, arg__13806_22, arg__13814_26, arg__13815_27, v28, inner_6, outer_7, form_8, v37, v163, inner_164, outer_165, form_166, inner_30, outer_31, form_32, arg__13822_40, arg__13827_42, arg__13828_43, arg__13832_45, arg__13837_47, arg__13838_48, arg__13843_51, arg__13848_53, arg__13849_54, arg__13853_56, arg__13858_58, arg__13859_59, arg__13860_60, arg__13865_62, arg__13870_64, arg__13871_65, arg__13875_67, arg__13880_69, arg__13881_70, arg__13886_73, arg__13891_75, arg__13892_76, arg__13896_78, arg__13901_80, arg__13902_81, arg__13903_82, v83, inner_33, outer_34, form_35, v92, v158, inner_159, outer_160, form_161, inner_85, outer_86, form_87, arg__13912_95, arg__13919_97, v98, inner_88, outer_89, form_90, v107, v153, inner_154, outer_155, form_156, inner_100, outer_101, form_102, arg__13926_110, arg__13932_112, arg__13937_115, arg__13943_117, arg__13944_118, arg__13949_120, arg__13955_122, arg__13960_125, arg__13966_127, arg__13967_128, v129, inner_103, outer_104, form_105, v148, inner_149, outer_150, form_151, inner_131, outer_132, form_133, v139, inner_134, outer_135, form_136, v143, inner_144, outer_145, form_146
	v10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "list?").Deref(), []vm.Value{form_2})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v10) {
		inner_3 = inner_0
		outer_4 = outer_1
		form_5 = form_2
		goto b1
	} else {
		inner_6 = inner_0
		outer_7 = outer_1
		form_8 = form_2
		goto b2
	}
b1:
	;
	arg__13789_14, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{inner_3, form_5})
	if callErr != nil {
		return nil, callErr
	}
	arg__13797_18, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{inner_3, form_5})
	if callErr != nil {
		return nil, callErr
	}
	arg__13798_19, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "apply").Deref(), []vm.Value{rt.LookupVar("clojure.core", "list").Deref(), arg__13797_18})
	if callErr != nil {
		return nil, callErr
	}
	arg__13806_22, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{inner_3, form_5})
	if callErr != nil {
		return nil, callErr
	}
	arg__13814_26, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{inner_3, form_5})
	if callErr != nil {
		return nil, callErr
	}
	arg__13815_27, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "apply").Deref(), []vm.Value{rt.LookupVar("clojure.core", "list").Deref(), arg__13814_26})
	if callErr != nil {
		return nil, callErr
	}
	v28, callErr = rt.InvokeValue(outer_4, []vm.Value{arg__13815_27})
	if callErr != nil {
		return nil, callErr
	}
	v163 = v28
	inner_164 = inner_3
	outer_165 = outer_4
	form_166 = form_5
	goto b3
b2:
	;
	v37, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map-entry?").Deref(), []vm.Value{form_8})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v37) {
		inner_30 = inner_6
		outer_31 = outer_7
		form_32 = form_8
		goto b4
	} else {
		inner_33 = inner_6
		outer_34 = outer_7
		form_35 = form_8
		goto b5
	}
b3:
	;
	return v163, nil
b4:
	;
	arg__13822_40, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "key").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13827_42, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "key").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13828_43, callErr = rt.InvokeValue(inner_30, []vm.Value{arg__13827_42})
	if callErr != nil {
		return nil, callErr
	}
	arg__13832_45, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "val").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13837_47, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "val").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13838_48, callErr = rt.InvokeValue(inner_30, []vm.Value{arg__13837_47})
	if callErr != nil {
		return nil, callErr
	}
	arg__13843_51, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "key").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13848_53, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "key").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13849_54, callErr = rt.InvokeValue(inner_30, []vm.Value{arg__13848_53})
	if callErr != nil {
		return nil, callErr
	}
	arg__13853_56, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "val").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13858_58, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "val").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13859_59, callErr = rt.InvokeValue(inner_30, []vm.Value{arg__13858_58})
	if callErr != nil {
		return nil, callErr
	}
	arg__13860_60, callErr = rt.InvokeValue(rt.LookupVar("clojure.lang.MapEntry", "create").Deref(), []vm.Value{arg__13849_54, arg__13859_59})
	if callErr != nil {
		return nil, callErr
	}
	arg__13865_62, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "key").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13870_64, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "key").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13871_65, callErr = rt.InvokeValue(inner_30, []vm.Value{arg__13870_64})
	if callErr != nil {
		return nil, callErr
	}
	arg__13875_67, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "val").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13880_69, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "val").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13881_70, callErr = rt.InvokeValue(inner_30, []vm.Value{arg__13880_69})
	if callErr != nil {
		return nil, callErr
	}
	arg__13886_73, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "key").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13891_75, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "key").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13892_76, callErr = rt.InvokeValue(inner_30, []vm.Value{arg__13891_75})
	if callErr != nil {
		return nil, callErr
	}
	arg__13896_78, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "val").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13901_80, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "val").Deref(), []vm.Value{form_32})
	if callErr != nil {
		return nil, callErr
	}
	arg__13902_81, callErr = rt.InvokeValue(inner_30, []vm.Value{arg__13901_80})
	if callErr != nil {
		return nil, callErr
	}
	arg__13903_82, callErr = rt.InvokeValue(rt.LookupVar("clojure.lang.MapEntry", "create").Deref(), []vm.Value{arg__13892_76, arg__13902_81})
	if callErr != nil {
		return nil, callErr
	}
	v83, callErr = rt.InvokeValue(outer_31, []vm.Value{arg__13903_82})
	if callErr != nil {
		return nil, callErr
	}
	v158 = v83
	inner_159 = inner_30
	outer_160 = outer_31
	form_161 = form_32
	goto b6
b5:
	;
	v92, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq?").Deref(), []vm.Value{form_35})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v92) {
		inner_85 = inner_33
		outer_86 = outer_34
		form_87 = form_35
		goto b7
	} else {
		inner_88 = inner_33
		outer_89 = outer_34
		form_90 = form_35
		goto b8
	}
b6:
	;
	v163 = v158
	inner_164 = inner_159
	outer_165 = outer_160
	form_166 = form_161
	goto b3
b7:
	;
	arg__13912_95, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{inner_85, form_87})
	if callErr != nil {
		return nil, callErr
	}
	arg__13919_97, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{inner_85, form_87})
	if callErr != nil {
		return nil, callErr
	}
	v98, callErr = rt.InvokeValue(outer_86, []vm.Value{arg__13919_97})
	if callErr != nil {
		return nil, callErr
	}
	v153 = v98
	inner_154 = inner_85
	outer_155 = outer_86
	form_156 = form_87
	goto b9
b8:
	;
	v107, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "coll?").Deref(), []vm.Value{form_90})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v107) {
		inner_100 = inner_88
		outer_101 = outer_89
		form_102 = form_90
		goto b10
	} else {
		inner_103 = inner_88
		outer_104 = outer_89
		form_105 = form_90
		goto b11
	}
b9:
	;
	v158 = v153
	inner_159 = inner_154
	outer_160 = outer_155
	form_161 = form_156
	goto b6
b10:
	;
	arg__13926_110, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "empty").Deref(), []vm.Value{form_102})
	if callErr != nil {
		return nil, callErr
	}
	arg__13932_112, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{inner_100, form_102})
	if callErr != nil {
		return nil, callErr
	}
	arg__13937_115, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "empty").Deref(), []vm.Value{form_102})
	if callErr != nil {
		return nil, callErr
	}
	arg__13943_117, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{inner_100, form_102})
	if callErr != nil {
		return nil, callErr
	}
	arg__13944_118, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "into").Deref(), []vm.Value{arg__13937_115, arg__13943_117})
	if callErr != nil {
		return nil, callErr
	}
	arg__13949_120, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "empty").Deref(), []vm.Value{form_102})
	if callErr != nil {
		return nil, callErr
	}
	arg__13955_122, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{inner_100, form_102})
	if callErr != nil {
		return nil, callErr
	}
	arg__13960_125, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "empty").Deref(), []vm.Value{form_102})
	if callErr != nil {
		return nil, callErr
	}
	arg__13966_127, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{inner_100, form_102})
	if callErr != nil {
		return nil, callErr
	}
	arg__13967_128, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "into").Deref(), []vm.Value{arg__13960_125, arg__13966_127})
	if callErr != nil {
		return nil, callErr
	}
	v129, callErr = rt.InvokeValue(outer_101, []vm.Value{arg__13967_128})
	if callErr != nil {
		return nil, callErr
	}
	v148 = v129
	inner_149 = inner_100
	outer_150 = outer_101
	form_151 = form_102
	goto b12
b11:
	;
	if vm.IsTruthy(vm.Keyword("else")) {
		inner_131 = inner_103
		outer_132 = outer_104
		form_133 = form_105
		goto b13
	} else {
		inner_134 = inner_103
		outer_135 = outer_104
		form_136 = form_105
		goto b14
	}
b12:
	;
	v153 = v148
	inner_154 = inner_149
	outer_155 = outer_150
	form_156 = form_151
	goto b9
b13:
	;
	v139, callErr = rt.InvokeValue(outer_132, []vm.Value{form_133})
	if callErr != nil {
		return nil, callErr
	}
	v143 = v139
	inner_144 = inner_131
	outer_145 = outer_132
	form_146 = form_133
	goto b15
b14:
	;
	v143 = vm.NIL
	inner_144 = inner_134
	outer_145 = outer_135
	form_146 = form_136
	goto b15
b15:
	;
	v148 = v143
	inner_149 = inner_144
	outer_150 = outer_145
	form_151 = form_146
	goto b12
}
func postwalk(f_0 vm.Value, form_1 vm.Value) (vm.Value, error) {
	var arg__13976_5 vm.Value
	var arg__13985_10 vm.Value
	var v11 vm.Value
	var callErr error
	_, _, _ = arg__13976_5, arg__13985_10, v11
	arg__13976_5, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "partial").Deref(), []vm.Value{rt.LookupVar("clojure.walk", "postwalk").Deref(), f_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__13985_10, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "partial").Deref(), []vm.Value{rt.LookupVar("clojure.walk", "postwalk").Deref(), f_0})
	if callErr != nil {
		return nil, callErr
	}
	v11, callErr = rt.InvokeValue(rt.LookupVar("clojure.walk", "walk").Deref(), []vm.Value{arg__13985_10, f_0, form_1})
	if callErr != nil {
		return nil, callErr
	}
	return v11, nil
}
func keywordize_keys(m_0 vm.Value) (vm.Value, error) {
	var v9 vm.Value
	var callErr error
	_ = v9
	v9, callErr = rt.InvokeValue(rt.LookupVar("clojure.walk", "postwalk").Deref(), []vm.Value{rt.BoxNativeFn(func(x_0_c2 vm.Value) (vm.Value, error) {
		var v7_c2 vm.Value
		var x_2_c2 vm.Value
		var f_3_c2 vm.Value
		var arg__14045_11_c2 vm.Value
		var arg__14053_15_c2 vm.Value
		var v16_c2 vm.Value
		var x_4_c2 vm.Value
		var f_5_c2 vm.Value
		var v19_c2 vm.Value
		var x_20_c2 vm.Value
		var f_21_c2 vm.Value
		var callErr error
		_, _, _, _, _, _, _, _, _, _, _ = v7_c2, x_2_c2, f_3_c2, arg__14045_11_c2, arg__14053_15_c2, v16_c2, x_4_c2, f_5_c2, v19_c2, x_20_c2, f_21_c2
		v7_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map?").Deref(), []vm.Value{x_0_c2})
		if callErr != nil {
			return nil, callErr
		}
		if vm.IsTruthy(v7_c2) {
			x_2_c2 = x_0_c2
			f_3_c2 = rt.BoxNativeFn(func(vec__13988_0_c1 vm.Value) (vm.Value, error) {
				var k_6_c1 vm.Value
				var v_12_c1 vm.Value
				var v20_c1 vm.Value
				var vec__13988_13_c1 vm.Value
				var k_14_c1 vm.Value
				var v_15_c1 vm.Value
				var arg__14010_24_c1 vm.Value
				var v25_c1 vm.Value
				var vec__13988_16_c1 vm.Value
				var k_17_c1 vm.Value
				var v_18_c1 vm.Value
				var v28_c1 vm.Value
				var v30_c1 vm.Value
				var vec__13988_31_c1 vm.Value
				var k_32_c1 vm.Value
				var v_33_c1 vm.Value
				var callErr error
				_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = k_6_c1, v_12_c1, v20_c1, vec__13988_13_c1, k_14_c1, v_15_c1, arg__14010_24_c1, v25_c1, vec__13988_16_c1, k_17_c1, v_18_c1, v28_c1, v30_c1, vec__13988_31_c1, k_32_c1, v_33_c1
				k_6_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{vec__13988_0_c1, vm.Int(0), vm.NIL})
				if callErr != nil {
					return nil, callErr
				}
				v_12_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{vec__13988_0_c1, vm.Int(1), vm.NIL})
				if callErr != nil {
					return nil, callErr
				}
				v20_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "string?").Deref(), []vm.Value{k_6_c1})
				if callErr != nil {
					return nil, callErr
				}
				if vm.IsTruthy(v20_c1) {
					vec__13988_13_c1 = vec__13988_0_c1
					k_14_c1 = k_6_c1
					v_15_c1 = v_12_c1
					goto b1
				} else {
					vec__13988_16_c1 = vec__13988_0_c1
					k_17_c1 = k_6_c1
					v_18_c1 = v_12_c1
					goto b2
				}
			b1:
				;
				arg__14010_24_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "keyword").Deref(), []vm.Value{k_14_c1})
				if callErr != nil {
					return nil, callErr
				}
				v25_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{arg__14010_24_c1, v_15_c1})
				if callErr != nil {
					return nil, callErr
				}
				v30_c1 = v25_c1
				vec__13988_31_c1 = vec__13988_13_c1
				k_32_c1 = k_14_c1
				v_33_c1 = v_15_c1
				goto b3
			b2:
				;
				v28_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{k_17_c1, v_18_c1})
				if callErr != nil {
					return nil, callErr
				}
				v30_c1 = v28_c1
				vec__13988_31_c1 = vec__13988_16_c1
				k_32_c1 = k_17_c1
				v_33_c1 = v_18_c1
				goto b3
			b3:
				;
				return v30_c1, nil
			})
			goto b1
		} else {
			x_4_c2 = x_0_c2
			f_5_c2 = rt.BoxNativeFn(func(vec__13988_0_c1 vm.Value) (vm.Value, error) {
				var k_6_c1 vm.Value
				var v_12_c1 vm.Value
				var v20_c1 vm.Value
				var vec__13988_13_c1 vm.Value
				var k_14_c1 vm.Value
				var v_15_c1 vm.Value
				var arg__14010_24_c1 vm.Value
				var v25_c1 vm.Value
				var vec__13988_16_c1 vm.Value
				var k_17_c1 vm.Value
				var v_18_c1 vm.Value
				var v28_c1 vm.Value
				var v30_c1 vm.Value
				var vec__13988_31_c1 vm.Value
				var k_32_c1 vm.Value
				var v_33_c1 vm.Value
				var callErr error
				_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = k_6_c1, v_12_c1, v20_c1, vec__13988_13_c1, k_14_c1, v_15_c1, arg__14010_24_c1, v25_c1, vec__13988_16_c1, k_17_c1, v_18_c1, v28_c1, v30_c1, vec__13988_31_c1, k_32_c1, v_33_c1
				k_6_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{vec__13988_0_c1, vm.Int(0), vm.NIL})
				if callErr != nil {
					return nil, callErr
				}
				v_12_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{vec__13988_0_c1, vm.Int(1), vm.NIL})
				if callErr != nil {
					return nil, callErr
				}
				v20_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "string?").Deref(), []vm.Value{k_6_c1})
				if callErr != nil {
					return nil, callErr
				}
				if vm.IsTruthy(v20_c1) {
					vec__13988_13_c1 = vec__13988_0_c1
					k_14_c1 = k_6_c1
					v_15_c1 = v_12_c1
					goto b1
				} else {
					vec__13988_16_c1 = vec__13988_0_c1
					k_17_c1 = k_6_c1
					v_18_c1 = v_12_c1
					goto b2
				}
			b1:
				;
				arg__14010_24_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "keyword").Deref(), []vm.Value{k_14_c1})
				if callErr != nil {
					return nil, callErr
				}
				v25_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{arg__14010_24_c1, v_15_c1})
				if callErr != nil {
					return nil, callErr
				}
				v30_c1 = v25_c1
				vec__13988_31_c1 = vec__13988_13_c1
				k_32_c1 = k_14_c1
				v_33_c1 = v_15_c1
				goto b3
			b2:
				;
				v28_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{k_17_c1, v_18_c1})
				if callErr != nil {
					return nil, callErr
				}
				v30_c1 = v28_c1
				vec__13988_31_c1 = vec__13988_16_c1
				k_32_c1 = k_17_c1
				v_33_c1 = v_18_c1
				goto b3
			b3:
				;
				return v30_c1, nil
			})
			goto b2
		}
	b1:
		;
		arg__14045_11_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{f_3_c2, x_2_c2})
		if callErr != nil {
			return nil, callErr
		}
		arg__14053_15_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{f_3_c2, x_2_c2})
		if callErr != nil {
			return nil, callErr
		}
		v16_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "into").Deref(), []vm.Value{vm.EmptyPersistentMap, arg__14053_15_c2})
		if callErr != nil {
			return nil, callErr
		}
		v19_c2 = v16_c2
		x_20_c2 = x_2_c2
		f_21_c2 = f_3_c2
		goto b3
	b2:
		;
		v19_c2 = x_4_c2
		x_20_c2 = x_4_c2
		f_21_c2 = f_5_c2
		goto b3
	b3:
		;
		return v19_c2, nil
	}), m_0})
	if callErr != nil {
		return nil, callErr
	}
	return v9, nil
}
func prewalk(f_0 vm.Value, form_1 vm.Value) (vm.Value, error) {
	var arg__14061_5 vm.Value
	var arg__14066_7 vm.Value
	var arg__14073_12 vm.Value
	var arg__14078_14 vm.Value
	var v15 vm.Value
	var callErr error
	_, _, _, _, _ = arg__14061_5, arg__14066_7, arg__14073_12, arg__14078_14, v15
	arg__14061_5, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "partial").Deref(), []vm.Value{rt.LookupVar("clojure.walk", "prewalk").Deref(), f_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__14066_7, callErr = rt.InvokeValue(f_0, []vm.Value{form_1})
	if callErr != nil {
		return nil, callErr
	}
	arg__14073_12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "partial").Deref(), []vm.Value{rt.LookupVar("clojure.walk", "prewalk").Deref(), f_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__14078_14, callErr = rt.InvokeValue(f_0, []vm.Value{form_1})
	if callErr != nil {
		return nil, callErr
	}
	v15, callErr = rt.InvokeValue(rt.LookupVar("clojure.walk", "walk").Deref(), []vm.Value{arg__14073_12, rt.LookupVar("clojure.core", "identity").Deref(), arg__14078_14})
	if callErr != nil {
		return nil, callErr
	}
	return v15, nil
}
func prewalk_replace(smap_0 vm.Value, form_1 vm.Value) (vm.Value, error) {
	var v9 vm.Value
	var callErr error
	_ = v9
	v9, callErr = rt.InvokeValue(rt.LookupVar("clojure.walk", "prewalk").Deref(), []vm.Value{rt.BoxNativeFn(func(x_0_c1 vm.Value) (vm.Value, error) {
		var v7_c1 vm.Value
		var x_2_c1 vm.Value
		var smap_3_c1 vm.Value
		var v9_c1 vm.Value
		var x_4_c1 vm.Value
		var smap_5_c1 vm.Value
		var v12_c1 vm.Value
		var x_13_c1 vm.Value
		var smap_14_c1 vm.Value
		var callErr error
		_, _, _, _, _, _, _, _, _ = v7_c1, x_2_c1, smap_3_c1, v9_c1, x_4_c1, smap_5_c1, v12_c1, x_13_c1, smap_14_c1
		v7_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "contains?").Deref(), []vm.Value{smap_0, x_0_c1})
		if callErr != nil {
			return nil, callErr
		}
		if vm.IsTruthy(v7_c1) {
			x_2_c1 = x_0_c1
			smap_3_c1 = smap_0
			goto b1
		} else {
			x_4_c1 = x_0_c1
			smap_5_c1 = smap_0
			goto b2
		}
	b1:
		;
		v9_c1, callErr = rt.InvokeValue(smap_3_c1, []vm.Value{x_2_c1})
		if callErr != nil {
			return nil, callErr
		}
		v12_c1 = v9_c1
		x_13_c1 = x_2_c1
		smap_14_c1 = smap_3_c1
		goto b3
	b2:
		;
		v12_c1 = x_4_c1
		x_13_c1 = x_4_c1
		smap_14_c1 = smap_5_c1
		goto b3
	b3:
		;
		return v12_c1, nil
	}), form_1})
	if callErr != nil {
		return nil, callErr
	}
	return v9, nil
}
func stringify_keys(m_0 vm.Value) (vm.Value, error) {
	var v9 vm.Value
	var callErr error
	_ = v9
	v9, callErr = rt.InvokeValue(rt.LookupVar("clojure.walk", "postwalk").Deref(), []vm.Value{rt.BoxNativeFn(func(x_0_c2 vm.Value) (vm.Value, error) {
		var v7_c2 vm.Value
		var x_2_c2 vm.Value
		var f_3_c2 vm.Value
		var arg__14157_11_c2 vm.Value
		var arg__14165_15_c2 vm.Value
		var v16_c2 vm.Value
		var x_4_c2 vm.Value
		var f_5_c2 vm.Value
		var v19_c2 vm.Value
		var x_20_c2 vm.Value
		var f_21_c2 vm.Value
		var callErr error
		_, _, _, _, _, _, _, _, _, _, _ = v7_c2, x_2_c2, f_3_c2, arg__14157_11_c2, arg__14165_15_c2, v16_c2, x_4_c2, f_5_c2, v19_c2, x_20_c2, f_21_c2
		v7_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map?").Deref(), []vm.Value{x_0_c2})
		if callErr != nil {
			return nil, callErr
		}
		if vm.IsTruthy(v7_c2) {
			x_2_c2 = x_0_c2
			f_3_c2 = rt.BoxNativeFn(func(vec__14100_0_c1 vm.Value) (vm.Value, error) {
				var k_6_c1 vm.Value
				var v_12_c1 vm.Value
				var v20_c1 vm.Value
				var vec__14100_13_c1 vm.Value
				var k_14_c1 vm.Value
				var v_15_c1 vm.Value
				var arg__14122_24_c1 vm.Value
				var v25_c1 vm.Value
				var vec__14100_16_c1 vm.Value
				var k_17_c1 vm.Value
				var v_18_c1 vm.Value
				var v28_c1 vm.Value
				var v30_c1 vm.Value
				var vec__14100_31_c1 vm.Value
				var k_32_c1 vm.Value
				var v_33_c1 vm.Value
				var callErr error
				_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = k_6_c1, v_12_c1, v20_c1, vec__14100_13_c1, k_14_c1, v_15_c1, arg__14122_24_c1, v25_c1, vec__14100_16_c1, k_17_c1, v_18_c1, v28_c1, v30_c1, vec__14100_31_c1, k_32_c1, v_33_c1
				k_6_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{vec__14100_0_c1, vm.Int(0), vm.NIL})
				if callErr != nil {
					return nil, callErr
				}
				v_12_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{vec__14100_0_c1, vm.Int(1), vm.NIL})
				if callErr != nil {
					return nil, callErr
				}
				v20_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "keyword?").Deref(), []vm.Value{k_6_c1})
				if callErr != nil {
					return nil, callErr
				}
				if vm.IsTruthy(v20_c1) {
					vec__14100_13_c1 = vec__14100_0_c1
					k_14_c1 = k_6_c1
					v_15_c1 = v_12_c1
					goto b1
				} else {
					vec__14100_16_c1 = vec__14100_0_c1
					k_17_c1 = k_6_c1
					v_18_c1 = v_12_c1
					goto b2
				}
			b1:
				;
				arg__14122_24_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "name").Deref(), []vm.Value{k_14_c1})
				if callErr != nil {
					return nil, callErr
				}
				v25_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{arg__14122_24_c1, v_15_c1})
				if callErr != nil {
					return nil, callErr
				}
				v30_c1 = v25_c1
				vec__14100_31_c1 = vec__14100_13_c1
				k_32_c1 = k_14_c1
				v_33_c1 = v_15_c1
				goto b3
			b2:
				;
				v28_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{k_17_c1, v_18_c1})
				if callErr != nil {
					return nil, callErr
				}
				v30_c1 = v28_c1
				vec__14100_31_c1 = vec__14100_16_c1
				k_32_c1 = k_17_c1
				v_33_c1 = v_18_c1
				goto b3
			b3:
				;
				return v30_c1, nil
			})
			goto b1
		} else {
			x_4_c2 = x_0_c2
			f_5_c2 = rt.BoxNativeFn(func(vec__14100_0_c1 vm.Value) (vm.Value, error) {
				var k_6_c1 vm.Value
				var v_12_c1 vm.Value
				var v20_c1 vm.Value
				var vec__14100_13_c1 vm.Value
				var k_14_c1 vm.Value
				var v_15_c1 vm.Value
				var arg__14122_24_c1 vm.Value
				var v25_c1 vm.Value
				var vec__14100_16_c1 vm.Value
				var k_17_c1 vm.Value
				var v_18_c1 vm.Value
				var v28_c1 vm.Value
				var v30_c1 vm.Value
				var vec__14100_31_c1 vm.Value
				var k_32_c1 vm.Value
				var v_33_c1 vm.Value
				var callErr error
				_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = k_6_c1, v_12_c1, v20_c1, vec__14100_13_c1, k_14_c1, v_15_c1, arg__14122_24_c1, v25_c1, vec__14100_16_c1, k_17_c1, v_18_c1, v28_c1, v30_c1, vec__14100_31_c1, k_32_c1, v_33_c1
				k_6_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{vec__14100_0_c1, vm.Int(0), vm.NIL})
				if callErr != nil {
					return nil, callErr
				}
				v_12_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{vec__14100_0_c1, vm.Int(1), vm.NIL})
				if callErr != nil {
					return nil, callErr
				}
				v20_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "keyword?").Deref(), []vm.Value{k_6_c1})
				if callErr != nil {
					return nil, callErr
				}
				if vm.IsTruthy(v20_c1) {
					vec__14100_13_c1 = vec__14100_0_c1
					k_14_c1 = k_6_c1
					v_15_c1 = v_12_c1
					goto b1
				} else {
					vec__14100_16_c1 = vec__14100_0_c1
					k_17_c1 = k_6_c1
					v_18_c1 = v_12_c1
					goto b2
				}
			b1:
				;
				arg__14122_24_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "name").Deref(), []vm.Value{k_14_c1})
				if callErr != nil {
					return nil, callErr
				}
				v25_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{arg__14122_24_c1, v_15_c1})
				if callErr != nil {
					return nil, callErr
				}
				v30_c1 = v25_c1
				vec__14100_31_c1 = vec__14100_13_c1
				k_32_c1 = k_14_c1
				v_33_c1 = v_15_c1
				goto b3
			b2:
				;
				v28_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector").Deref(), []vm.Value{k_17_c1, v_18_c1})
				if callErr != nil {
					return nil, callErr
				}
				v30_c1 = v28_c1
				vec__14100_31_c1 = vec__14100_16_c1
				k_32_c1 = k_17_c1
				v_33_c1 = v_18_c1
				goto b3
			b3:
				;
				return v30_c1, nil
			})
			goto b2
		}
	b1:
		;
		arg__14157_11_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{f_3_c2, x_2_c2})
		if callErr != nil {
			return nil, callErr
		}
		arg__14165_15_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map").Deref(), []vm.Value{f_3_c2, x_2_c2})
		if callErr != nil {
			return nil, callErr
		}
		v16_c2, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "into").Deref(), []vm.Value{vm.EmptyPersistentMap, arg__14165_15_c2})
		if callErr != nil {
			return nil, callErr
		}
		v19_c2 = v16_c2
		x_20_c2 = x_2_c2
		f_21_c2 = f_3_c2
		goto b3
	b2:
		;
		v19_c2 = x_4_c2
		x_20_c2 = x_4_c2
		f_21_c2 = f_5_c2
		goto b3
	b3:
		;
		return v19_c2, nil
	}), m_0})
	if callErr != nil {
		return nil, callErr
	}
	return v9, nil
}
func postwalk_replace(smap_0 vm.Value, form_1 vm.Value) (vm.Value, error) {
	var v9 vm.Value
	var callErr error
	_ = v9
	v9, callErr = rt.InvokeValue(rt.LookupVar("clojure.walk", "postwalk").Deref(), []vm.Value{rt.BoxNativeFn(func(x_0_c1 vm.Value) (vm.Value, error) {
		var v7_c1 vm.Value
		var x_2_c1 vm.Value
		var smap_3_c1 vm.Value
		var v9_c1 vm.Value
		var x_4_c1 vm.Value
		var smap_5_c1 vm.Value
		var v12_c1 vm.Value
		var x_13_c1 vm.Value
		var smap_14_c1 vm.Value
		var callErr error
		_, _, _, _, _, _, _, _, _ = v7_c1, x_2_c1, smap_3_c1, v9_c1, x_4_c1, smap_5_c1, v12_c1, x_13_c1, smap_14_c1
		v7_c1, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "contains?").Deref(), []vm.Value{smap_0, x_0_c1})
		if callErr != nil {
			return nil, callErr
		}
		if vm.IsTruthy(v7_c1) {
			x_2_c1 = x_0_c1
			smap_3_c1 = smap_0
			goto b1
		} else {
			x_4_c1 = x_0_c1
			smap_5_c1 = smap_0
			goto b2
		}
	b1:
		;
		v9_c1, callErr = rt.InvokeValue(smap_3_c1, []vm.Value{x_2_c1})
		if callErr != nil {
			return nil, callErr
		}
		v12_c1 = v9_c1
		x_13_c1 = x_2_c1
		smap_14_c1 = smap_3_c1
		goto b3
	b2:
		;
		v12_c1 = x_4_c1
		x_13_c1 = x_4_c1
		smap_14_c1 = smap_5_c1
		goto b3
	b3:
		;
		return v12_c1, nil
	}), form_1})
	if callErr != nil {
		return nil, callErr
	}
	return v9, nil
}
func __gogen_wrap(fn func(args []vm.Value) (vm.Value, error)) vm.Value {
	v, _ := vm.NativeFnType.Wrap(fn)
	return v
}
func init() {
	rt.RegisterGoOverrides("walk", map[string]vm.Value{"walk": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 3 {
			return nil, fmt.Errorf("walk: wrong number of arguments %d (expected 3)", len(args))
		}
		return walk(args[0], args[1], args[2])
	}), "postwalk": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 2 {
			return nil, fmt.Errorf("postwalk: wrong number of arguments %d (expected 2)", len(args))
		}
		return postwalk(args[0], args[1])
	}), "keywordize-keys": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("keywordize-keys: wrong number of arguments %d (expected 1)", len(args))
		}
		return keywordize_keys(args[0])
	}), "prewalk": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 2 {
			return nil, fmt.Errorf("prewalk: wrong number of arguments %d (expected 2)", len(args))
		}
		return prewalk(args[0], args[1])
	}), "prewalk-replace": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 2 {
			return nil, fmt.Errorf("prewalk-replace: wrong number of arguments %d (expected 2)", len(args))
		}
		return prewalk_replace(args[0], args[1])
	}), "stringify-keys": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("stringify-keys: wrong number of arguments %d (expected 1)", len(args))
		}
		return stringify_keys(args[0])
	}), "postwalk-replace": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 2 {
			return nil, fmt.Errorf("postwalk-replace: wrong number of arguments %d (expected 2)", len(args))
		}
		return postwalk_replace(args[0], args[1])
	}),
	})
}
