//go:build gogen_ir

// Code generated by lgbgen --target=go. DO NOT EDIT.
// gogen.nsHash:       11222ba54af7637ba58ef661b89d02c19797015baf954875b092dd8f618b27e0
// gogen.pipelineHash: f81a0be759146aabc0b9420eced6c006305bf04f7df82e999fb75a5c8206ea44

package dce

import (
	"fmt"

	rt "github.com/nooga/let-go/pkg/rt"
	vm "github.com/nooga/let-go/pkg/vm"
)

func removable_QMARK_(nid_0 vm.Value, f_1 vm.Value) (vm.Value, error) {
	var arg__24135_3 vm.Value
	var arg__24142_6 vm.Value
	var and__x_7 vm.Value
	var nid_8 vm.Value
	var f_9 vm.Value
	var and__x_10 vm.Value
	var arg__24146_16 vm.Value
	var arg__24152_19 vm.Value
	var arg__24154_20 vm.Value
	var arg__24159_23 vm.Value
	var arg__24165_26 vm.Value
	var arg__24167_27 vm.Value
	var v28 vm.Value
	var nid_11 vm.Value
	var f_12 vm.Value
	var and__x_13 vm.Value
	var v31 vm.Value
	var nid_32 vm.Value
	var f_33 vm.Value
	var and__x_34 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = arg__24135_3, arg__24142_6, and__x_7, nid_8, f_9, and__x_10, arg__24146_16, arg__24152_19, arg__24154_20, arg__24159_23, arg__24165_26, arg__24167_27, v28, nid_11, f_12, and__x_13, v31, nid_32, f_33, and__x_34
	arg__24135_3, callErr = rt.InvokeValue(rt.LookupVar("ir", "op").Deref(), []vm.Value{nid_0, f_1})
	if callErr != nil {
		return nil, callErr
	}
	arg__24142_6, callErr = rt.InvokeValue(rt.LookupVar("ir", "op").Deref(), []vm.Value{nid_0, f_1})
	if callErr != nil {
		return nil, callErr
	}
	and__x_7, callErr = rt.InvokeValue(rt.LookupVar("ir.passes.dce", "pure-ops").Deref(), []vm.Value{arg__24142_6})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(and__x_7) {
		nid_8 = nid_0
		f_9 = f_1
		and__x_10 = and__x_7
		goto b1
	} else {
		nid_11 = nid_0
		f_12 = f_1
		and__x_13 = and__x_7
		goto b2
	}
b1:
	;
	arg__24146_16, callErr = rt.InvokeValue(rt.LookupVar("ir", "uses").Deref(), []vm.Value{f_9})
	if callErr != nil {
		return nil, callErr
	}
	arg__24152_19, callErr = rt.InvokeValue(rt.LookupVar("ir", "uses").Deref(), []vm.Value{f_9})
	if callErr != nil {
		return nil, callErr
	}
	arg__24154_20, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{arg__24152_19, nid_8})
	if callErr != nil {
		return nil, callErr
	}
	arg__24159_23, callErr = rt.InvokeValue(rt.LookupVar("ir", "uses").Deref(), []vm.Value{f_9})
	if callErr != nil {
		return nil, callErr
	}
	arg__24165_26, callErr = rt.InvokeValue(rt.LookupVar("ir", "uses").Deref(), []vm.Value{f_9})
	if callErr != nil {
		return nil, callErr
	}
	arg__24167_27, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "nth").Deref(), []vm.Value{arg__24165_26, nid_8})
	if callErr != nil {
		return nil, callErr
	}
	v28, callErr = rt.InvokeValue(rt.LookupVar("ir", "uses-empty?").Deref(), []vm.Value{arg__24167_27})
	if callErr != nil {
		return nil, callErr
	}
	v31 = v28
	nid_32 = nid_8
	f_33 = f_9
	and__x_34 = and__x_10
	goto b3
b2:
	;
	v31 = and__x_13
	nid_32 = nid_11
	f_33 = f_12
	and__x_34 = and__x_13
	goto b3
b3:
	;
	return v31, nil
}
func one_pass(f_0 vm.Value) (vm.Value, error) {
	var removed_5 vm.Value
	var arg__24180_7 vm.Value
	var arg__24185_10 vm.Value
	var doseq_seq__24170_11 vm.Value
	var doseq_loop__24171_12 vm.Value
	var f_13 vm.Value
	var removed_14 vm.Value
	var v122 bool
	var doseq_seq__24170_16 vm.Value
	var doseq_loop__24171_17 vm.Value
	var f_18 vm.Value
	var removed_19 vm.Value
	var v121 bool
	var bid_26 vm.Value
	var arg__24194_28 vm.Value
	var arg__24201_31 vm.Value
	var arg__24202_32 vm.Value
	var arg__24209_35 vm.Value
	var arg__24216_38 vm.Value
	var arg__24217_39 vm.Value
	var doseq_seq__24172_40 vm.Value
	var doseq_seq__24170_20 vm.Value
	var doseq_loop__24171_21 vm.Value
	var f_22 vm.Value
	var removed_23 vm.Value
	var v128 bool
	var v109 vm.Value
	var doseq_seq__24170_110 vm.Value
	var doseq_loop__24171_111 vm.Value
	var f_112 vm.Value
	var removed_113 vm.Value
	var v115 vm.Value
	var doseq_loop__24173_41 vm.Value
	var f_42 vm.Value
	var removed_43 vm.Value
	var bid_44 vm.Value
	var v125 bool
	var doseq_seq__24170_46 vm.Value
	var doseq_loop__24171_47 vm.Value
	var doseq_seq__24172_48 vm.Value
	var doseq_loop__24173_49 vm.Value
	var f_50 vm.Value
	var removed_51 vm.Value
	var bid_52 vm.Value
	var v124 bool
	var nid_62 vm.Value
	var v80 vm.Value
	var doseq_seq__24170_53 vm.Value
	var doseq_loop__24171_54 vm.Value
	var doseq_seq__24172_55 vm.Value
	var doseq_loop__24173_56 vm.Value
	var f_57 vm.Value
	var removed_58 vm.Value
	var bid_59 vm.Value
	var v127 bool
	var v96 vm.Value
	var doseq_seq__24170_97 vm.Value
	var doseq_loop__24171_98 vm.Value
	var doseq_seq__24172_99 vm.Value
	var doseq_loop__24173_100 vm.Value
	var f_101 vm.Value
	var removed_102 vm.Value
	var bid_103 vm.Value
	var v120 bool
	var v105 vm.Value
	var doseq_seq__24170_63 vm.Value
	var doseq_loop__24171_64 vm.Value
	var doseq_seq__24172_65 vm.Value
	var doseq_loop__24173_66 vm.Value
	var f_67 vm.Value
	var removed_68 vm.Value
	var bid_69 vm.Value
	var nid_70 vm.Value
	var v126 bool
	var v83 vm.Value
	var v87 vm.Value
	var v89 vm.Value
	var doseq_seq__24170_71 vm.Value
	var doseq_loop__24171_72 vm.Value
	var doseq_seq__24172_73 vm.Value
	var doseq_loop__24173_74 vm.Value
	var f_75 vm.Value
	var removed_76 vm.Value
	var bid_77 vm.Value
	var nid_78 vm.Value
	var v123 bool
	var v92 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = removed_5, arg__24180_7, arg__24185_10, doseq_seq__24170_11, doseq_loop__24171_12, f_13, removed_14, v122, doseq_seq__24170_16, doseq_loop__24171_17, f_18, removed_19, v121, bid_26, arg__24194_28, arg__24201_31, arg__24202_32, arg__24209_35, arg__24216_38, arg__24217_39, doseq_seq__24172_40, doseq_seq__24170_20, doseq_loop__24171_21, f_22, removed_23, v128, v109, doseq_seq__24170_110, doseq_loop__24171_111, f_112, removed_113, v115, doseq_loop__24173_41, f_42, removed_43, bid_44, v125, doseq_seq__24170_46, doseq_loop__24171_47, doseq_seq__24172_48, doseq_loop__24173_49, f_50, removed_51, bid_52, v124, nid_62, v80, doseq_seq__24170_53, doseq_loop__24171_54, doseq_seq__24172_55, doseq_loop__24173_56, f_57, removed_58, bid_59, v127, v96, doseq_seq__24170_97, doseq_loop__24171_98, doseq_seq__24172_99, doseq_loop__24173_100, f_101, removed_102, bid_103, v120, v105, doseq_seq__24170_63, doseq_loop__24171_64, doseq_seq__24172_65, doseq_loop__24173_66, f_67, removed_68, bid_69, nid_70, v126, v83, v87, v89, doseq_seq__24170_71, doseq_loop__24171_72, doseq_seq__24172_73, doseq_loop__24173_74, f_75, removed_76, bid_77, nid_78, v123, v92
	removed_5, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "atom").Deref(), []vm.Value{vm.Boolean(false)})
	if callErr != nil {
		return nil, callErr
	}
	arg__24180_7, callErr = rt.InvokeValue(rt.LookupVar("ir", "blocks").Deref(), []vm.Value{f_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__24185_10, callErr = rt.InvokeValue(rt.LookupVar("ir", "blocks").Deref(), []vm.Value{f_0})
	if callErr != nil {
		return nil, callErr
	}
	doseq_seq__24170_11, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{arg__24185_10})
	if callErr != nil {
		return nil, callErr
	}
	doseq_loop__24171_12 = doseq_seq__24170_11
	f_13 = f_0
	removed_14 = removed_5
	v122 = true
	goto b1
b1:
	;
	if vm.IsTruthy(doseq_loop__24171_12) {
		doseq_seq__24170_16 = doseq_seq__24170_11
		doseq_loop__24171_17 = doseq_loop__24171_12
		f_18 = f_13
		removed_19 = removed_14
		v121 = v122
		goto b2
	} else {
		doseq_seq__24170_20 = doseq_seq__24170_11
		doseq_loop__24171_21 = doseq_loop__24171_12
		f_22 = f_13
		removed_23 = removed_14
		v128 = v122
		goto b3
	}
b2:
	;
	bid_26, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "first").Deref(), []vm.Value{doseq_loop__24171_17})
	if callErr != nil {
		return nil, callErr
	}
	arg__24194_28, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-insts").Deref(), []vm.Value{bid_26, f_18})
	if callErr != nil {
		return nil, callErr
	}
	arg__24201_31, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-insts").Deref(), []vm.Value{bid_26, f_18})
	if callErr != nil {
		return nil, callErr
	}
	arg__24202_32, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vec").Deref(), []vm.Value{arg__24201_31})
	if callErr != nil {
		return nil, callErr
	}
	arg__24209_35, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-insts").Deref(), []vm.Value{bid_26, f_18})
	if callErr != nil {
		return nil, callErr
	}
	arg__24216_38, callErr = rt.InvokeValue(rt.LookupVar("ir", "block-insts").Deref(), []vm.Value{bid_26, f_18})
	if callErr != nil {
		return nil, callErr
	}
	arg__24217_39, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vec").Deref(), []vm.Value{arg__24216_38})
	if callErr != nil {
		return nil, callErr
	}
	doseq_seq__24172_40, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{arg__24217_39})
	if callErr != nil {
		return nil, callErr
	}
	doseq_loop__24173_41 = doseq_seq__24172_40
	f_42 = f_18
	removed_43 = removed_19
	bid_44 = bid_26
	v125 = v121
	goto b5
b3:
	;
	v109 = vm.NIL
	doseq_seq__24170_110 = doseq_seq__24170_20
	doseq_loop__24171_111 = doseq_loop__24171_21
	f_112 = f_22
	removed_113 = removed_23
	goto b4
b4:
	;
	v115, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "deref").Deref(), []vm.Value{removed_113})
	if callErr != nil {
		return nil, callErr
	}
	return v115, nil
b5:
	;
	if vm.IsTruthy(doseq_loop__24173_41) {
		doseq_seq__24170_46 = doseq_seq__24170_16
		doseq_loop__24171_47 = doseq_loop__24171_17
		doseq_seq__24172_48 = doseq_seq__24172_40
		doseq_loop__24173_49 = doseq_loop__24173_41
		f_50 = f_42
		removed_51 = removed_43
		bid_52 = bid_44
		v124 = v125
		goto b6
	} else {
		doseq_seq__24170_53 = doseq_seq__24170_16
		doseq_loop__24171_54 = doseq_loop__24171_17
		doseq_seq__24172_55 = doseq_seq__24172_40
		doseq_loop__24173_56 = doseq_loop__24173_41
		f_57 = f_42
		removed_58 = removed_43
		bid_59 = bid_44
		v127 = v125
		goto b7
	}
b6:
	;
	nid_62, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "first").Deref(), []vm.Value{doseq_loop__24173_49})
	if callErr != nil {
		return nil, callErr
	}
	v80, callErr = rt.InvokeValue(rt.LookupVar("ir.passes.dce", "removable?").Deref(), []vm.Value{nid_62, f_50})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v80) {
		doseq_seq__24170_63 = doseq_seq__24170_46
		doseq_loop__24171_64 = doseq_loop__24171_47
		doseq_seq__24172_65 = doseq_seq__24172_48
		doseq_loop__24173_66 = doseq_loop__24173_49
		f_67 = f_50
		removed_68 = removed_51
		bid_69 = bid_52
		nid_70 = nid_62
		v126 = v124
		goto b9
	} else {
		doseq_seq__24170_71 = doseq_seq__24170_46
		doseq_loop__24171_72 = doseq_loop__24171_47
		doseq_seq__24172_73 = doseq_seq__24172_48
		doseq_loop__24173_74 = doseq_loop__24173_49
		f_75 = f_50
		removed_76 = removed_51
		bid_77 = bid_52
		nid_78 = nid_62
		v123 = v124
		goto b10
	}
b7:
	;
	v96 = vm.NIL
	doseq_seq__24170_97 = doseq_seq__24170_53
	doseq_loop__24171_98 = doseq_loop__24171_54
	doseq_seq__24172_99 = doseq_seq__24172_55
	doseq_loop__24173_100 = doseq_loop__24173_56
	f_101 = f_57
	removed_102 = removed_58
	bid_103 = bid_59
	v120 = v127
	goto b8
b8:
	;
	v105, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "next").Deref(), []vm.Value{doseq_loop__24171_98})
	if callErr != nil {
		return nil, callErr
	}
	doseq_loop__24171_12 = v105
	f_13 = f_101
	removed_14 = removed_102
	v122 = v120
	goto b1
b9:
	;
	v83, callErr = rt.InvokeValue(rt.LookupVar("ir", "remove-inst!").Deref(), []vm.Value{f_67, bid_69, nid_70})
	if callErr != nil {
		return nil, callErr
	}
	v87, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "reset!").Deref(), []vm.Value{removed_68, vm.Boolean(v126)})
	if callErr != nil {
		return nil, callErr
	}
	v89, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "next").Deref(), []vm.Value{doseq_loop__24173_66})
	if callErr != nil {
		return nil, callErr
	}
	doseq_loop__24173_41 = v89
	f_42 = f_67
	removed_43 = removed_68
	bid_44 = bid_69
	v125 = v126
	goto b5
b10:
	;
	v92, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "next").Deref(), []vm.Value{doseq_loop__24173_74})
	if callErr != nil {
		return nil, callErr
	}
	doseq_loop__24173_41 = v92
	f_42 = f_75
	removed_43 = removed_76
	bid_44 = bid_77
	v125 = v123
	goto b5
}
func dce(f_0 vm.Value) (vm.Value, error) {
	var f_2 vm.Value
	var v7 vm.Value
	var f_4 vm.Value
	var f_5 vm.Value
	var v12 vm.Value
	var f_13 vm.Value
	var callErr error
	_, _, _, _, _, _ = f_2, v7, f_4, f_5, v12, f_13
	f_2 = f_0
	goto b1
b1:
	;
	v7, callErr = rt.InvokeValue(rt.LookupVar("ir.passes.dce", "one-pass").Deref(), []vm.Value{f_2})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v7) {
		f_4 = f_2
		goto b2
	} else {
		f_5 = f_2
		goto b3
	}
b2:
	;
	f_2 = f_4
	goto b1
b3:
	;
	v12 = vm.NIL
	f_13 = f_5
	goto b4
b4:
	;
	return f_13, nil
}
func __gogen_wrap(fn func(args []vm.Value) (vm.Value, error)) vm.Value {
	v, _ := vm.NativeFnType.Wrap(fn)
	return v
}
func init() {
	rt.RegisterGoOverrides("ir.passes.dce", map[string]vm.Value{"removable?": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 2 {
			return nil, fmt.Errorf("removable?: wrong number of arguments %d (expected 2)", len(args))
		}
		return removable_QMARK_(args[0], args[1])
	}), "one-pass": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("one-pass: wrong number of arguments %d (expected 1)", len(args))
		}
		return one_pass(args[0])
	}), "dce": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("dce: wrong number of arguments %d (expected 1)", len(args))
		}
		return dce(args[0])
	}),
	})
}
