//go:build gogen_ir

// Code generated by lgbgen --target=go. DO NOT EDIT.
// gogen.nsHash:       71fa536939d4bdd3d6bbe4915913aeb66aa944e1c9cd8e29fe83a759d3185fd3
// gogen.pipelineHash: f81a0be759146aabc0b9420eced6c006305bf04f7df82e999fb75a5c8206ea44

package test

import (
	"fmt"

	rt "github.com/nooga/let-go/pkg/rt"
	vm "github.com/nooga/let-go/pkg/vm"
)

func testing_contexts_str() (vm.Value, error) {
	var arg__15560_6 vm.Value
	var arg__15568_14 vm.Value
	var arg__15569_15 vm.Value
	var arg__15577_23 vm.Value
	var arg__15585_31 vm.Value
	var arg__15586_32 vm.Value
	var v33 vm.Value
	var callErr error
	_, _, _, _, _, _, _ = arg__15560_6, arg__15568_14, arg__15569_15, arg__15577_23, arg__15585_31, arg__15586_32, v33
	arg__15560_6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "interpose").Deref(), []vm.Value{vm.String(" > "), rt.LookupVar("clojure.test", "*testing-contexts*").Deref()})
	if callErr != nil {
		return nil, callErr
	}
	arg__15568_14, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "interpose").Deref(), []vm.Value{vm.String(" > "), rt.LookupVar("clojure.test", "*testing-contexts*").Deref()})
	if callErr != nil {
		return nil, callErr
	}
	arg__15569_15, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "apply").Deref(), []vm.Value{rt.LookupVar("clojure.core", "str").Deref(), arg__15568_14})
	if callErr != nil {
		return nil, callErr
	}
	arg__15577_23, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "interpose").Deref(), []vm.Value{vm.String(" > "), rt.LookupVar("clojure.test", "*testing-contexts*").Deref()})
	if callErr != nil {
		return nil, callErr
	}
	arg__15585_31, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "interpose").Deref(), []vm.Value{vm.String(" > "), rt.LookupVar("clojure.test", "*testing-contexts*").Deref()})
	if callErr != nil {
		return nil, callErr
	}
	arg__15586_32, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "apply").Deref(), []vm.Value{rt.LookupVar("clojure.core", "str").Deref(), arg__15585_31})
	if callErr != nil {
		return nil, callErr
	}
	v33, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "str").Deref(), []vm.Value{arg__15586_32})
	if callErr != nil {
		return nil, callErr
	}
	return v33, nil
}
func apply_template(argv_0 vm.Value, expr_1 vm.Value, values_2 vm.Value) (vm.Value, error) {
	var arg__15632_4 vm.Value
	var arg__15640_7 vm.Value
	var v8 vm.Value
	var callErr error
	_, _, _ = arg__15632_4, arg__15640_7, v8
	arg__15632_4, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "zipmap").Deref(), []vm.Value{argv_0, values_2})
	if callErr != nil {
		return nil, callErr
	}
	arg__15640_7, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "zipmap").Deref(), []vm.Value{argv_0, values_2})
	if callErr != nil {
		return nil, callErr
	}
	v8, callErr = rt.InvokeValue(rt.LookupVar("clojure.walk", "postwalk-replace").Deref(), []vm.Value{arg__15640_7, expr_1})
	if callErr != nil {
		return nil, callErr
	}
	return v8, nil
}
func __gogen_wrap(fn func(args []vm.Value) (vm.Value, error)) vm.Value {
	v, _ := vm.NativeFnType.Wrap(fn)
	return v
}
func init() {
	rt.RegisterGoOverrides("test", map[string]vm.Value{"testing-contexts-str": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 0 {
			return nil, fmt.Errorf("testing-contexts-str: wrong number of arguments %d (expected 0)", len(args))
		}
		return testing_contexts_str()
	}), "apply-template": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 3 {
			return nil, fmt.Errorf("apply-template: wrong number of arguments %d (expected 3)", len(args))
		}
		return apply_template(args[0], args[1], args[2])
	}),
	})
}
