//go:build gogen_ir

// Code generated by lgbgen --target=go. DO NOT EDIT.
// gogen.nsHash:       63987781e8f3bcc23171e36f366867fb1332c3e37c1491874346ef0508f07fde
// gogen.pipelineHash: f81a0be759146aabc0b9420eced6c006305bf04f7df82e999fb75a5c8206ea44

package pprint

import (
	"fmt"

	rt "github.com/nooga/let-go/pkg/rt"
	vm "github.com/nooga/let-go/pkg/vm"
)

func indent_str(n_0 vm.Value) (vm.Value, error) {
	var arg__14872_5 vm.Value
	var arg__14880_11 vm.Value
	var v12 vm.Value
	var callErr error
	_, _, _ = arg__14872_5, arg__14880_11, v12
	arg__14872_5, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "repeat").Deref(), []vm.Value{n_0, vm.String(" ")})
	if callErr != nil {
		return nil, callErr
	}
	arg__14880_11, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "repeat").Deref(), []vm.Value{n_0, vm.String(" ")})
	if callErr != nil {
		return nil, callErr
	}
	v12, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "apply").Deref(), []vm.Value{rt.LookupVar("clojure.core", "str").Deref(), arg__14880_11})
	if callErr != nil {
		return nil, callErr
	}
	return v12, nil
}
func pprint__a0(form_0 vm.Value) (vm.Value, error) {
	var arg__14884_2 vm.Value
	var arg__14889_5 vm.Value
	var v6 vm.Value
	var callErr error
	_, _, _ = arg__14884_2, arg__14889_5, v6
	arg__14884_2, callErr = rt.InvokeValue(rt.LookupVar("clojure.pprint", "pprint-str").Deref(), []vm.Value{form_0})
	if callErr != nil {
		return nil, callErr
	}
	arg__14889_5, callErr = rt.InvokeValue(rt.LookupVar("clojure.pprint", "pprint-str").Deref(), []vm.Value{form_0})
	if callErr != nil {
		return nil, callErr
	}
	v6, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "println").Deref(), []vm.Value{arg__14889_5})
	if callErr != nil {
		return nil, callErr
	}
	return v6, nil
}
func pprint_str__a0(form_0 vm.Value) (vm.Value, error) {
	var v4 vm.Value
	var callErr error
	_ = v4
	v4, callErr = rt.InvokeValue(rt.LookupVar("clojure.pprint", "pprint-str").Deref(), []vm.Value{form_0, vm.Int(0)})
	if callErr != nil {
		return nil, callErr
	}
	return v4, nil
}
func pprint_str__a1(form_0 vm.Value, indent_1 vm.Value) (vm.Value, error) {
	var v7 vm.Value
	var form_2 vm.Value
	var indent_3 vm.Value
	var v10 vm.Value
	var form_4 vm.Value
	var indent_5 vm.Value
	var v17 vm.Value
	var v103 vm.Value
	var form_104 vm.Value
	var indent_105 vm.Value
	var form_12 vm.Value
	var indent_13 vm.Value
	var v24 vm.Value
	var form_14 vm.Value
	var indent_15 vm.Value
	var v31 vm.Value
	var v99 vm.Value
	var form_100 vm.Value
	var indent_101 vm.Value
	var form_26 vm.Value
	var indent_27 vm.Value
	var arg__15500_34 vm.Value
	var arg__15508_39 vm.Value
	var v42 vm.Value
	var form_28 vm.Value
	var indent_29 vm.Value
	var v49 vm.Value
	var v95 vm.Value
	var form_96 vm.Value
	var indent_97 vm.Value
	var form_44 vm.Value
	var indent_45 vm.Value
	var v56 vm.Value
	var form_46 vm.Value
	var indent_47 vm.Value
	var v63 vm.Value
	var v91 vm.Value
	var form_92 vm.Value
	var indent_93 vm.Value
	var form_58 vm.Value
	var indent_59 vm.Value
	var v70 vm.Value
	var form_60 vm.Value
	var indent_61 vm.Value
	var v87 vm.Value
	var form_88 vm.Value
	var indent_89 vm.Value
	var form_72 vm.Value
	var indent_73 vm.Value
	var v79 vm.Value
	var form_74 vm.Value
	var indent_75 vm.Value
	var v83 vm.Value
	var form_84 vm.Value
	var indent_85 vm.Value
	var callErr error
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = v7, form_2, indent_3, v10, form_4, indent_5, v17, v103, form_104, indent_105, form_12, indent_13, v24, form_14, indent_15, v31, v99, form_100, indent_101, form_26, indent_27, arg__15500_34, arg__15508_39, v42, form_28, indent_29, v49, v95, form_96, indent_97, form_44, indent_45, v56, form_46, indent_47, v63, v91, form_92, indent_93, form_58, indent_59, v70, form_60, indent_61, v87, form_88, indent_89, form_72, indent_73, v79, form_74, indent_75, v83, form_84, indent_85
	v7, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "map?").Deref(), []vm.Value{form_0})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v7) {
		form_2 = form_0
		indent_3 = indent_1
		goto b1
	} else {
		form_4 = form_0
		indent_5 = indent_1
		goto b2
	}
b1:
	;
	v10, callErr = rt.InvokeValue(rt.LookupVar("clojure.pprint", "pprint-map").Deref(), []vm.Value{form_2, indent_3})
	if callErr != nil {
		return nil, callErr
	}
	v103 = v10
	form_104 = form_2
	indent_105 = indent_3
	goto b3
b2:
	;
	v17, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "vector?").Deref(), []vm.Value{form_4})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v17) {
		form_12 = form_4
		indent_13 = indent_5
		goto b4
	} else {
		form_14 = form_4
		indent_15 = indent_5
		goto b5
	}
b3:
	;
	return v103, nil
b4:
	;
	v24, callErr = rt.InvokeValue(rt.LookupVar("clojure.pprint", "pprint-seq").Deref(), []vm.Value{form_12, vm.String("["), vm.String("]"), indent_13})
	if callErr != nil {
		return nil, callErr
	}
	v99 = v24
	form_100 = form_12
	indent_101 = indent_13
	goto b6
b5:
	;
	v31, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "set?").Deref(), []vm.Value{form_14})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v31) {
		form_26 = form_14
		indent_27 = indent_15
		goto b7
	} else {
		form_28 = form_14
		indent_29 = indent_15
		goto b8
	}
b6:
	;
	v103 = v99
	form_104 = form_100
	indent_105 = indent_101
	goto b3
b7:
	;
	arg__15500_34, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{form_26})
	if callErr != nil {
		return nil, callErr
	}
	arg__15508_39, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq").Deref(), []vm.Value{form_26})
	if callErr != nil {
		return nil, callErr
	}
	v42, callErr = rt.InvokeValue(rt.LookupVar("clojure.pprint", "pprint-seq").Deref(), []vm.Value{arg__15508_39, vm.String("#{"), vm.String("}"), indent_27})
	if callErr != nil {
		return nil, callErr
	}
	v95 = v42
	form_96 = form_26
	indent_97 = indent_27
	goto b9
b8:
	;
	v49, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "list?").Deref(), []vm.Value{form_28})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v49) {
		form_44 = form_28
		indent_45 = indent_29
		goto b10
	} else {
		form_46 = form_28
		indent_47 = indent_29
		goto b11
	}
b9:
	;
	v99 = v95
	form_100 = form_96
	indent_101 = indent_97
	goto b6
b10:
	;
	v56, callErr = rt.InvokeValue(rt.LookupVar("clojure.pprint", "pprint-seq").Deref(), []vm.Value{form_44, vm.String("("), vm.String(")"), indent_45})
	if callErr != nil {
		return nil, callErr
	}
	v91 = v56
	form_92 = form_44
	indent_93 = indent_45
	goto b12
b11:
	;
	v63, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "seq?").Deref(), []vm.Value{form_46})
	if callErr != nil {
		return nil, callErr
	}
	if vm.IsTruthy(v63) {
		form_58 = form_46
		indent_59 = indent_47
		goto b13
	} else {
		form_60 = form_46
		indent_61 = indent_47
		goto b14
	}
b12:
	;
	v95 = v91
	form_96 = form_92
	indent_97 = indent_93
	goto b9
b13:
	;
	v70, callErr = rt.InvokeValue(rt.LookupVar("clojure.pprint", "pprint-seq").Deref(), []vm.Value{form_58, vm.String("("), vm.String(")"), indent_59})
	if callErr != nil {
		return nil, callErr
	}
	v87 = v70
	form_88 = form_58
	indent_89 = indent_59
	goto b15
b14:
	;
	if vm.IsTruthy(vm.Keyword("else")) {
		form_72 = form_60
		indent_73 = indent_61
		goto b16
	} else {
		form_74 = form_60
		indent_75 = indent_61
		goto b17
	}
b15:
	;
	v91 = v87
	form_92 = form_88
	indent_93 = indent_89
	goto b12
b16:
	;
	v79, callErr = rt.InvokeValue(rt.LookupVar("clojure.core", "pr-str").Deref(), []vm.Value{form_72})
	if callErr != nil {
		return nil, callErr
	}
	v83 = v79
	form_84 = form_72
	indent_85 = indent_73
	goto b18
b17:
	;
	v83 = vm.NIL
	form_84 = form_74
	indent_85 = indent_75
	goto b18
b18:
	;
	v87 = v83
	form_88 = form_84
	indent_89 = indent_85
	goto b15
}
func __gogen_wrap(fn func(args []vm.Value) (vm.Value, error)) vm.Value {
	v, _ := vm.NativeFnType.Wrap(fn)
	return v
}
func init() {
	rt.RegisterGoOverrides("pprint", map[string]vm.Value{"indent-str": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("indent-str: wrong number of arguments %d (expected 1)", len(args))
		}
		return indent_str(args[0])
	}),
	})
}
