//go:build gogen_ir

// Code generated by lgbgen --target=go. DO NOT EDIT.
// gogen.nsHash:       18bd9fafe8d2d04ab3333a3d1d2fe5ae46d5fa82182b11b6aef36b1a92a445b0
// gogen.pipelineHash: f81a0be759146aabc0b9420eced6c006305bf04f7df82e999fb75a5c8206ea44

package passes

import (
	"fmt"

	rt "github.com/nooga/let-go/pkg/rt"
	vm "github.com/nooga/let-go/pkg/vm"
)

func replace_refs_BANG_(new_refs_0 vm.Value) (vm.Value, error) {
	var v6 vm.Value
	var callErr error
	_ = v6
	v6, callErr = rt.InvokeValue(rt.LookupVar("ir", "set-refs!").Deref(), []vm.Value{rt.LookupVar("ir.passes", "*current-fn*").Deref(), rt.LookupVar("ir.passes", "*current-inst*").Deref(), new_refs_0})
	if callErr != nil {
		return nil, callErr
	}
	return v6, nil
}
func replace_aux_BANG_(new_aux_0 vm.Value) (vm.Value, error) {
	var v6 vm.Value
	var callErr error
	_ = v6
	v6, callErr = rt.InvokeValue(rt.LookupVar("ir", "set-aux!").Deref(), []vm.Value{rt.LookupVar("ir.passes", "*current-fn*").Deref(), rt.LookupVar("ir.passes", "*current-inst*").Deref(), new_aux_0})
	if callErr != nil {
		return nil, callErr
	}
	return v6, nil
}
func remove_BANG_() (vm.Value, error) {
	var arg__15937_4 vm.Value
	var arg__15944_11 vm.Value
	var v13 vm.Value
	var callErr error
	_, _, _ = arg__15937_4, arg__15944_11, v13
	arg__15937_4, callErr = rt.InvokeValue(rt.LookupVar("ir.zipper", "current-block").Deref(), []vm.Value{rt.LookupVar("ir.passes", "*current-zip*").Deref()})
	if callErr != nil {
		return nil, callErr
	}
	arg__15944_11, callErr = rt.InvokeValue(rt.LookupVar("ir.zipper", "current-block").Deref(), []vm.Value{rt.LookupVar("ir.passes", "*current-zip*").Deref()})
	if callErr != nil {
		return nil, callErr
	}
	v13, callErr = rt.InvokeValue(rt.LookupVar("ir", "remove-inst!").Deref(), []vm.Value{rt.LookupVar("ir.passes", "*current-fn*").Deref(), arg__15944_11, rt.LookupVar("ir.passes", "*current-inst*").Deref()})
	if callErr != nil {
		return nil, callErr
	}
	return v13, nil
}
func __gogen_wrap(fn func(args []vm.Value) (vm.Value, error)) vm.Value {
	v, _ := vm.NativeFnType.Wrap(fn)
	return v
}
func init() {
	rt.RegisterGoOverrides("ir.passes", map[string]vm.Value{"replace-refs!": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("replace-refs!: wrong number of arguments %d (expected 1)", len(args))
		}
		return replace_refs_BANG_(args[0])
	}), "replace-aux!": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 1 {
			return nil, fmt.Errorf("replace-aux!: wrong number of arguments %d (expected 1)", len(args))
		}
		return replace_aux_BANG_(args[0])
	}), "remove!": __gogen_wrap(func(args []vm.Value) (vm.Value, error) {
		if len(args) != 0 {
			return nil, fmt.Errorf("remove!: wrong number of arguments %d (expected 0)", len(args))
		}
		return remove_BANG_()
	}),
	})
}
